### ISSUE TITLE
MO Federal Income Tax Deduction

### ISSUE THREAD

**Issue by nmrodelo** [PolicyEngine/policyengine-us#1050]
Detailed here: https://revisor.mo.gov/main/OneSection.aspx?section=143.171 

Variable to add:
MO Federal Income Tax Deduction

Params to add:
MO Federal Income Tax Deduction Schedule

**Comment by MaxGhenis** [comment]
This looks like it creates a circular dependency, given the SALT deduction. Alternative interpretations welcome.

**Comment by feenberg** [comment]
On Thu, 7 Jul 2022, Max Ghenis wrote:

> 
> @feenberg Could you share how taxsim deals with this program? Are we misreading it as
> creating a circular dependency?

The law allows a deduction for tax paid, not tax liability. So there is 
nothing circular in the law. Taxsim can't do that, so it iterates 3 times 
on tax liability and uses that. That is


   calculate federal liability f0 with no state tax
   calculate state liability s0
   calculate federal liability with s0 state tax deduction
   calculate state s1 liability with f0 federal tax deduction
   calculate federal liability with s1 deduction
   ...for 3 rounds


Dan

**Comment by MaxGhenis** [comment]
@feenberg thanks for sharing your procedure. I'm not sure I follow how it's not circular though; the law and forms look to ask for liability.

[MO Chapter 143.171](https://revisor.mo.gov/main/OneSection.aspx?section=143.171)(2)(1) says:
>an individual taxpayer shall be allowed a deduction equal to a percentage of his or her federal income tax liability under Chapter 1 of the Internal Revenue Code for the same taxable year for which the Missouri return is being filed

Line 11 of [MO-1040](https://dor.mo.gov/forms/MO-1040%20Fillable%20Calculating_2021.pdf) says:
>Total tax from federal return. Do not enter federal tax withheld.

Line 11 sums lines 9 and 10, which are described in the [MO-1040 instruction booklet](https://dor.mo.gov/forms/MO-1040%20Instructions_2021.pdf#page=7):
>LINE 9 - TAX FROM FEDERAL RETURN
Use the chart in next column to locate your tax on your federal return. Do not enter your federal income tax withheld as shown on your Form(s) W-2 or federal return.
If you have an earned income credit, you must subtract the credit from the tax on your federal return. If a negative amount is calculated, enter “0”. If you used a method other than the federal tax table to determine your federal tax, attach the appropriate schedule.

<img width="353" alt="image" src="https://user-images.githubusercontent.com/6076111/177920119-7ec09225-22aa-4a8c-9498-330749f703a6.png">

>LINE 10 - OTHER FEDERAL TAX
Enter the total amount of:
• Schedule 2, Part 1, Line 3;
• Schedule 2, Part 2, Line 8 and 10;
• Any recapture taxes included on Schedule 2, Part 2, Line 21; and
• Schedule 3, Part 1, Line 1.
For amended returns enter the other taxes reported on Line 10 of Federal Form 1040X except: do not include self-employment tax, FICA tax, or railroad retirement tax on this line. Attach a copy of your federal return (pages 1 and 2) and applicable schedules. Attach a copy of Federal Form(s) 4255, 8611, or 8828 if claiming recapture taxes.

Notably those don't refer to line 12a of the [federal 1040](https://www.irs.gov/pub/irs-pdf/f1040.pdf) or the [Schedule A](https://www.irs.gov/pub/irs-pdf/f1040sa.pdf) where state income tax is itemized.

**Comment by nikhilwoodruff** [comment]
Thanks for this clarification @feenberg- though to confirm, a reform to federal tax rules would affect state tax revenues in this way?

**Comment by nikhilwoodruff** [comment]
Thanks for this clarification @feenberg- though to confirm, a reform to federal tax rules would affect state tax revenues in this way?

**Comment by nikhilwoodruff** [comment]
Thanks for this clarification @feenberg- though to confirm, a reform to federal tax rules would affect state tax revenues in this way?

**Comment by feenberg** [comment]
An increase in the federal tax would decrease the state tax through the 
contemporanious dependence in taxsim. A change in state tax would affect 
federal tax in the same year, although in law the effect would show up in 
the same year only to the extent that withholding and estimated tax 
changed in conformance with the new law.

Dan

**Comment by MaxGhenis** [comment]
I contacted the MO Department of Revenue. Their response did not acknowledge the circularity.

From: me
To: income@dor.mo.gov

>Dear DOR Income Tax Department,
We are building an [open source microsimulation model](http://github.com/policyengine/openfisca-us) of taxes and benefits across the US. While implementing Missouri's income tax, we found what appeared to be circular logic between state and federal taxes: federal income tax liability affects the Missouri income tax via the federal income tax deduction, which in turn affects federal income tax liability via the state and local tax deduction. We've documented the relevant parts of the law and tax forms [here](https://github.com/PolicyEngine/openfisca-us/issues/1050#issuecomment-1178553942).
Could you please let us know if we've misinterpreted the law? If not, how to Missouri taxpayers deal with this circularity?

DOR response:

>Thank you for contacting the Missouri Department of Revenue.
The Federal income tax deduction does affect the Missouri income tax deduction as it lowers tax liability.
However, I am unsure of how the federal laws work with tax liability. For that answer, you may need to contact the IRS.

**Comment by MaxGhenis** [comment]
Closing as we've implemented this, with the caveat applied to several similar programs that it will change after we model state tax withholding
