### ISSUE TITLE
Idaho standard deduction

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#1160]
![Screenshot_20220723-092509.png](https://user-images.githubusercontent.com/6076111/180613951-82c082e8-b033-425a-b7bf-3fa3e5f2b5ac.png)![Screenshot_20220723-092533.png](https://user-images.githubusercontent.com/6076111/180613962-08ef8757-8c0e-4d11-9696-59d2dddfaca5.png)

**Comment by PavelMakarchuk** [comment]
Completed
