### ISSUE TITLE
Idaho Child Tax Credit 

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#1162]
$205 non refundable 
![Screenshot_20220723-102447.png](https://user-images.githubusercontent.com/6076111/180616079-9584a0ad-af3d-4bf2-befe-66633ec74c39.png)

**Comment by martinholmer** [comment]
In the 0.508.3 version, the `id_ctc` variable formula is complete, but the value of this variable has not yet been added into the Idaho non-refundable credits total.  So, this issue is still open, but could be closed with a small amount of development work.
