### ISSUE TITLE
Determine strategy to handle circular dependency in the IRC

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-us#1235]
As far as I can tell, this is a genuine circular dependency within the Internal Revenue Code. Many States allow federal itemized deductions (excluding the SALT deduction) to be deducted from taxable income. This often (by omission of an exclusion) includes the QBI deduction. However, the QBI deduction has a means-test which involves a definition of income that requires calculation of SALT: AGI less non-QBI deductions (including the SALT deduction). So, in summary, the circular dependency is: State tax -> itemized deductions -> QBI deduction -> QBI means-test income -> SALT -> State tax.

So far, our solution has been exclude the QBI deduction from State itemized deductions. We chose this because we think that it has the smallest negative impact on tax accuracy.

@martinholmer have you encountered this in your model or TAXSIM?

**Comment by MaxGhenis** [comment]
@MattHJensen @jdebacker

**Comment by martinholmer** [comment]
@nikhilwoodruff said in issue #1235:
> So, in summary, the circular dependency is: State tax -> itemized deductions -> QBI deduction -> QBI means-test income -> SALT -> State tax.

And then @martinholmer replied:
> All I can say is that you can use tax preparation software (for example, Turbo Tax) to compute the QBID before you have installed any Turbo Tax state tax module.

I guess your point is that once a taxpayer installs a state module for Turbo Tax, that the state calculations could change federal itemized deductions enough that the federal QBID amount would change.  Is that your point?   I have no idea whether or not this is how Turbo Tax works.  And I have no idea how TAXSIM35 works in this regard.

**Comment by nikhilwoodruff** [comment]
I'm not sure about Turbo Tax. But my only point here is that the circular dependency exists in the law (so any model must deviate from it in order to run).

**Comment by martinholmer** [comment]
@nikhilwoodruff said in issue #1235:
> But my only point here is that the circular dependency exists in the law (so any model must deviate from it in order to run).

What is it about the circular dependency that prevents a model that has both a federal module and a state module from doing the calculations exactly correctly?

**Comment by nikhilwoodruff** [comment]
> @nikhilwoodruff said in issue #1235:
> 
> > But my only point here is that the circular dependency exists in the law (so any model must deviate from it in order to run).
> 
> 
> 
> What is it about the circular dependency that prevents a model that has both a federal module and a state module from doing the calculations exactly correctly?

A circular dependency causes a recursion error. If I define State tax as a function of State tax, then I'll enter an infinite loop and never terminate.

**Comment by martinholmer** [comment]
@nikhilwoodruff said in issue #1235:
>> What is it about the circular dependency that prevents a model that has both a federal module and a state module from doing the calculations exactly correctly?
>
> A circular dependency causes a recursion error. If I define State tax as a function of State tax, then I'll enter an infinite loop and never terminate.

How many states have this circularity?  My only experience with state income taxes is Massachusetts, which does not have this circularity.  MA income tax does depend on federal AGI via the phase-out of the EITC, but as far as I can tell does not not depend on federal taxable income.

In the original comment in the issue #1235 conversation, @nikhilwoodruff said:
> So far, our solution has been exclude the QBI deduction from State itemized deductions. We chose this because we think that it has the smallest negative impact on tax accuracy.

This seems sensible.  As best I can tell, federal `qualified_business_income_deduction` is being ignored only in the Maryland income tax logic.  Is that because the MD legislation specifically excludes it?   Or is this an example of your solution to the circularity problem?

**Comment by MaxGhenis** [comment]
The solution to this is to model state tax withholding, which is what produces the SALT deduction (rather than actual state tax liability).

**Comment by MaxGhenis** [comment]
Closing - see #1409 which encompasses the need to model state tax withholding
