### ISSUE TITLE
Simplify `dividend_income` formula to not impute in-formula qualified dividends

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-us#1247]
To move imputation to the data stage. Will aim to complete by tomorrow.

**Comment by martinholmer** [comment]
@nikhilwoodruff,  Hasn't issue #1247 been resolved for some time?  The split between qualified and non-qualified dividend income is now being done in the CPS dataset preparation.  If you agree, can you close #1247?

**Comment by nikhilwoodruff** [comment]
Yep, thanks for spotting Martin!
