### ISSUE TITLE
Maine personal exemption

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#1297]
$4,300 per filer, income-tested
https://www.maine.gov/revenue/sites/maine.gov.revenue/files/inline-files/21_1040me_book_gen_instr_revMay2022.pdf

**Comment by k-obenschain** [comment]
<img width="788" alt="image" src="https://user-images.githubusercontent.com/29848542/218334705-3d0706c3-525d-4277-abba-86a82d08e73c.png">

**Comment by k-obenschain** [comment]
<img width="792" alt="image" src="https://user-images.githubusercontent.com/29848542/218766525-819bf1ef-55a7-42d5-8dba-06a53bd7b610.png">
