### ISSUE TITLE
MO EITC

### ISSUE THREAD

**Issue by nmrodelo** [PolicyEngine/policyengine-us#1358]
Missouri Appears to have enacted an EITC match, effective Jan. 1, 2023, more info here: https://revisor.mo.gov/main/PageSearch.aspx?tb1=earned%20income%20tax%20credit&op=and&tb2=&idx=2

**Comment by MaxGhenis** [comment]
I think this is the last piece to finish the MO state income tax

**Comment by nmrodelo** [comment]
@MaxGhenis cool, will start this weekend

**Comment by PavelMakarchuk** [comment]
Completed in #1749
