### ISSUE TITLE
SNAP

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-us#138]
The Supplemental Nutrition Assistance Program (food stamps) is a federal program with some rules varying by state. It provided [$56 billion in benefits in 2019 and $74 billion in 2020](https://fns-prod.azureedge.net/sites/default/files/resource-files/SNAPsummary-11.pdf).

Rough computation tree:
```
spm_unit_snap
  snap_net_income
    components of snap net income
  snap_gross_income
  snap_shelter_deduction
    shelter_costs
    state_group
      state
    is_usda_elderly_disabled
      age (>60)
      is_usda_disabled
        set of program enrollment
  snap_net_income_pre_shelter
    gross_income
    snap_standard_deduction
      state_group
      household_size
    snap_earnings_deduction
      gross_income
```

**Comment by MaxGhenis** [comment]
Section 2.3.3 of the [Policy Rules Database documentation](https://www.atlantafed.org/-/media/documents/economic-mobility-and-resilience/advancing-careers-for-low-income-families/policy-rules-database/policy-rules-database-technical-manual.pdf) indicates we should start with childcare, housing, and energy subsidies:

>Several public assistance programs interact either directly through the categorical eligibility
provisions or gross income calculations, or indirectly through net expense deductions. The
following list shows the suggested order of calculating values of public assistance programs to
ensure accurate calculations.
> 1. Calculate all child-care-related subsidies (Child Care Development Fund, or CCDF;
Head Start; and Voluntary Pre-K and compute net child care costs.
>2. Compute the value of the Housing Choice Voucher Program (Section 8). Take into
account the deduction of net child care expenses from Step 1 that can affect eligibility for
and value of the subsidy. Calculate corresponding net housing expenses.
>3. Compute the value of LIHEAP subsidies along with the corresponding value of net utility
expenses
>4. Calculate the value of the SNAP subsidies. SNAP calculations take net child care
expenses (from Step 1), net housing expenses (from Step 2), and net utility expenses
(from Step 3) as inputs to produce an accurate subsidy value. Deduct these net
expenses from the family’s income to determine eligibility for and value of a subsidy.
>5. Calculate the federal CDCTC using net child care costs (from Step 1). See the
Interactions between Taxes and Tax Credits section for details.
