### ISSUE TITLE
After model name change, cannot execute the CLI test capability

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1455]
Is it possible that the model-name-change process was not complete?  If it was complete, how do you execute the model `test` CLI with the new model.  My guess about how to do that (and I'm guessing because I don't know of any documentation on this topic) didn't work as you can see below:

```
(policyengine-us) PolicyEngine-US% conda list olicy
# packages in environment at //Users/mrh/anaconda3/envs/policyengine-us:
#
# Name                    Version                   Build  Channel
policyengine-core         1.7.0                    pypi_0    pypi
policyengine-us           0.174.2                  pypi_0    pypi

(policyengine-us) PolicyEngine-US% policyengine-us --help
100%|█████████████████████████████████████| 20.9M/20.9M [00:00<00:00, 47.9MiB/s]
100%|█████████████████████████████████████| 42.0M/42.0M [00:01<00:00, 37.2MiB/s]
Traceback (most recent call last):
  File "//Users/mrh/anaconda3/envs/policyengine-us/bin/policyengine-us", line 5, in <module>
    from policyengine_us.tools.cli import main
ModuleNotFoundError: No module named 'policyengine_us.tools.cli'
```

**Comment by MaxGhenis** [comment]
The new CLI is all in PolicyEngine Core:
```
policyengine-core test test.yaml_or_folder -c policyengine_us
```

**Comment by martinholmer** [comment]
In issue #1455, @MaxGhenis said:
> ... the new CLI is all in PolicyEngine Core:
>`policyengine-core test test.yaml_or_folder -c policyengine_us`

Thanks for the tip.   Is this documented somewhere?

**Comment by MaxGhenis** [comment]
Yes we've documented it in the policyengine-core page here: https://policyengine.github.io/policyengine-core/usage/cli.html#test

It also somewhat resembles https://openfisca.org/doc/openfisca-python-api/openfisca_test.html

Sorry for the confusion, we may put together a migration guide and will include this. Closing but feel free to reopen or reach out if unclear.
