### ISSUE TITLE
Maine tax rate schedules

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#1474]
<img width="369" alt="image" src="https://user-images.githubusercontent.com/6076111/198884744-dd06d7f2-3a89-43bd-8117-56be2391cc98.png">

https://www.maine.gov/revenue/sites/maine.gov.revenue/files/inline-files/21_1040me_book_gen_instr_revMay2022.pdf

**Comment by PavelMakarchuk** [comment]
Fixed by #2070
