### ISSUE TITLE
Ohio retirement credit

### ISSUE THREAD

**Issue by shrinidhi20** [PolicyEngine/policyengine-us#1499]
To qualify for this credit, all of the following
must be true:
● Your modified adjusted gross income less
exemptions is less than $100,000;
● You must have received income from a
pension, profit-sharing, or retirement plan
(such as traditional IRAs or 401(k) plans);
● This income is included in your Ohio adjusted gross income;
● This income was received on account of
retirement; AND
● You have not previously taken the Ohio
lump sum retirement credit.
Use Table 2 on page 29 to determine your
credit based on your and your spouse's (if
filing jointly) total eligible retirement income.
Amounts deducted on the Ohio Schedule
of Adjustments (such as Social Security
benefits and uniformed services retirement
income) do not qualify for this credit. The
maximum credit per return is $200.
See R.C. 5747.055(B)
https://tax.ohio.gov/static/forms/ohio_individual/individual/2021/pit-it1040-booklet.pdf#page=20
https://codes.ohio.gov/ohio-revised-code/section-5747.055
![image](https://user-images.githubusercontent.com/118138118/201780702-21180c46-f868-46f1-91be-0bdbca9f45e2.png)

**Comment by MaxGhenis** [comment]
Now complete
