### ISSUE TITLE
Need to reassess CPS-to-PolicyEngineUS income variable mapping

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1506]
In the [cps.py](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/data/datasets/cps/cps.py) file, the following code assigns CPS income variables to PolicyEngineUS variables:
```
def add_personal_income_variables(cps: h5py.File, person: DataFrame):
    """Add income variables.

    Args:
        cps (h5py.File): The CPS dataset file.
        person (DataFrame): The CPS person table.
    """
    cps["employment_income"] = person.WSAL_VAL
    cps["interest_income"] = person.INT_VAL
    cps["self_employment_income"] = person.SEMP_VAL
    cps["farm_income"] = person.FRSE_VAL
    cps["dividend_income"] = person.DIV_VAL
    cps["rental_income"] = person.RNT_VAL
    cps["social_security"] = person.SS_VAL
    cps["unemployment_compensation"] = person.UC_VAL
    cps["pension_income"] = person.PNSN_VAL + person.ANN_VAL
    cps["alimony_income"] = (person.OI_OFF == 20) * person.OI_VAL
    cps["tanf_reported"] = person.PAW_VAL
    cps["ssi_reported"] = person.SSI_VAL
    cps["pension_contributions"] = person.RETCB_VAL
    cps[
        "long_term_capital_gains"
    ] = person.CAP_VAL  # Assume all CPS capital gains are long-term
    cps["receives_wic"] = person.WICYN == 1
```

The above code raises several questions:
* How should interest be split between taxable and tax-exempt?
* Should all self-employment income be **not** qualified business income?
* How should dividends be split between qualified and non-qualified?
* How should pensions be split between taxable and tax-exempt?
* How should capital gains be split between short-term and long-term?

**Comment by MaxGhenis** [comment]
In the near term, we can use averages from administrative totals like we do for dividends.

Longer term, we plan to allocate using our synthimpute package for random forest-based quantile regression, pulling data from the PUF.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> In the near term, we can use averages from administrative totals like we do for dividends.

OK, but what about the **immediate** term?   

How about fixing the errors by making some simple assumptions just like is currently being done with capital gains?  This would mean making the following assumptions:

* All CPS interest is taxable
* All CPS dividends are qualified
* All CPS pensions are taxable
* All CPS capital gains are long-term (as assumed now)

Then in subsequent pull requests, you can add the splitting fractions based on administrative data.

Shall I prepare a pull request that makes the above simple splitting assumptions?  These changes can be implemented before merging #1502 and #1505.

**Comment by MaxGhenis** [comment]
### Taxable interest fraction 

[Publication 1304, Table 1.4](https://www.irs.gov/statistics/soi-tax-stats-individual-statistical-tables-by-size-of-adjusted-gross-income#_grp1) reports $127,375,994,000 taxable interest income and 59,449,107,000 tax-exempt interest income in 2020, so we can set the taxable fraction to $127,375,994,000 / ($127,375,994,000 + $59,449,107,000) = **0.68.**

### Qualified dividend fraction

We already have this as a calibration parameter.

### Taxable pension fraction

I can't immediately find this, so 100% sounds good.

### Long-term capital gains fraction

[These SOI tables](https://www.irs.gov/statistics/soi-tax-stats-sales-of-capital-assets-reported-on-individual-tax-returns)  reported $98,678,301,211 and $745,745,186,120 in short- and long-term capital gains, respectively, in 2012. So we can set the long-term fraction to $745,745,186,120 / ($745,745,186,120 + $98,678,301,211) = **0.88**.

**Comment by martinholmer** [comment]
A simple first step in resolving this issue is in pull request #1507.
The direction of subsequent steps is outlined in issue #1513.
