### ISSUE TITLE
Resolve US discrepancies against TAXSIM35 for 2021

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1538]
In the table below, the issues blocking progress are:
#1571 (US) and a TAXSIM35 QBID bug that has been reported.

```
Number of tax units (out of random samples of 100,000) with
an income tax difference between PolicyEngineUS and TAXSIM35
[sample assumptions are described below this table]
[what a 'difference' means is explained below this table]
--------------------------------------------------------------
: MODEL VERSIONS :   :  MODEL DIFFERENCES  :   : DIFF CAUSES :
PolEngUS  TAXSIM35   REGION SAMPLE NUM.DIFFS   RELEVANT.ISSUES
--------------------------------------------------------------
0.188.4   12/08/22       US    a21     15709   #1571
0.188.4   12/08/22       US    b21     10566   #1571
0.188.4   12/08/22       US    c21     21865   #1571, others
0.188.4   12/08/22       US    d21         0   NONE
0.188.4   12/08/22       US    e21         0   NONE
0.188.4   12/08/22       US    f21     13106   TAXSIM35 bug
--------------------------------------------------------------
```

_Sample assumptions:_

**a21**: 2021 tax units consisting of married couples and single individuals having from zero to four dependents of various ages; with tax units having various types of expenses [rent, local property taxes, mortgage interest, and child care]; and with tax units having various types of incomes [wages, qualified dividends, non-qualified dividends, taxable interest, short-term capital gains (not losses), long-term capital gains (not losses), taxable pension benefits, and social security benefits].

**b21**: same as the **a21** sample except adds self-employment income from a non-qualified business.

**c21**: same as the **a21** sample except adds self-employment income from a qualified business with some being a SSTB and others not being a SSTB.

**d21**: same as the **a21** sample except there are no child care expenses.

**e21**: same as the **b21** sample except there are no child care expenses.

**f21**: same as the **c21** sample except there are no child care expenses.

_Difference definition:_

A difference is generally defined to mean taxes from the two models being more than one cent apart.  The following tests use a definition of difference that is larger than one cent:

**b21** : three cents (PolicyEngine single-precision rounding error)
**c21** : three cents (PolicyEngine single-precision rounding error)
**e21** : three cents (PolicyEngine single-precision rounding error)
**f21** : three cents (PolicyEngine single-precision rounding error)

**Comment by martinholmer** [comment]
Update US validation against TAXSIM35 results in issue #1538 for the PolicyEngineUS 0.184.1 version.  The TAXSIM35 bug has been reported and will be fixed later today.

**Comment by martinholmer** [comment]
Update US validation against TAXSIM35 results in issue https://github.com/PolicyEngine/policyengine-us/issues/1538 for the PolicyEngineUS 0.184.1 version and the TAXSIM35 12/08/22 version. What looks like a TAXSIM35 bug will be reported to NBER on Friday.

**Comment by MaxGhenis** [comment]
If you have a chance, I'd look forward to seeing these updated with dependents now post-CTC-fix

**Comment by martinholmer** [comment]
Update US validation against TAXSIM35 results in issue #1538 for the PolicyEngineUS 0.188.4 version and TAXSIM35 12/08/22 version.  Note that the samples are completely different than in prior versions of these US validation tests.

**Comment by martinholmer** [comment]
When using the `taxsim35-emulation` branch of PolicyEngineUS 0.196.1 version and TAXSIM35 12/30/22 version, all differences are eliminated in the six samples being used in this issue.   See issue #993 for details.

Give these results, this issue is being closed in favor of the broader issue #993.

**Comment by MaxGhenis** [comment]
Amazing milestone!! Thanks for your work on this @martinholmer!

**Comment by nikhilwoodruff** [comment]
Awesome to see this, thanks Martin!
