### ISSUE TITLE
Make ODC non-refundable in 2021

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1577]
Pull request #1575 appears to be incorrect.
The rationale for making this change was the "taxsim.app" GUI.
Usually the basis for making a change in the model's tax logic is a reading of tax legislation or a reading of the relevant tax forms.

A review of the [2021 Schedule 8812](https://www.irs.gov/pub/irs-prior/f1040s8--2021.pdf) and the [2021 Form 1040](https://www.irs.gov/pub/irs-prior/f1040--2021.pdf) suggests that even for 2021 the ODC was non-refundable.  On Schedule 8812, line 14h is described as "This is your credit for other dependents [ODC]. Enter this amount on line 19 of your Form 1040."  Then when we look at Form 1040, we see line 19 described as "Nonrefundable child tax credit or credit for other dependents from Schedule 8812."

So, the 2021 IRS forms seem to indicate that the ODC has always been non-refundable (even in 2021).   Are the forms misleading?   What does the tax legislation say about whether or not the other dependent credit (ODC) was refundable in 2021?

**Comment by MaxGhenis** [comment]
I was referring to both taxsim and my reading of [IRC § 24(i)(1)](https://www.law.cornell.edu/uscode/text/26/24#i_1), which removes 24(d) (which specifies refundability) for 2021. But you're right, the tax form is clear, so I must have mistaken how this subsection interacts with the TCJA. Thanks for the report.
