### ISSUE TITLE
MO property tax credit logic is incomplete

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1608]
Currently the MO property tax credit amount is always zero because the formula logic is incomplete.  Part of the incompleteness has been highlighted in issue #1361.  The main missing piece is the phase-out (or reduction) of the credit as income rises.

**Comment by MaxGhenis** [comment]
I think the issue is primarily https://github.com/PolicyEngine/policyengine-us/issues/1285 

We asked the MO DOR to clarify this but they never got back to us.
