### ISSUE TITLE
Social Security doesn't sum components for individual households

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#1620]
See this in the app:

https://www.loom.com/share/7dc1cb59c2004f59a3ceede5547f1d65

This is because `parameters(period).simulation.disabled_programs` includes `social_security`, so it only uses reported values, even outside of the microsim.

Short term fix is probably something like what @nikhilwoodruff did in #1618 to check if we're in a microsimulation. Longer term we should impute each SS benefit type in the microsim based on age, disability status, etc.

**Comment by gsadowsky** [comment]
This is still an issue. Entering Social Security retirement benefits does not affect net income. [Here's an example.](https://policyengine.org/us/household?focus=gov.ssa.ss.social_security_retirement.social_security_retirement&household=996)
