### ISSUE TITLE
Add multiplier for SNAP emergency allotments to model it ending in March 2023

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#1630]
We parameterize the termination of SNAP emergency allotments by having it end in March 2023. As a stopgap before modeling it monthly, we can model it annually but multiply by the share of the year it'll be active. And as a super-stopgap we could manually multiply 2023 SNAP EAs by 1/6.

**Comment by nikhilwoodruff** [comment]
I'll make `snap_emergency_allotment` monthly

**Comment by MaxGhenis** [comment]
SNAP EA is now monthly
