### ISSUE TITLE
Incomplete MD AGI subtraction for child/dependent care expenses

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1647]
The 2021 MD Form 502 instructions say this:

<img width="793" alt="Screenshot 2023-01-04 at 3 58 18 PM" src="https://user-images.githubusercontent.com/12170745/210649053-8e96a53c-2563-4ecf-9b56-7383c5c1a8c6.png">

The code is missing part (b) of the Line 9 instructions.

**Comment by MaxGhenis** [comment]
I don't think it's incomplete. As described in the comment, we follow the [MD legal code](https://casetext.com/statute/code-of-maryland/article-tax-general/title-10-income-tax/subtitle-2-maryland-taxable-income-calculations-for-individual/part-ii-maryland-adjusted-gross-income/section-10-208-effective-until712024subtractions-from-federal-adjusted-gross-income-state-adjustments):

https://github.com/PolicyEngine/policyengine-us/blob/7247fa73b727dfffc50c6df6025ddaf548c1ee8b/policyengine_us/variables/gov/states/md/tax/income/agi/subtractions/md_dependent_care_subtraction.py#L17-L26

That's the entire legal section for this subtraction; it does not mention $3,000 or $6,000.

Your logic in #1648 applies numbers from the tax form, but those are only provided to reproduce the relevant IRC section using federal tax forms.

**Comment by martinholmer** [comment]
@MaxGhenis said in issue #1647:
 > That's the entire legal section for this subtraction; it does not mention $3,000 or $6,000.
>
> Your logic in https://github.com/PolicyEngine/policyengine-us/pull/1648 applies numbers from the tax form, but those are only provided to reproduce the relevant IRC section using federal tax forms.

That is not true for 2021.  The maximum expenses per dependent in 2021 were $8000, not $3000, for the federal income tax.  Here is the US parameter file:

<img width="1344" alt="Screenshot 2023-01-04 at 11 07 13 PM" src="https://user-images.githubusercontent.com/12170745/210700328-88adfbdc-6fb2-4191-a3e2-b40cb7797886.png">


It seems to me that the evidence points to a decoupling of the 2021 MD care expense subtraction and the federal rules.   This is also what happened in a number of states that decoupled their EITC from the federal COVID-era EITC expansions.

If you think otherwise, how do you explain a large difference between what the 2021 form says and the legislation that you've been able to find?   Is it possible there was some kind of temporary MD decoupling legislation that applied only to 2021?  Do you really think the MD department of revenue staff took it upon themselves to write a tax form that was illegal?

**Comment by MaxGhenis** [comment]
I forgot about the ARPA CDCC reform. The $3,000/$6,000 amounts aren't in the legal code, nor is decoupling language specific to ARPA or the child and dependent care subtraction. The closest I could find was a [description](https://aronsonllc.com/cares-act-triggers-marylands-automatic-decoupling/) of Maryland automatically decoupling from the IRC when a reform occurs in the same tax year and would affect the Maryland budget by at least $5 million. Those descriptions all pertained to the CARES Act, but ARPA apparently qualified as well.

I'll suggest how to model this according to the law in #1648.
