### ISSUE TITLE
Integrate pension income input variables

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#1676]
We currently have:
* `tax_exempt_public_pension_income`
* `taxable_pension_income`
* `tax_exempt_pension_income`
* `public_pension_income`
* `pension_income` (sum of `taxable_pension_income` and `tax_exempt_pension_income`)

Almost all calculations result from `taxable_pension_income` and `tax_exempt_pension_income`. Users entering either of the public pension income variables expect it to flow to other variables, but neither fully end up in the net income computation (they just affect some specific state tax variables).

I'd suggest we switch to a MECE 2x2 of pension income variables to fully capture the income source:
* `taxable_public_pension_income`
* `tax_exempt_public_pension_income`
* `taxable_private_pension_income`
* `tax_exempt_private_pension_income`

**Comment by martinholmer** [comment]
@MaxGhenis said:
> I'd suggest we switch to a MECE 2x2 of pension income variables to fully capture the income source:
>
> * `taxable_public_pension_income`
> * `tax_exempt_public_pension_income`
> * `taxable_private_pension_income`
> * `tax_exempt_private_pension_income`

OK.  If you did that, would there be a `pension_income` variable that would be the sum of all four?  Is that variable used to determine benefit eligibility?   It would not be of any use in federal or state income tax calculations.

Also, you forgot the `taxsim_pensions` variable, which is misused in many taxsim tests but no where else.   Can we just get rid of this obsolete variable?   You rightly point out that the pension variables need to be rationalized.  So, it seems as if removing the `taxsim_pensions` variable should be part of this rationalization.

What is your timeline on doing this?

**Comment by MaxGhenis** [comment]
Yes I think we should use a total `pension_income` for benefit computations.

I haven't started on this or placed it in a priority queue yet, but I'd appreciate anyone who wanted to step in and give it a go.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> Yes I think we should use a total `pension_income` for benefit computations.

The tax computations would need  a `taxable_pension_income` variable equal to the sum of the `taxable_private_pension_income` and `taxable_public_pension_income` variables, and a `tax_exempt_pension_income` variable equal to the sum of the `tax_exempt_private_pension_income` and `tax_exempt_public_pension_income` variables.

Then, the `pension_income` variable would be defined as the sum of the `taxable_pension_income`  and `tax_exempt_pension_income` variables.

Does that make sense?
