### ISSUE TITLE
NYC School Tax Credit Income

### ISSUE THREAD

**Issue by leogoldman** [PolicyEngine/policyengine-us#1729]
NYC School Tax Credit has its own definition of income. Already created variables/gov/local/ny/nyc/tax/income/credits/school/nyc_school_credit_income.py

"Income, for purposes of determining your New York City school tax credit, means your recomputed federal adjusted gross income from
Form IT-201, line 19a, minus distributions from an individual retirement account and an individual retirement annuity, from Form IT-201,
line 9, if they were included in your recomputed federal adjusted gross income."

https://www.tax.ny.gov/pdf/2022/printable-pdfs/inc/it201i-2022.pdf#page=26

**Comment by leogoldman** [comment]
Recomputed federal AGI is only different from federal AGI if you were required to report any adjustments due to Decoupling from the IRC.
If we choose to ignore this possibility for now, then I think School Tax Credit Income = Federal AGI
---
Line 19a: Recomputed federal adjusted gross income
Were you required to report any adjustments on Form IT-558, New York State Adjustments due to Decoupling from the
IRC? Note: This form is reserved for a limited group of taxpayers. For more information, see the instructions for Form IT-558.
• If No, enter the line 19 amount on line 19a.
• If Yes, complete the worksheet below.
Do not leave line 19a blank.

Link to IT-558: https://www.tax.ny.gov/pdf/current_forms/it/it558i.pdf

**Comment by MaxGhenis** [comment]
Sounds good, let's define `nyc_school_credit_income` as `adds = ["adjusted_gross_income"]` and leave your note as a comment.
