### ISSUE TITLE
Add legislative references to California CARE eligibility parameters

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#1790]
From the CA legal code: https://leginfo.legislature.ca.gov/faces/codes.xhtml

Some newer version of this: https://law.justia.com/codes/california/2011/puc/division-1/727-758/739.1/

**Comment by KathrynPanger** [comment]
Here is the most recent version of the law:
https://law.justia.com/codes/california/2021/code-puc/division-1/part-1/chapter-4/article-2/section-739-1/

Takeaways:
An individual qualifies if they make no more than twice the poverty line for a two-person household
A person is categorically eligible if they are already enrolled in another public assistance program with similar requirements, however no specific programs are mentioned
A person MAY lose eligibility for the CARE program if In a given month, they use at least 4X their baseline energy consumption (presumably in kilowatt hours, “baseline energy consumption” is never defined) AND their electric company decides to make them enroll in the Energy Savings Assistance Program (ESAP), which includes a residential energy assessment, and they do not consent to this assessment within 45 days of notice
A person will DEFINITELY lose eligibility if they use at least 6X their baseline in a given month, at which point they are required to consent to their energy assessment within 45 days of notice, and if they continue to exceed 6X their baseline consumption (for one additional month, presumably, but this is not explicitly stated). 

[I created a Google Doc and highlighted the important parts](https://docs.google.com/document/d/1HNgf45oqrGkQHVYtMu_DXk-YiCB--dmqar_qf-IqrWE/edit?usp=sharing)
