### ISSUE TITLE
Simplify MO pension and social security deduction variables

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1793]
The MO income tax code would be easier to understand and faster to execute if the following changes were made:

(1) Shorten variable names so they can be read on GitHub:
```
mo_pension_and_ss_or_ssd_deduction            -->  mo_pension_oasdi_ded.py
mo_pension_and_ss_or_ssd_deduction_section_?  -->  mo_pension_oasdi_ded_?.py
```
for `?` equal to `a`, `b`, and `c`.

(2) Define all four of these variables at the Tax_Unit level, which is how they appear on the MO income tax form.

**Comment by MaxGhenis** [comment]
Agree with this except I'd suggest keeping it as `deduction` rather than `ded`, for consistency with other deductions in policyengine-us.
