### ISSUE TITLE
Improve simultaneous-tax-equations calculation

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1827]
When a taxpayer itemizes on the federal form, the taxpayer's state income tax liability can be itemized (up to an TCJA limit).  Usually, this does not cause any computational problems because most states do not allow federal income taxes to be deductible on the state form.  However, at least one state, Missouri (MO), does allow the deduction on the state form of a fraction of federal income tax liability.  This causes the federal income tax function and the state income tax function to be simultaneous, where the federal and state income tax liability amounts must be jointly determined to solve both equations simultaneously.  If you're not familiar with this mathematical problem and how it is solved, I suggest you read [Numerical Recipes](http://numerical.recipes/), Chapter 9: Root Finding and Nonlinear Sets of Equations, beginning with section 9.6.

Before continuing, let me make it clear there is room for improvement in handling this situation in both PolicyEngineUS and in TAXSIM35.  Neither model handles the MO situation in a fully correct manner.

In this issue, I present a very simple Python script that illustrates the MO problem and illustrates an iterative solution algorithm that is probably computationally inefficient, but is definitely easier to understand and implement than the general solution methods discussed in [Numerical Recipes](http://numerical.recipes/).

After presenting the script, I show two solutions that differ in the value assumed for the state income tax liability at the start of the itemizing iterations.   And finally, I use those two sets of results to discuss how the MO problem could be better handled in PolicyEngineUS.

First, the simple Python script:
```
"""
Simple one-person example of simultaneous federal/state tax equations.
"""

import sys


# specify root-finding parameters:
MAX_ITERS = 99
CONVERGENCE_TOL = 0.001  # one-tenth of one cent
ZERO_START_S = True


# specify individual attributes:
AGI = 100_000


def ftax(z, s):
    """
    Federal tax function:
    input:  z, whether or not taxpayer is itemizing on federal form
            s, state income tax amount
    output: federal income tax amount
    """
    ded = 2_000  # standard deduction
    if z:
        cap = 5_000
        ded = min(cap, s)
    taxinc = max(0, AGI - ded)
    return 0.25 * taxinc


def stax(z, f):
    """
    State tax function:
    input:  z, whether or not taxpayer is itemizing on federal form
            f, federal income tax amount
    output: state income tax amount
    """
    ded = 0.20 * f  # deduction of share of federal tax is available to all
    taxinc = max(0, AGI - ded)
    return 0.05 * taxinc


def main():
    """
    High-level script logic
    """
    # assume taxpayer is not itemizing on federal return
    z = 0
    s = 0
    f = ftax(z, s)
    s = stax(z, f)
    print("Not-Itemizing results:")
    print(f"i,z,f,s: 0 {z}  {f:.4f}  {s:.4f}")
    # assume taxpayer is itemizing on federal return
    z = 1
    if ZERO_START_S:
        s = 0
    else:
        pass  # use the s value computed under the not-itemizing assumption
    print(f"Itemizing results with iterations starting at s = {s:.4f}")
    prior_t = f + s
    for i in range(1, MAX_ITERS+1):
        f = ftax(z, s)
        s = stax(z, f)
        print(f"i,z,f,s: {i} {z}  {f:.4f}  {s:.4f}")
        t = f + s
        if abs(t - prior_t) < CONVERGENCE_TOL:
            break  # out of loop
        prior_t = t

    return 0
# end of main function code


if __name__ == '__main__':
    sys.exit(main())
```

Next, two sets of results from this script are shown: the first set is generated when the `ZERO_START_S` parameter is set to `True`, and the second set is generate when that parameter is set to `False`.
```
(policyengine-us) Policy-Engine-US% python fstax.py 
Not-Itemizing results:
i,z,f,s: 0 0  24500.0000  4755.0000
Itemizing results with iterations starting at s = 0.0000
i,z,f,s: 1 1  25000.0000  4750.0000
i,z,f,s: 2 1  23812.5000  4761.8750
i,z,f,s: 3 1  23809.5312  4761.9047
i,z,f,s: 4 1  23809.5238  4761.9048
i,z,f,s: 5 1  23809.5238  4761.9048

(policyengine-us) Policy-Engine-US% python fstax.py
Not-Itemizing results:
i,z,f,s: 0 0  24500.0000  4755.0000
Itemizing results with iterations starting at s = 4755.0000
i,z,f,s: 1 1  23811.2500  4761.8875
i,z,f,s: 2 1  23809.5281  4761.9047
i,z,f,s: 3 1  23809.5238  4761.9048
i,z,f,s: 4 1  23809.5238  4761.9048
```

The first thing to be said is that even if an iterative solution to the MO problem were never implemented in PolicyEngineUS (that is, if `MAX_ITERS` was set to one), there would be an enormous improvement in the one-itemizing-iteration approximation of the true solution if the starting value of the state income tax liability was taken to being the value of the state income tax liability under the not-itemizing calculation.  I'm not familiar with the not-itemizing and itemizing branching logic, but it would be highly desirable to break the circular logic in PolicyEngineUS by setting `state_income_tax` to the not-itemizing value instead of setting it to zero.   If that can be done, it would be seem to be straightforward to conduct a benefit-cost analysis of letting the itemizing iterations continue until convergence at the exactly correct values of federal and state income tax liability.

**Comment by MaxGhenis** [comment]
Modeling Missouri's state income tax withholding system (#1410) seems more tractable and accurate than iterative logic.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> Modeling Missouri's state income tax withholding system (https://github.com/PolicyEngine/policyengine-us/issues/1410) seems more tractable and accurate than iterative logic.

But will the "withholding logic" produce the correct federal and state income tax liabilities?

**Comment by MaxGhenis** [comment]
Yes, it should, given the law provides a deduction for SALT paid (not SALT liabilities), and the MO deduction is for federal tax liabilities. From what we can tell, software like TurboTax applies the SALT deduction to taxes paid, which withholding will more closely resemble.

[MO requires income tax withholding](https://dor.mo.gov/forms/Withholding%20Formula_2022.pdf) based only on rates, the standard deduction, filing status, and whether the spouse works; the federal income tax deduction is not a factor.

**Comment by martinholmer** [comment]
Issue #1827 is being closed because it has been resolved by the implementation of the PolicyEngine-US testing methods described in discussion topic #2389.
