### ISSUE TITLE
Reference for 2021 CA EITC parameters

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1864]
Pull request #1850 implemented logic for the CalEITC refundable credit for 2022, but did not supply 2021 parameter values.   When I look at the two references given, I cannot find the 2022 parameter values.   So, for example, when looking for the 2022 value of $8,954 for the phase-in amount for two or more eligible children mentioned in [`earned_income_amount.yaml`](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/parameters/gov/states/ca/tax/income/credits/earned_income/earned_income_amount.yaml), I cannot find that amount in either reference.

How would somebody go about specifying 2021 parameter values for the CA EITC?

**Comment by MaxGhenis** [comment]
Here's the 2022 reference: https://www.ftb.ca.gov/forms/2022/2022-3514-instructions.html

>If you have:
No qualifying children, is the amount on line 3 less than $4,248?
1 qualifying child, is the amount on line 3 less than $6,379?
2 or more qualifying children, is the amount on line 3 less than $8,954?

The [Form Search tool](https://www.ftb.ca.gov/forms/Search/Home/Results) pointed to the [2021 form](https://www.ftb.ca.gov/forms/2021/2021-3514-instructions.html) (also guessable from the URL), which provides the parameters:
>No qualifying children, is the amount on line 3 less than $3,922?
1 qualifying child, is the amount on line 3 less than $5,890?
2 or more qualifying children, is the amount on line 3 less than $8,268?

**Comment by martinholmer** [comment]
@MaxGhenis, Thanks for the hint.
