### ISSUE TITLE
SSI Not Including Both Incomes for Married and Both Eligible

### ISSUE THREAD

**Issue by CalebPena** [PolicyEngine/policyengine-us#1900]
When 2 people are married and both eligible for SSI, only one of their incomes is used when calculating SSI amount. It should calculate both of their countable incomes and then subtract those from the married grant standard.

Example: https://colab.research.google.com/drive/1nayyALu9Y9A-By1Aq-1CTuym1__qazbn#scrollTo=YDeKreCARbZq

**Comment by CalebPena** [comment]
@MaxGhenis Can we fix this bug. Here is another example.
https://colab.research.google.com/drive/1ly5EF-u6rncOdN3ol19Wb_xWydNwiqJh?usp=sharing

**Comment by MaxGhenis** [comment]
We only deem income from ineligible spouses or parents. This looks like it aligns with the [legal code](https://www.law.cornell.edu/cfr/text/20/part-416/subpart-K) which only has subsections on those types of deeming. Could you point to a section of the law that states otherwise?

**Comment by MaxGhenis** [comment]
My mistake, deeming doesn't apply here because they're a joint SSI filing unit (`marital_unit`). I'm not following the test though, looks like you're intercepting some intermediate variables. Can you provide a MRE providing leaf-node variables only, with the expected and actual result?

**Comment by CalebPena** [comment]
I updated the colab to be more minimal, as well as provide some better explanations.
https://colab.research.google.com/drive/1ly5EF-u6rncOdN3ol19Wb_xWydNwiqJh#scrollTo=x8Qkf48t4v0g

**Comment by MaxGhenis** [comment]
Thanks, this is clear. I'm not sure we have resources to fix this in the short term, but if you or anyone else is interested, I think it would involve the `ssi_countable_income` formula. The code is complex though. @nikhilwoodruff do you see a quick solution?
