### ISSUE TITLE
Are CA AGI additions and subtractions handled correctly?

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-us#1910]
In [this line](https://github.com/PolicyEngine/policyengine-us/blob/6d75f7505103c78a82fbd3e77c80ae5c0bdb0761/policyengine_us/variables/gov/states/ca/tax/income/ca_agi.py#L20) of `ca_agi`, we currently apply the zero-cap after the subtractions but before additions. Is this definitely correct? The referenced tax form didn't seem to clearly support that when I read it. @martinholmer LMK if I've missed something though - thanks.

**Comment by martinholmer** [comment]
@nikhilwoodruff asked:
> In [this line](https://github.com/PolicyEngine/policyengine-us/blob/6d75f7505103c78a82fbd3e77c80ae5c0bdb0761/policyengine_us/variables/gov/states/ca/tax/income/ca_agi.py#L20) of `ca_agi`, we currently apply the zero-cap after the subtractions but before additions. Is this definitely correct?

Here is the relevant screenshot of the 2021 CA Form 540:

<img width="1176" alt="Screenshot 2023-03-11 at 6 51 18 PM" src="https://user-images.githubusercontent.com/12170745/224516790-c58aad00-6598-4633-9a18-52cf3e3cc234.png">

Thanks for catching this bug.  The post-subtraction amount can be negative.
I'll open a pull request to fix this bug.

**Comment by nikhilwoodruff** [comment]
Thanks Martin!
