### ISSUE TITLE
NJ Main Income Tax

### ISSUE THREAD

**Issue by leogoldman** [PolicyEngine/policyengine-us#1932]
"Line 43 – Tax on Amount on Line 42
If the income on line 42 is less than $100,000, use the Tax
Table on page 52. Otherwise, calculate the tax by using the Tax
Rate Schedules on page 61. Use the correct column or schedule for your filing status. Enter the tax on line 43."

https://www.state.nj.us/treasury/taxation/pdf/current/1040i.pdf#page=32

Page 52 table: https://www.state.nj.us/treasury/taxation/pdf/current/1040i.pdf#page=54
Page 61 table: https://www.state.nj.us/treasury/taxation/pdf/current/1040i.pdf#page=63

Example PolicyEngine code from NY:
https://github.com/PolicyEngine/policyengine-us/blob/e234e6e2f8a72b80566d3ef0e62719c6472f7285/policyengine_us/variables/gov/states/ny/tax/income/ny_main_income_tax.py
https://github.com/PolicyEngine/policyengine-us/tree/master/policyengine_us/parameters/gov/states/ny/tax/income/main

**Comment by leogoldman** [comment]
Legal code: https://law.justia.com/codes/new-jersey/2022/title-54a/section-54a-2-1/

**Comment by AlexanderMies** [comment]
Let's do it
