### ISSUE TITLE
CHANGELOG is broken

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1946]
There have been two pull requests merged since 0.244.0 version, but neither of them show up in the CHANGELOG.

**Comment by martinholmer** [comment]
A broken CHANGELOG means contributors cannot even submit pull requests without hassles.  See, for example, PR #1947.

**Comment by martinholmer** [comment]
So, how am I supposed to fix this conflict?

<img width="1191" alt="Screenshot 2023-03-17 at 4 34 17 PM" src="https://user-images.githubusercontent.com/12170745/226034810-696a98b5-6e3e-462c-9351-5f6f17a2336f.png">

Why wasn't the `changelog_entry.md` file empty on the master branch, the way it usually is?

**Comment by MaxGhenis** [comment]
Something is wrong with the action: https://github.com/PolicyEngine/policyengine-us/actions/runs/4448517974/jobs/7811432429

>Error: fatal: could not read Username for 'https://github.com/': terminal prompts disabled

**Comment by MaxGhenis** [comment]
Fixed now
