### ISSUE TITLE
What is survey_enhance and why is it missing?

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#2028]
When I upgrade to 0.260.0 and execute `make test`, I get an error I have never seen before.
Here is (what seems to me the key) part of the error message:
```
  File "/Users/mrh/work/policyengine-us/policyengine_us/data/datasets/cps/calibrated_cps/calibrated_cps.py", line 2, in <module>
    from survey_enhance.reweight import CalibratedWeights
ModuleNotFoundError: No module named 'survey_enhance'
```

**Comment by nikhilwoodruff** [comment]
It's a package we'll be using the calibrate the CPS with administrative data- sorry, it should be a) a dev dependency and b) only imported within the function that generates the calibrated CPS dataset. The main reason we don't want it as a default dependency is because it depends on `pytorch` which is huge.

**Comment by martinholmer** [comment]
@nikhilwoodruff said:
> It's a package we'll be using [to] calibrate the CPS with administrative data- sorry, it should be a) a dev dependency and b) only imported within the function that generates the calibrated CPS dataset. The main reason we don't want it as a default dependency is because it depends on `pytorch` which is huge.

Thanks for the background, but what needs to done to fix this?   Seems like at the moment, nobody can do any development work.   In other words, the project has been stopped dead in its tracks.

**Comment by martinholmer** [comment]
@nikhilwoodruff said:
> `survey_enhace` [is a package] only imported within the function that generates the calibrated CPS dataset. 

How about dropping these CPS creation tests from the `make test` that everybody has to run when developing income tax or benefit code?   Running those tests has nothing to do with checking the validity of the new tax/benefit code and they take a long time to run.  I'm not really interested in installing a large `pytorch` package on my computer just so I can contribute tax code to the project.
