### ISSUE TITLE
Maine AGI Subtractions

### ISSUE THREAD

**Issue by leogoldman** [PolicyEngine/policyengine-us#2074]
Take a look at the NY example below. I think the main ones we can definitely capture are social security, government/bond interest, and pension income.

NY example: https://github.com/PolicyEngine/policyengine-us/blob/e234e6e2f8a72b80566d3ef0e62719c6472f7285/policyengine_us/variables/gov/states/ny/tax/income/adjusted_gross_income/ny_agi_subtractions.py
Subtractions worksheet: https://www.maine.gov/revenue/sites/maine.gov.revenue/files/inline-files/22_1040me_sched_1s_ff.pdf
Legal Code: https://www.mainelegislature.org/legis/statutes/36/title36sec5122.html

**Comment by mzx-4real** [comment]
Working on the issue:)
