### ISSUE TITLE
NJ Property Tax Deduction/Credit

### ISSUE THREAD

**Issue by leogoldman** [PolicyEngine/policyengine-us#2095]
Applicable for homeowners and tenants.
For homeowners, amount in question is property taxes paid. For tenants, amount in question is 18% of rent.
Is a deduction or a credit depending on which would help you more. The credit is $50, but at an effective tax rate around 5%, the deduction is better once you've paid above $1k in property taxes.

Tax Form: https://www.state.nj.us/treasury/taxation/pdf/current/1040i.pdf#page=26
Some extra info on NJ website: https://www.state.nj.us/treasury/taxation/njit35.shtml
Legal code: https://law.justia.com/codes/new-jersey/2022/title-54a/section-54a-3a-17/

**Comment by leogoldman** [comment]
@MaxGhenis couple questions on structure here. 
The main one: I don't want to get trigger-happy on modifying simulations, but is there a better way to access whether a deduction or a credit would be more helpful to an individual before their taxable income is calculated (which would depend on the total deductions)?
Second, do you think it would be best to format this on PolicyEngine as 1, 2, or 3 variables? I'm thinking ideally (for the tree structure) it would be two variables and at least one will always evaluate to $0 but not sure how to do that if they can't reference each other.

**Comment by MaxGhenis** [comment]
I'd suggest doing the branching similar to how the federal itemized vs standard deduction works. If we can identify an efficiency-enhancing heuristic later on we can always switch.
