### ISSUE TITLE
MS aged exemption

### ISSUE THREAD

**Issue by ZiqianCui** [PolicyEngine/policyengine-us#2229]
Blindness taxpayer additional exemption of $1,500.

"In the case of any taxpayer or the spouse of the taxpayer who is blind at the close of the taxable year, an additional exemption of One Thousand Five Hundred Dollars ($1,500.00). For the purpose of this subsection, an individual is blind only if his central visual acuity does not exceed 20/200 in the better eye with correcting lenses, or if his visual acuity is greater than 20/200 but is accompanied by a limitation in the fields of vision such that the widest diameter of the visual field subtends an angle no greater than twenty (20) degrees."

Miss. Code Ann. § 27-7-21 (g)
https://advance.lexis.com/documentpage/?pdmfid=1000516&crid=adb5f365-0449-4d49-80f0-22673c0d0165&nodeid=AAPAAFAABAAP&nodepath=%2fROOT%2fAAP%2fAAPAAF%2fAAPAAFAAB%2fAAPAAFAABAAP&level=4&haschildren=&populated=false&title=%C2%A7+27-7-21.+Exemptions+allowed.&config=00JABhZDIzMTViZS04NjcxLTQ1MDItOTllOS03MDg0ZTQxYzU4ZTQKAFBvZENhdGFsb2f8inKxYiqNVSihJeNKRlUp&pddocfullpath=%2fshared%2fdocument%2fstatutes-legislation%2furn%3acontentItem%3a8V3T-78H2-D6RV-H4WK-00008-00&ecomp=8gf5kkk&prid=e1d2bafd-2018-44e8-a4fc-e9e2b08a4daa

**Comment by MaxGhenis** [comment]
If this has been implemented (closed), could you please link the PR?

Also is this issue for an aged exemption or blind exemption?

**Comment by ZiqianCui** [comment]
I am not sure how to delete an issue, so I closed this one.

**Comment by ZiqianCui** [comment]
Duplicate of #2192
