### ISSUE TITLE
Georgia Standard Deduction 2022

### ISSUE THREAD

**Issue by GeneJung** [PolicyEngine/policyengine-us#2245]
**Standard deduction**
Single/Head of Household/Qualifying
Surviving Spouse..................$5,400
Married Filing Separate................... $3,550
Married Filing Joint.......................... $7,100
Additional Deduction....................... $1,300
Note: The additional deduction applies if you and/or your spouse are age 65 or over and/or blind.

(Reference: 2022 Georgia Tax Booklet, https://dor.georgia.gov/georgia-standard-deductions-increases)
(Legal reference: Georgia Code Title 48, Chapter 7, Article 2, Section 48-7-27
href: https://public.fastcase.com/9SKwsfNqTc6OieYDhNMyMyXMWX5bJPJbhkG3Ui6%2F6PjqLFqBSlnw9j5kMO4qrILO9GiBgvgtbuIau7KPlSNvcA%3D%3D )

**Comment by martinholmer** [comment]
Resolved by merge of pull request #2316.
