### ISSUE TITLE
Michigan Home Heating Credit 

### ISSUE THREAD

**Issue by keepjojoyoung** [PolicyEngine/policyengine-us#2312]
Michigan Home Heating Credit Information Page
https://www.michigan.gov/taxes/questions/iit/accordion/heating/home-heating-credit-information-1
Tax Form
https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/2022/2022-IIT-Forms/MI-1040CR7.pdf?rev=c36e54deae424566bb6abd1cbe8af7cb&hash=B39BA9887DD31395E754CC0641EFB512
Instruction
https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/2022/2022-IIT-Forms/BOOK_MI-1040CR-7.pdf?rev=d765b421bc7343c0a54793499dc550db&hash=0B10BE7DD0B91D7F609230E8F636EBC8

**Comment by MaxGhenis** [comment]
Could you add more information on this? Please try to include a source when filing a new issue.

**Comment by keepjojoyoung** [comment]
> Could you add more information on this? Please try to include a source when filing a new issue.

Sure! Thanks for the reminder, I just started working on this issue and will add more information to complete the issue description.
