### ISSUE TITLE
Add missing NJ pension exclusion logic

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#2367]
The NJ state income tax excludes social security benefits from NJ AGI (as fixed in pull request #2361) and also excludes taxable pension income in most cases (see the [instructions](https://www.state.nj.us/treasury/taxation/pdf/current/1040i.pdf#page=21) for Line 28a and Line 28b).

On the NJ-1040 tax form, the sum of Line 28a and Line 28b is placed on Line 28c and Line 28c is subtracted from Line 27 to get Line 29, **New Jersey Gross Income**, which is called `nj_agi` in the code.

The current version of the code does not include pension exclusion variables, and those variables are not in the list of variables added to get the value of the `nj_agi_subtractions` variable.

The person who fixes this issue should, at a minimum, add to their pull request the corrected versions of the following two integration tests.

```
- name: NJ taxpayer with taxable pension income
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: true
        age: 62
        taxable_interest_income: 6_000
        taxable_pension_income: 12_000
    spm_units:
      spm_unit:
        members: [person1]
    tax_units:
      tax_unit:
        members: [person1]
    households:
      household:
        members: [person1]
        state_code: NJ
  output:
    adjusted_gross_income: 18_000  # on federal form
    nj_agi: 18_000  # because pension subtraction from federal AGI is missing
    # CORRECT nj_agi OUTPUT IS:
    # 6_000 because all pension income is excluded from NJ AGI in this case

- name: NJ taxpayer with no taxable pension income
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: true
        age: 70
        taxable_interest_income: 7_000
    spm_units:
      spm_unit:
        members: [person1]
    tax_units:
      tax_unit:
        members: [person1]
    households:
      household:
        members: [person1]
        state_code: NJ
  output:
    adjusted_gross_income: 7_000  # on federal form
    nj_agi: 7_000  # because pension subtraction from federal AGI is missing
    # CORRECT nj_agi OUTPUT IS:
    # 4_000 because eligible for Other Retirement Income Exclusion, namely
    #   the Special Exclusion of $3000 for singles who will never get social
    #   security benefits
    # Note: we can infer this is the case for those age 70+ who have no
    #       social security benefits because beyond age 70 there are no
    #       more delayed retirement credits under social security.
```

@leogoldman, can you undertake the development work required to fix this issue?

**Comment by leogoldman** [comment]
@martinholmer Thanks for detailing this, assigning myself now!

**Comment by martinholmer** [comment]
@leogoldman said in issue #2367:
> Thanks for detailing this, assigning myself now!

Great!  Let me know if you have any questions when you wade into this.

**Comment by leogoldman** [comment]
@martinholmer Possible I'm misunderstanding the other retirement income exclusion (line 28b), but wouldn't someone age 70 with $7k in taxable income as their total income (your second test inputs) be eligible to have all of this income excluded even before the special exclusion?

**Comment by martinholmer** [comment]
@leogoldman said is issue #2367:
> Possible I'm misunderstanding the other retirement income exclusion (line 28b), but wouldn't someone age 70 with $7k in taxable income as their total income (your second test inputs) be eligible to have all of this income excluded even before the special exclusion?

Perhaps.  Can you explain exactly why you think that?  
Remember I know virtually nothing about the NJ state income tax, so you would need to spell it out for me.

**Comment by leogoldman** [comment]
@martinholmer No problem, as I understand it:

Line 27 = Total income minus tax exempt interest income and tax exempt pension income
line 20a = taxable pension income
Line 28a ("Pension/Retirement Exclusion") = amount of line 20a that can be excluded
Line 28b ("Other Retirement Income Exclusion") = Amount of line 27 you can exclude if 62 or older, plus special exclusion if eligible.

What seems strange to me is that based on Worksheet D (which helps you calculate line 28b, see screenshot below) is that it seems like if you are 62+ you can exclude a large portion of your income, unrelated to line 28a. If everything in Worksheet D is accurate and I'm understanding it correctly, then someone aged 70 with $7k in taxable interest income would fill out Worksheet D as follows:
1. Line 27 = $7k which is less than $150k so continue and max exclusion = $50k, $75k, or $100k dep. on filing status
2. Line 20a = $0
3. Worksheet Line 1 minus Worksheet Line 2 min(Worksheet Line 1, $7k)=$7k > $0 so continue.
4. Wages = $0
5. Business profits = $0
6. Partnership income = $0
7. Corporation income = $0
8. Worksheet lines 4 through 7 sum to < $3k so continue.
9. Enter Worksheet Line 3 = $7k
This individual could then exclude their $7k income.

They would also be eligible for the special exclusion under your assumption of being 70 with no SS, so before bottoming the NJ AGI at $0 (which is a separate question), their NJ AGI would be -$3k.

Let me know if that makes sense or if you see what I'm misunderstanding!

Worksheet D link: https://www.state.nj.us/treasury/taxation/pdf/current/1040i.pdf#page=22
<img width="595" alt="Screen Shot 2023-06-15 at 10 34 34 AM" src="https://github.com/PolicyEngine/policyengine-us/assets/33919642/2dc60328-8bb1-4005-91ff-8438a34093ae">

**Comment by martinholmer** [comment]
@leogoldman, Thanks for the detailed explanation.  I agree that the instructions are confusing.  

My understanding (from the form and the text in the instructions) now is that Line 28b is composed of two parts:  (1) an amount related to the unclaimed 28a amount (because taxable pension income was small or was limited in the Line 28a calculation), and (2) the "special exclusion" for those without any social security eligibility.

Looking back on my original comment in this issue, I guess I overlooked the (1) part of Line 28b.  

So, I guess the way to correct my mistake is to add a new third test that is constructed in such a way as to test the (2) part of Line 28b (the "special exclusion").  You are right to point out that my second test doesn't do that (because I overlooked the existence of Worksheet D).

However, I am confused about the exact nature of Worksheet D.   The instructions say this:

<img width="690" alt="Screenshot 2023-06-15 at 2 50 39 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/cfde1272-6e26-419b-980d-75cf6f7bba75">

What exactly is the "unclaimed portion" of Line 28a?   Seem like you need taxable pension income to have an "unclaimed portion" (or at least that's my perhaps inaccurate reading).  But you are correct in pointing out that Worksheet D makes no mention of taxable pension income.

**Comment by martinholmer** [comment]
@leogoldman, Is PR #2367 ready for review?
If so, please request a review from @MaxGhenis.
Thanks.
