### ISSUE TITLE
Vermont Taxable Income

### ISSUE THREAD

**Issue by mzx-4real** [PolicyEngine/policyengine-us#2399]
# References
Tax Form: https://tax.vermont.gov/sites/tax/files/documents/IN-111-2022.pdf
Instruction: https://tax.vermont.gov/sites/tax/files/documents/Income%20Booklet-2022.pdf
# Example
Maine Taxable Income: https://github.com/PolicyEngine/policyengine-us/pull/2020
# Variable to add:
`vt_taxable_income` `vt_deductions` `vt_exemptions`

Vermont Taxable income equals to Vermont AGI minus deductions and exemptions
# Summary
Complete `vt_taxable_income` computation frame
Refine `vt_deductions` and `vt_exemptions` in future issues.

**Comment by jongwonIee** [comment]
I would like to contribute
