### ISSUE TITLE
Model state-by-state SNAP rules

### ISSUE THREAD

**Issue by nmrodelo** [PolicyEngine/policyengine-us#24]
SNAP:
https://www.ers.usda.gov/data-products/snap-policy-data-sets/

**Comment by MaxGhenis** [comment]
Thanks @nmrodelo, in particular the `bbce*` and `vehexcl*` variables there will help us model state-by-state SNAP rules.

**Comment by nmrodelo** [comment]
Eligibility cutoffs for all 50 states:
https://www.benefits.gov/categories/Food%20and%20Nutrition
