### ISSUE TITLE
MS Individual Itemized Deductions

### ISSUE THREAD

**Issue by ZiqianCui** [PolicyEngine/policyengine-us#2472]
(i) The deduction for state income taxes paid or other taxes allowed for federal purposes in lieu of state income taxes paid;
(ii) The deduction for gaming losses from gaming establishments;
(iii) The deduction for taxes collected by licensed gaming establishments pursuant to Section 27-7-901;
(iv) The deduction for taxes collected by gaming establishments pursuant to Section 27-7-903.

reference: https://advance.lexis.com/documentpage/teaserdocument/?pdmfid=1000516&crid=10f9847f-839a-482c-b6b3-3ffa6993b9f5&config=00JABhZDIzMTViZS04NjcxLTQ1MDItOTllOS03MDg0ZTQxYzU4ZTQKAFBvZENhdGFsb2f8inKxYiqNVSihJeNKRlUp&pddocfullpath=%2Fshared%2Fdocument%2Fstatutes-legislation%2Furn%3AcontentItem%3A659V-W3G3-CGX8-0009-00008-00&pddocid=urn%3AcontentItem%3A659V-W3G3-CGX8-0009-00008-00&pdcontentcomponentid=234190&pdteaserkey=h3&pditab=allpods&ecomp=7s65kkk&earg=sr0&prid=72e99828-14ce-44a2-88ad-6955d7005598 3(a)(i-iv)

**Comment by MaxGhenis** [comment]
These are all low priority

**Comment by ZiqianCui** [comment]
Got it Max!

**Comment by ZiqianCui** [comment]
merged with issue #2528
