### ISSUE TITLE
grocery credit refund Idaho

### ISSUE THREAD

**Issue by GeneJung** [PolicyEngine/policyengine-us#2574]
Reference: https://tax.idaho.gov/pressrelease/claim-your-grocery-credit-refund-even-if-you-dont-earn-enough-to-file-income-taxes-2/#:~:text=BOISE%2C%20Idaho%20%E2%80%94%20March%207%2C,65%20or%20older%20get%20%24120.

**Comment by MaxGhenis** [comment]
Duplicate of #1161
