### ISSUE TITLE
Bugs in Maine income tax calculations

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#2607]
As of the 0.359.1 version, the Maine income tax code has several problems.

First, there is a bug in the calculation of the standard deduction: it is supposed to be the same as the federal standard deduction, but the elderly and blind bonus deductions have not been included in the Maine code.

Second, I was asked to include Maine in the #993 test suite.  But when I did that I found that there are no 2021 tax parameter values, which is the year for which the #993 testing is done.   Apparently there needs to be a better effort made by senior project staff to inform volunteers that state tax parameters should go back at least to 2021.

As a result of these two problems, the Maine income tax generated by PolicyEngine-US differs from that generated by TAXSIM35 in **every one** of the 100,000 test cases in the simple `p21` sample.

I'll be happy to run the Maine tests again after these problems are fixed.

cc: @MaxGhenis  @nikhilwoodruff  @PavelMakarchuk

**Comment by MaxGhenis** [comment]
Thanks Martin, I've filed issues for each of these, as referenced in this issue. Pavel now provides guidance to volunteers to add 2021 rules to all states for taxsim validation, but I never mentioned it to @leogoldman who worked on Maine; my mistake there.

**Comment by PavelMakarchuk** [comment]
That was my mistake, I will make sure it does not slip through my
review again.
Thank you for catching that.

Best,
Pavel

**Comment by martinholmer** [comment]
Apparently this issue is no longer relevant because several pull requests did not link to this issue.
