### ISSUE TITLE
Avoid circular reference in NM itemized deductions

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#2646]
In #2616, @Linfeng-ll implemented NM itemized deductions, and references SALT, because the formula is based on state income taxes as a fraction of capped SALT. @PavelMakarchuk and I couldn't immediately identify an implementation that avoids a circular reference, short of modeling withholding rules.

**Comment by martinholmer** [comment]
Issue #2646 has been resolved by commenting-out the `nm_income_tax` variable in the list that is in the`state_income_tax.py` module.  This is the same treatment as given other states whose income tax rules create circular logic errors in the PolicyEngine-Core framework.  As described in issue #993, the correct state income tax amounts for these states can be calculated using a looping technique.
