### ISSUE TITLE
Add Maine STFC and PTFC refundable credits

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#2662]
Maine provides a Sales Tax Fairness Credit (STFC) and a Property Tax Fairness Credit (PTFC) that are both refundable.  The calculation of these two credits are done on a [separate 2021 form](https://www.maine.gov/revenue/sites/maine.gov.revenue/files/inline-files/21_1040me_sched_pstfc_dwnldff.pdf) and then transferred to the 1040ME form.
There is also a [2022 form](https://www.maine.gov/revenue/sites/maine.gov.revenue/files/inline-files/22_1040me_sched_pstfc_ff.pdf) for the STFC and PTFC.

But neither of these two credits have been added to the Maine state income tax code.

**Comment by martinholmer** [comment]
@leogoldman,  Your recent changes to the Maine income tax code have been great.  Thanks.   Will you be able to add the missing credits described in issue #2662?  If so, it looks as if we will start to get agreement between PolicyEngine-US and TAXSIM35 as described in issue #993.

**Comment by leogoldman** [comment]
@martinholmer Thanks for pointing these out. I spoke with @PavelMakarchuk in case he has someone that can get to it sooner, but if not I'm happy to take care of it just a bit busy this following week

**Comment by PavelMakarchuk** [comment]
@martinholmer more than happy to look over those as soon as NM is done. I will bring in a volunteer for it. Thank you @leogoldman

**Comment by martinholmer** [comment]
@PavelMakarchuk,  Why did you close PR #2691?
You have still assigned yourself to resolve issue #2662.
Are you going to assign this to someone else?

**Comment by PavelMakarchuk** [comment]
I had some issues with the PR -> I have reopened it under #2888
https://github.com/PolicyEngine/policyengine-us/pull/2888
