### ISSUE TITLE
Missing state income tax variable that includes all states

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-us#2697]
The PolicyEngine web app uses `state_income_tax` to determine revenue impacts from the state and federal levels. But `state_income_tax` excludes a selection of states which cause circular dependencies when included. I propose adding a new `household_state_income_tax` variable not involved in the net income tree that includes all modelled states, specifically to fix this chart issue.

**Comment by martinholmer** [comment]
This issue #2697 was posted after pull request #2696 was already merged into the master branch, and therefore, the issue did not close (because the PR had already been merged).
