### ISSUE TITLE
Confusing New Mexico variable and parameter name

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#2767]
It is good that merged PR #27553 fixed the subtraction errors, but the new parameter and variable name is massively confusing.  

The new parameter file is named:
```
other_deductions_and_exemptions.yaml
```
 even though its description is this:
```
description: New Mexico other deduction and subtraction elements.
```
And the label is misnamed just like the file itself.

There are no exemptions in this list, only subtractions.   Please rename the file and change the label to be like the description.

And the same for the new variable which is misnamed as:
```
nm_other_deductions_and_exemptions.py
```
which contradicts its (correct) label:
```
 label = "New Mexico other income deductions and subtractions"
```
Please rename this variable file.

**Comment by PavelMakarchuk** [comment]
I believe the [payments to educational funds ](https://nmonesource.com/nmos/nmsa/en/item/4340/index.do#!fragment/zoupio-_Toc141270056/BQCwhgziBcwMYgK4DsDWszIQewE4BUBTADwBdoAvbRABwEtsBaAfX2zgEYAWDgJgHYADIICsANgCUAGmTZShCAEVEhXAE9oAck1SIhMLgTLVG7bv2GQAZTykAQhoBKAUQAyzgGoBBAHIBhZylSMAAjaFJ2CQkgA) is specified as a deduction and the [armed forced salaries ](https://nmonesource.com/nmos/nmsa/en/item/4340/index.do#!fragment/zoupio-_Toc141269862/BQCwhgziBcwMYgK4DsDWszIQewE4BUBTADwBdoAvbRABwEtsBaAfX2zgEYAWDgJgDYAnAA5+vAJQAaZNlKEIARUSFcAT2gByDZIiEwuBEpXqtOvQZABlPKQBC6gEoBRADJOAagEEAcgGEnkqRgAEbQpOzi4kA) seem to be an exemption. The [tax form](https://klvg4oyd4j.execute-api.us-west-2.amazonaws.com/prod/PublicFiles/34821a9573ca43e7b06dfad20f5183fd/1afc56af-ea90-4d48-82e5-1f9aeb43255a/PITbook2022.pdf) classifies them as "deduction and exemptions" in PIT-ADJ -  I dont think new mexico uses the term subtractions at all

**Comment by martinholmer** [comment]
@PavelMakarchuk said:
> I dont think new mexico uses the term subtractions at all

OK.  Then eliminate the use of that term in the descriptions and labels.

**Comment by martinholmer** [comment]
Apparently there is little interest in making the NM labels and descriptions reflect the language used by the NM tax law and forms.
