### ISSUE TITLE
Connecticut Personal Exemptions

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-us#2799]
[Reference](https://www.cga.ct.gov/current/pub/chap_229.htm#sec_12-702)

**Comment by martinholmer** [comment]
@PavelMakarchuk,  Isn't issue #2799 already resolved in the CT income tax source code?

**Comment by PavelMakarchuk** [comment]
@martinholmer absolutely right -> closing the issue
