### ISSUE TITLE
Maryland 100 year subtraction

### ISSUE THREAD

**Issue by SirMalamute** [PolicyEngine/policyengine-us#2818]
References: 
https://www.marylandtaxes.gov/forms/22_forms/Resident_Booklet.pdf
https://mgaleg.maryland.gov/2023RS/fnotes/bil_0001/sb0461.pdf

**Comment by MaxGhenis** [comment]
Renaming to focus on the subtraction, as I think the senior tax credit is in https://github.com/PolicyEngine/policyengine-us/issues/1413

In general please target each issue to a single program
