### ISSUE TITLE
Turn on New Jersey income parameters

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#2846]
They're still hidden. Revealing them requires some other changes: 
1. Clearing other TAXSIM deviations
2. Updating for any 2023 reforms

In #2843 (now merged), @martinholmer said:
>there are no NJ tax differences for the 600,000 integration tests in the p21 sample and in the e21 through i21 samples described in issue https://github.com/PolicyEngine/policyengine-us/issues/993.

Yet #993 shows some remaining deviations on other samples, with as-yet-unknown causes.

We also have not yet modeled reforms introduced in 2023 legislation, such as the NJ CTC #2807.

**Comment by martinholmer** [comment]
Using the 2023-08-17 patch of TAXSIM35, there are no NJ tax differences between PolicyEngine-US and TAXSIM35 in 900,000 integration tests in the `p21` through `x21` sequence of samples described in issue #993.   Also, there are no differences in the 700,000 tests in the `e21` through `k21` sequence of samples.  So, taken together, there are no diffs in 1,600,000 different integration tests.

@leogoldman, thanks for all you work on the NJ module and especially in adding the complex pension/retirement income exclusions.

**Comment by MaxGhenis** [comment]
Ok great, then we just need to update the CTC and property tax credit https://www.nj.gov/treasury/taxation/newlegislation2023.shtml

**Comment by martinholmer** [comment]
@MaxGhenis said in issue #2846:
> Ok great, then we just need to update the CTC and property tax credit [for the 2023 reforms] https://www.nj.gov/treasury/taxation/newlegislation2023.shtml

What is the status of this work?   Can this issue be closed?

**Comment by MaxGhenis** [comment]
Yes, we've updated the CTC and verified that the property tax credit is out of scope vis-a-vis taxsim.
