### ISSUE TITLE
Begin integration testing of Connecticut income tax

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#2895]
Thanks to the work of @PavelMakarchuk, the Connecticut income tax module is close to being complete enough for testing to start.   Mainly need to add placeholder `ct_agi_additions` and `ct_agi_subtractions` variables.

**Comment by PavelMakarchuk** [comment]
@martinholmer thank you for that! We are looking to merge the EITC and property tax credit early next week as well
