### ISSUE TITLE
Missing Colorado state tax addback

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#2947]
The Colorado income tax forms/instructions for [2021](https://tax.colorado.gov/sites/tax/files/documents/DR_104_Book_2021.pdf) and [2022](https://tax.colorado.gov/sites/tax/files/documents/DR_104_Book_2022.pdf) start on Line 1 with federal taxable income.  Then on Line 2 there is a state income tax addback.   However, the 0.458.1 version has no variable to implement this addback.

**Comment by PavelMakarchuk** [comment]
@MaxGhenis are we able to add-back the state income tax as mentioned below? 

![image](https://github.com/PolicyEngine/policyengine-us/assets/110687043/47aa2121-27a2-4998-b013-942749e87d36)

**Comment by MaxGhenis** [comment]
Can we do this without a circular reference? I think we'd need to use a version of federal taxable income without the salt deduction.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> Can we do this without a circular reference? I think we'd need to use a version of federal taxable income without the salt deduction.

Better to do this like @MaxGhenis did MO, which means code the CO formula correctly using the `state_income_tax` variable.   There will be no circular-logic error when doing this because the `co_income_tax` has been for weeks commented out of the list in the `state_income_tax` module.

If coded in any other way it will be inaccurate, and therefore, the TAXSIM integration tests will **never** pass.

If you want, I'd be happy to provide a PR that results this issue.

**Comment by MaxGhenis** [comment]
>If you want, I'd be happy to provide a PR that results this issue.

That'd be great thank you @martinholmer
