### ISSUE TITLE
Ohio lump sum retirement credit

### ISSUE THREAD

**Issue by Linfeng-ll** [PolicyEngine/policyengine-us#2958]

**Comment by Linfeng-ll** [comment]
https://tax.ohio.gov/static/forms/ohio_individual/individual/2022/it1040-sd100-instruction-booklet.pdf#page=20

**Comment by MaxGhenis** [comment]
This was already filed in #1499 and code for it was added in #2388 (https://github.com/PolicyEngine/policyengine-us/tree/master/policyengine_us/variables/gov/states/oh/tax/income/credits/retirement_income)

Can you amend the issue title to describe what needs to be fixed? Same goes for #2990
