### ISSUE TITLE
Focus test coverage report on taxes and benefits

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#2972]
There is a strong commitment to test-driven development when adding new taxes or benefits to the model.  However, the current test coverage report is not well focused on taxes and benefits because it includes test results for dataset construction, tools, taxsim variables, and the `slspc` variable, which is part of the not-yet-implemented Premium Tax Credit.  This makes the test coverage report much less useful than it could be.  A coverage report focused on just taxes and benefits would be useful in guiding an effort to obtain 100% code coverage for taxes and benefits.

This effort would proceed in two phases: (1) focus the test coverage report on taxes and benefits, and (2) use that focused report to add the tests that are necessary to obtain 100% coverage of taxes and benefits.

**Comment by MaxGhenis** [comment]
I'd prefer we shoot for 100% code coverage including of non-policy sections like data.

**Comment by MaxGhenis** [comment]
@nikhilwoodruff and I chatted about this and agreed we can exclude non-policy sections from codecov for now.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> @nikhilwoodruff and I chatted about this and agreed we can exclude non-policy sections from codecov [reports] for now.

OK.  I think PR #2973 is inline with this approach.
