### ISSUE TITLE
Remove index.yaml for other states

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#2988]
@PavelMakarchuk correctly noted that the `index.yaml` parameter file for IN income tax should be removed because that state income tax testing in issue #993 has been completed successfully.

But this is also true of the following states that have income tax `index.yaml` files:
DC
MA (two index.yaml files deep in the parameter directory tree)
MO

**Comment by PavelMakarchuk** [comment]
> @PavelMakarchuk correctly noted that the `index.yaml` parameter file for IN income tax should be removed because that state income tax testing in issue #993 has been completed successfully.
> 
> But this is also true of the following states that have income tax `index.yaml` files: DC MA (two index.yaml files deep in the parameter directory tree) MO

Thank you for noticing, I can't seem to see the DC index - will fix in PR #2987
