### ISSUE TITLE
Hide Louisiana policy parameters

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#3044]
Doesn't look done. If it's not, add `index.yaml` to hide it. If it is done, add a `README.md` with the name instead.

<img width="953" alt="image" src="https://github.com/PolicyEngine/policyengine-us/assets/6076111/c927d8e7-ca09-4c69-b47d-1fb774b73e3d">

**Comment by PavelMakarchuk** [comment]
Irrelevant as we have enabled all state models
