### ISSUE TITLE
Vermont Property Tax Credit

### ISSUE THREAD

**Issue by jongwonIee** [PolicyEngine/policyengine-us#3049]
Reference
https://tax.vermont.gov/sites/tax/files/documents/Income%20Booklet-2022.pdf#page=30

**Comment by martinholmer** [comment]
If adding **VT property tax credit**, then should also add **VT renter credit**:
https://tax.vermont.gov/sites/tax/files/documents/Income%20Booklet-2022.pdf#page=27

**Comment by hua7450** [comment]
Can we change the name of this issue to Vermont Renter Credit? I will file an issue and PR for the Vermont Property Tax Credit.
