### ISSUE TITLE
master branch has non-empty changelog_entry.yaml file

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3060]
My understanding is that on the `master` branch the `changelog_entry.yaml` file should be empty.
But I after pushed a minor change to the `changelog_entry.yaml` file to the **pending** PR #3034,
the contents of the `changelog_entry.yaml` file are as seen in the screenshot below.

Is something broken in the CI code that handles the CHANGELOG?  Or did I do something wrong?

<img width="1356" alt="Screenshot 2023-09-21 at 8 37 10 AM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/0db540cf-ae2a-4422-95ac-d47057922353">

**Comment by nikhilwoodruff** [comment]
Oh thanks for raising Martin- I think yes there was a few hours of time where the versioning action didn't function (due to a GH secret expiration) and this might have been compounded. I'll take a look today.

**Comment by nikhilwoodruff** [comment]
Seems to be fixed now?

**Comment by martinholmer** [comment]
@nikhilwoodruff, Thanks for looking into issue #3060.
