### ISSUE TITLE
Apply prior year's federal poverty line for SNAP rules until October

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#3094]
We currently use the current year's federal poverty line for the full year when computing SNAP eligibility. However, [7 CFR 273.9(a)(3)](https://www.ecfr.gov/current/title-7/part-273#p-273.9(a)(3)) states:
>The income eligibility limits, as described in this paragraph, are revised each October 1 to reflect the annual adjustment to the Federal income poverty guidelines for the 48 States and the District of Columbia, for Alaska, and for Hawaii.

https://snapscreener.com also (as of today in Sep) still uses the 2022 FPG.

This will require a novel use of parameters and dates, @nikhilwoodruff could you suggest a structure?

Thanks @CalebPena for reporting this.

**Comment by nikhilwoodruff** [comment]
Make a SNAP FPG variable and use that
