### ISSUE TITLE
Update Colorado TABOR parameters 2023

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-us#3107]
https://github.com/PolicyEngine/policyengine-us/tree/master/policyengine_us/parameters/gov/states/co/tax/income/credits/sales_tax_refund/amount

https://tax.colorado.gov/cash-back

bill - https://leg.colorado.gov/sites/default/files/documents/2023A/bills/fn/2023a_hb1311_00.pdf

explainer - https://www.bellpolicy.org/2023/05/22/tabor-in-2023/

**Comment by Eleanor-Zhu** [comment]
already solved.
