### ISSUE TITLE
Add Georgia retirement income exclusion

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3128]
Need to add a formula for the `ga_retirement_exclusion` variable.

Also, need to move three variables that are misplaced in the `variables/gov/ga` directory tree.  The three variables listed below need to be moved down two levels in the tree so that they are in the variables/gov/ga/tax/income` directory.

<img width="1087" alt="Screenshot 2023-10-05 at 10 16 43 AM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/fbcab050-7c53-4a97-b18e-0cedf9869798">

**Comment by PavelMakarchuk** [comment]
Will be solved by PR #2468 

@DianaShi5083 - please see the variables that need to be moved in the Georgia structure as well

**Comment by martinholmer** [comment]
Duplicate of issue #2468.
