### ISSUE TITLE
Use prior year poverty line in tax_unit_medicaid_income_level formula

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3154]
The formula for the `tax_unit_medicaid_income_level` variable is incorrect in the 0.502.1 version of PolicyEngine-US.  The current version of the formula provides no documentation to support its logic, so I'm assuming that these problems are bugs.

The bigger of the two problems is that the ratio of MAGI (i.e., `medicaid_income`) to the FPL is defined using the **prior-year** FPL (not the **current-year** FPL).

See, for example, pages 7-8 in the [2022 IRS Form 8962 instructions](https://www.irs.gov/pub/irs-pdf/i8962.pdf) for a complete explanation.

**Comment by MaxGhenis** [comment]
Thanks @martinholmer, I split this out into this issue for the prior year's poverty line and #3157 to truncate the FPL level, as I want to understand the year of the poverty line better.

You pointed to the [2022 Form 8962 instructions](https://www.irs.gov/pub/irs-pdf/i8962.pdf#page=7), which uses the [2021 poverty line](https://aspe.hhs.gov/topics/poverty-economic-mobility/poverty-guidelines/prior-hhs-poverty-guidelines-federal-register-references), e.g. $12,880 for a one-person household in the contiguous US. It also says (without specifying the year):
>Applicable federal poverty line percentages. For tax year 2022, taxpayers with household income that exceeds 400% of the federal poverty line for their family size may be allowed a PTC.

Similarly, the [2021 Form 8962 instructions](https://www.irs.gov/pub/irs-prior/i8962--2021.pdf) use the 2020 poverty line.

[IRC §36B(d)(3)(B)](https://www.law.cornell.edu/uscode/text/26/36B#d_3_B) states:
>In the case of any [qualified health plan](https://www.law.cornell.edu/definitions/uscode.php?width=840&height=800&iframe=true&def_id=26-USC-522967831-528328467&term_occur=999&term_src=title:26:subtitle:A:chapter:1:subchapter:A:part:IV:subpart:C:section:36B) offered through an Exchange for coverage during a taxable year beginning in a calendar year, the[ poverty line ](https://www.law.cornell.edu/definitions/uscode.php?width=840&height=800&iframe=true&def_id=26-USC-281322219-528327506&term_occur=999&term_src=)used shall be the most recently published[ poverty line ](https://www.law.cornell.edu/definitions/uscode.php?width=840&height=800&iframe=true&def_id=26-USC-281322219-528327506&term_occur=999&term_src=)as of the 1st day of the regular enrollment period for coverage during such calendar year.

Do you know how these reconcile?

**Comment by martinholmer** [comment]
@MaxGhenis asked in issue #3154:
> Do you know how these reconcile?

Why do you think there is any conflict between IRS Form 8962 and the tax law?
Do you think IRS has broken the law in publishing Form 8962?

**Comment by MaxGhenis** [comment]
Unless I'm misreading it, I do think there's a discrepancy between the law and the form, so I wanted to record that for posterity. Maybe another part of the USC or CFR clarifies it. But I'll merge your PR to recognize the form as the more relevant source.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> I do think there's a discrepancy between the law and the form, so I wanted to record that for posterity.

I don't see a "discrepancy between the law and the form".   The law says to use the latest FPL when the ACA plans are first offered.   The 2023 ACA plans have been on offer for almost a year now.   Was the 2023 FPL available a year ago?   The IRS form seems to indicate not.   What is the publication schedule for the FPL?

Both the [Kaiser Family Foundation ACA calculator](https://www.kff.org/interactive/subsidy-calculator/) and the [CBPP](https://www.healthreformbeyondthebasics.org/reference-guide-yearly-thresholds) think there is a one-year lag.  Are they both wrong?

**Comment by MaxGhenis** [comment]
I didn't think they were wrong, I was just trying to reconcile the apparent gap so we understand it. This clears it up:

The law says:
>the[ poverty line ](https://www.law.cornell.edu/definitions/uscode.php?width=840&height=800&iframe=true&def_id=26-USC-281322219-528327506&term_occur=999&term_src=)used shall be the most recently published[ poverty line ](https://www.law.cornell.edu/definitions/uscode.php?width=840&height=800&iframe=true&def_id=26-USC-281322219-528327506&term_occur=999&term_src=)as of the 1st day of the regular enrollment period for coverage during such calendar year.

[eHealth states](https://www.ehealthinsurance.com/resources/affordable-care-act/everything-to-know-about-the-annual-open-enrollment-period#:~:text=Key%20dates%20for%20open%20enrollment,up%20by%20December%2015%2C%202023.):
>The federal Open Enrollment Period runs from November 1, 2023 through January 15, 2024 for health insurance coverage beginning in 2024. 

HHS updates the FPL in mid-January of each year. So looking back to November results in the policy basing on the prior year's poverty line.

**Comment by martinholmer** [comment]
@MaxGhenis,  Thanks for the ACA open-enrollment vs FPL-publication time line in this [comment](https://github.com/PolicyEngine/policyengine-us/issues/3154#issuecomment-1764935057).  So, the tax law and the IRS forms are consistent.
