### ISSUE TITLE
SNAP Child Support Deduction

### ISSUE THREAD

**Issue by nmrodelo** [PolicyEngine/policyengine-us#316]
The Child Support deduction allows individuals to write off all/some portion of their child support payments from their gross income for SNAP calculation purposes. Per my exploration in the quality control data, about 2.06% of individuals in SNAP claim this deduction .

High level of state variability in this parameter - seems from my initial exploration that states have the policy option of not allowing this as a deduction at all (need to confirm)

**Comment by MaxGhenis** [comment]
We have a variable for this but no formula or parameter: https://github.com/PolicyEngine/openfisca-us/blob/master/openfisca_us/variables/usda/snap/income/deductions/snap_child_support_deduction.py

As @nmrodelo mentioned, the [USC](https://www.law.cornell.edu/uscode/text/7/2014#e_4) allows states to vary this.

**Comment by MaxGhenis** [comment]
We now capture this by state: https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/parameters/gov/usda/snap/income/deductions/child_support.yaml
