### ISSUE TITLE
Fix formula for Ohio senior citizen credit

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3175]
In the 0.507.1 version, the specification of the formula for the `oh_senior_citizen_credit` variable causes **the model to crash** with the following error:
```
variables/gov/states/oh/tax/income/credits/oh_senior_citizen_credit.py
line 29, in formula
    any_elderly * has_not_taken_lump_sum_distribution * credit_amount
ValueError: operands could not be broadcast together
            with shapes (100000,) (279905,) 
```
This error occurs because `any_elderly` and `credit_amount` are tax_unit variables, but
`has_not_taken_lump_sum_distribution` is a person variable.

**Comment by martinholmer** [comment]
@PavelMakarchuk and @MaxGhenis,  Why do you keep merging Ohio pull requests that can't be tested because of the **model crash** described in issue #3175?  Shouldn't the top priority be to fix the model crash?

**Comment by PavelMakarchuk** [comment]
> @PavelMakarchuk and @MaxGhenis, Why do you keep merging Ohio pull requests that can't be tested because of the **model crash** described in issue #3175? Shouldn't the top priority be to fix the model crash?

@martinholmer  the other issue has been filed a month prior to #3175 and has been worked on by a different developer. I will prioritize the review of the issues that are holding up the integration testing.
