### ISSUE TITLE
Reform Abolish Net Investment Tax

### ISSUE THREAD

**Issue by ThapeloMasasa** [PolicyEngine/policyengine-us#3177]
Reference:
https://taxfoundation.org/research/all/federal/growth-opportunity-us-tax-reform-plan/#timeline

**Comment by MaxGhenis** [comment]
We don't need a reform to simulate abolitions, we can use the [abolish switch](https://policyengine.org/us/policy?focus=gov.abolitions.net_investment_income_tax&reform=32694&region=enhanced_us&timePeriod=2023&baseline=2) or the [`neutralize_variable`](https://policyengine.github.io/policyengine-core/python_api/taxbenefitsystems.html?highlight=neutralize#policyengine_core.taxbenefitsystems.tax_benefit_system.TaxBenefitSystem.neutralize_variable) method in Python.

* Tax Foundation: [$49.2 billion (2024)](https://taxfoundation.org/research/all/federal/growth-opportunity-us-tax-reform-plan/#timeline)
* PolicyEngine (CPS): [$11.8 billion (2023)](https://policyengine.org/us/policy?focus=policyOutput.netIncome&reform=32694&region=us&timePeriod=2023&baseline=2)
* PolicyEngine (enhanced CPS): [$43.5 billion (2023)](https://policyengine.org/us/policy?focus=policyOutput.netIncome&reform=32694&region=enhanced_us&timePeriod=2023&baseline=2)
