### ISSUE TITLE
Add Idaho Permanent Building Fund Tax

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3179]
The absence of this small Idaho tax makes all the test cases have a tax difference in the TAXSIM35 integration testing described in issue #993.   What do people think about whether or not this tax should be considered part of the Idaho state income tax?

<img width="636" alt="Screenshot 2023-10-20 at 4 01 29 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/de5ab54f-1a1a-49f7-8ee1-537a160ad3aa">

**Comment by MaxGhenis** [comment]
I think we should include this
