### ISSUE TITLE
Include Delaware itemized deduction for Delaware income tax 

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3185]
In the 0.509.0 version, the `de_itemized_deductions` variable formula is incorrect.
There is no reference to the Delaware Schedule A form, so I'm assuming the problem is caused by not reading that tax form.

The current formula is:
```
adds = ["itemized_deductions_less_salt"]
```
But the [2021 Delaware Schedule A form](https://revenuefiles.delaware.gov/2021/TY21_PIT-RSA_2021-01_PaperInteractive.pdf) clearly shows this is incorrect.  In particular, Delaware does allow an itemized deduction of Delaware income taxes paid up to $10,000.  TAXSIM35 does model this correctly, and so there are many differences between the two models even in the simplest `e21` sample used in issue #993.

**Comment by martinholmer** [comment]
@PavelMakarchuk,  When you revise the `de_itemized_deductions` formula, you will need to comment out the `de_income_tax` entry in the list in the `state_income_tax.py` module.  Just follow the syntax of other states that have circular logic errors.

**Comment by PavelMakarchuk** [comment]
This was fixed by #3223 - it did not create a circular reference

**Comment by martinholmer** [comment]
@PavelMakarchuk said in issue #3185:
> This [issue] was fixed by https://github.com/PolicyEngine/policyengine-us/pull/3223 

Than why is issue #3185 still open?   
Why didn't the merge of #3223 close issue #3185?

**Comment by PavelMakarchuk** [comment]
The issue was not linked in the PR, will close it now
