### ISSUE TITLE
Randomly sample ZIP codes in CPS within the state

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#3202]
Currently randomly sampled nationwide, which creates inconsistency between e.g. county and state

Let's also assign ZIPs in the CPS stage rather than variable formula

**Comment by martinholmer** [comment]
@MaxGhenis said in issue #3202:
> Currently randomly sampled nationwide, which creates inconsistency between e.g. county and state
>
> Let's also assign ZIPs in the CPS stage rather than variable formula

Merged pull requests #3227 and #3228 are now sampling zip codes by state rather than nationally, but did that by adding a formula for the `zip_code` variable.

So, where do these changes leave issue #3202?

**Comment by MaxGhenis** [comment]
Fixed in #3227
