### ISSUE TITLE
Benefits aren't summing in web app

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#3203]
https://policyengine.org/us/household?focus=householdOutput.netIncome&household=35406

This began after adding CCCAP. Likely something in core.

<img width="415" alt="image" src="https://github.com/PolicyEngine/policyengine-us/assets/6076111/9220dca1-c152-4a0f-a0d2-3e8b6fe158ec">

**Comment by MaxGhenis** [comment]
Also likely related...
<img width="575" alt="image" src="https://github.com/PolicyEngine/policyengine-us/assets/6076111/0e44720a-3481-41a0-b02a-ec373fbabf5b">

**Comment by nikhilwoodruff** [comment]
Specifically related to Colorado households
