### ISSUE TITLE
Remove taxcalc-related logic from system.py and tools

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3236]
Several recent PRs have removed obsolete variables and variable aliases left over from early development work.  This removal project needs to be completed by streamlining the `system.py` code.

**Comment by MaxGhenis** [comment]
Sounds good. Since both taxcalc and policyengine-us validate against taxsim, we shouldn't need to compare policyengine-us directly to taxcalc. If the mappings remain useful for migrating users, we can reference that via the code history and restore it in a more documentation-oriented way.
