### ISSUE TITLE
Add West Virginia elderly/disabled AGI subtraction

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3242]
In the 0.519.0 version, the WV income tax module does not yet include logic for the elderly/disabled AGI subtraction.

<img width="1196" alt="Screenshot 2023-11-06 at 6 53 33 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/859dcd82-d080-447f-b797-c5d22ef4323e">

**Comment by yedeer12** [comment]
SENIOR CITIZEN OR DISABILITY DEDUCTION
https://tax.wv.gov/Documents/PIT/2022/PersonalIncomeTaxFormsAndInstructions.2022.pdf#page=26
![image](https://github.com/PolicyEngine/policyengine-us/assets/104268340/904eac8c-ce31-4a85-b1b2-690ff37cee11)
