### ISSUE TITLE
Fix definition of income used to calculate Maine fairness credits

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3248]
The 0.520.0 version, includes the following specification of income used to calculate the Maine fairness credits:

<img width="1440" alt="Screenshot 2023-11-08 at 11 31 57 AM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/e8188e53-7741-4eee-b39f-6c7b05bda929">

But the first two items in the above list are incorrect.   The [2021 form](https://www.maine.gov/revenue/sites/maine.gov.revenue/files/inline-files/21_1040me_sched_pstfc_dwnldff.pdf) makes it clear that the first list item is not federal AGI, but rather federal total income (before above-the-line adjustments), and that the second item is not total social security benefits, but rather only social security benefits not included in federal total income.   Including all social security benefits overstates fairness income in cases where some social security was taxed at the federal level.  This overstatement of fairness income causes an underestimate of the size of the fairness credits in many cases.  And this leads to many differences with TAXSIM35.

**Comment by PavelMakarchuk** [comment]
> ocial security benefits not included in federal total income

for ss: tax_exempt_social_security
