### ISSUE TITLE
Duplicate Ohio income tax parameter name deductions

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3270]
The recently-merged PR #3095 causes the model to crash with the following error:
```
ValueError: gov.states.oh.tax.income has already a child named deductions
```
The error arises because `deductions` is used in two different ways in the Ohio income tax parameter tree:

<img width="1176" alt="Screenshot 2023-11-15 at 3 09 20 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/92f5baf8-cf33-480f-abfd-b0c43f93caad">

**Comment by MaxGhenis** [comment]
@nikhilwoodruff where can we file an issue to add tests to catch this? core?
