### ISSUE TITLE
Fix formula for ut_ss_benefits_credit_max variable

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3289]
Utah provides, at least as far back as 2021, a social security benefits credit as can be seen in these 2021 instructions:

<img width="424" alt="Screenshot 2023-11-20 at 6 39 02 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/9caf9b99-74b8-48de-aa8c-230384461890">

However, for some unexplained reason @nikhilwoodruff coded the formula for the `ut_ss_benefits_credit_max` variable in this way:

<img width="1658" alt="Screenshot 2023-11-20 at 6 44 03 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/df98da8c-e0a8-4990-a8d9-4aa209b10ac8">

Adding the `_2022` to the formula name seems to set the maximum value of this credit to zero in years before 2022.   But as the screenshot of the 2021 Utah income tax instructions make clear, this credit was available in 2021.  There are thousands of differences between Policyengine-US and TAXSIM35 because of this mistaken assumption that there was no social security benefits credit before 2022.

**Comment by nikhilwoodruff** [comment]
Thanks Martin for identifying this. At the time I don't think we had the parameters and were focussing on 2022 or current-year policies first before moving backwards.

**Comment by PavelMakarchuk** [comment]
@mzx-4real can take a look to fix it, thanks
