### ISSUE TITLE
Montana income tax changes in 2024 

### ISSUE THREAD

**Issue by hua7450** [PolicyEngine/policyengine-us#3291]
Beginning in Tax Year 2024, taxpayers will see changes to filing statuses, tax brackets, the calculation of Montana taxable income, a new subtraction, and some repealed deductions. See details in the link: https://montana.servicenowservices.com/citizen?id=kb_article_view&sysparm_article=KB0018635,
bill: https://leg.mt.gov/bills/2023/billhtml/SB0121.htm

**Comment by PavelMakarchuk** [comment]
Completed in #3506
