### ISSUE TITLE
Double import in system.py module

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3318]
@nikhilwoodruff,  Why is `create_structural_reforms_from_parameters` imported twice?
Once on line 17 and another time on line 19 in the code below:

<img width="1213" alt="Screenshot 2023-11-28 at 10 03 14 AM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/a9fc07ce-d11b-4feb-b46b-2c8baa4b1819">

**Comment by MaxGhenis** [comment]
Thanks Martin, here are the relevant lines:
https://github.com/PolicyEngine/policyengine-us/blob/96210fb01d9c0c09a5d963e8be02435bb3e58caa/policyengine_us/system.py#L17-L19

Also just as a heads up [here's how](https://www.loom.com/share/465d33bd1d7d43708d5fc998ec4f1775) I got those lines to preview with the link to the code in the issue. This can help others navigate to the relevant lines more quickly than a screenshot.

**Comment by martinholmer** [comment]
@MaxGhenis,  Thanks for the code highlighting tip!

**Comment by nikhilwoodruff** [comment]
Thanks both!
