### ISSUE TITLE
Los Angeles county General Relief disability eligibility 

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-us#3365]
Currently we assume that the disability income eligibility supersedes all other eligibility requirements. This needs to be verified. 

Relevant section of the [information sheet](https://drive.google.com/file/d/1Oc7UuRFxJj-eDwTeox92PtmRVGnG9RjW/view):

> If you, your spouse or domestic partner are sick or disabled and unable to work:
> o You can receive GR if your doctor determines you cannot work.
> o If you do not have a doctor, DPSS will refer you to a medical facility to determine if you can work.
> o You must apply for other disability benefit programs if you seem to be eligible for them. These include:
> • Social Security Disability.
> • State Disability Insurance.
> • Supplemental Security Income (SSI).
> • SSI/SSP benefits with the Social Security Administration, if you are permanently disabled and cannot work.
> ▪ While the SSI/SSP eligibility is pending, you may be able to receive GR.
> ▪ If your SSI/SSP application is denied, you must appeal the decision.
> ▪ If you need help with your application for SSI/SSP, ask your DPSS worker for more information. This
> includes help filing an appeal if you are denied.

**Comment by MaxGhenis** [comment]
Per SBN conversation, let's remove the disability-superseding logic
