### ISSUE TITLE
Fix calculation of Michigan standard deduction tier three amount

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3412]
In the 0.569.0 model version, there are several problems with the calculation of MI tier 3 standard deductions.  First, the birth year eligibility parameters do not correspond to those stated in the MI income tax form instructions for 2020, 2021, and 2022.   Second, the formula for the `mi_standard_deduction_tier_three` variable does not correspond to the logic of the TIER 3 MICHIGAN STANDARD DEDUCTION WORKSHEET in the form instructions.

It would be prudent to conduct a comprehensive review of parameters and formulas, and then add many more unit tests.

**Comment by PavelMakarchuk** [comment]
@Mshuning one of the issues that we saw is that we use mi_exemptions but the instruction specify only line 9a which are the personal exemptions 
(also 9d but we do not model stillborn exemptions currently)

![image](https://github.com/PolicyEngine/policyengine-us/assets/110687043/d3f96515-7ad1-450f-8e90-3e38d3e2591b)
