### ISSUE TITLE
Add formula for Virginia AGI variable

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3424]
There is no formula for the `va_agi` variable in the 0.571.2 model version.
As a result, all VA AGI, taxable income, and income tax values are zero.

Why isn't there a unit test to spot this problem?

**Comment by MaxGhenis** [comment]
Why do you say this is a bug? We haven't completed the Virginia model yet.

**Comment by martinholmer** [comment]
Resolved by merge of pull request #3341.
