### ISSUE TITLE
Subtract only positive long-term captial gains to get Arizona AGI

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3425]
It seems as if only a fraction of **positive** federal LTCG should be an AZ AGI subtraction.  Do we really think AZ calls for those with long-term capital losses to have an AZ AGI be larger than federal AGI?

This could be fixed by replacing this:

https://github.com/PolicyEngine/policyengine-us/blob/d8d5d2da0b7cd6432f87c2d5efe25bdea963b753/policyengine_us/variables/gov/states/az/tax/income/subtractions/capital_gains/az_long_term_capital_gains_subtraction.py#L22

with this:
```
return max_(0, long_term_capital_gains) * p.rate
```

**Comment by MaxGhenis** [comment]
This refers to Line 1 of the worksheet, which states:
>Enter the total net long-term capital gain or (loss) from assets acquired after December 31, 2011 and included in federal adjusted gross income

Could `or (loss)` indicate that losses should result in AZ AGI > US AGI?

**Comment by martinholmer** [comment]
@MaxGhenis said:
> This refers to Line 1 of the worksheet, which states:
>
>> Enter the total net long-term capital gain or (loss) from assets acquired after December 31, 2011 and included in federal adjusted gross income

I'm not sure what worksheet you are quoting, but the 2021 form instructions seem clear to me:

<img width="844" alt="Screenshot 2023-12-11 at 2 52 30 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/1f004990-1803-444c-8b4e-db424d7222a4">

The AGI subtraction amount (Line 24) is (in 2021) 25% of Line 23.  And (unlike Lines 20, 21 and 22) Line 23 does **not** have an `or (loss)` phrase in it.

**Comment by martinholmer** [comment]
@MaxGhenis,  Thanks for the clarification in issue #3425.
