### ISSUE TITLE
Question about Arizona itemized deductions

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3426]
In the formula for the `az_itemized_deductions` variable, all (that is, uncapped-by-the-federal-SALT-rules) local property taxes are included AZ itemized deductions:

https://github.com/PolicyEngine/policyengine-us/blob/d8d5d2da0b7cd6432f87c2d5efe25bdea963b753/policyengine_us/variables/gov/states/az/tax/income/deductions/itemized/az_itemized_deductions.py#L57

Where exactly is the documentation that says that this is the correct thing to do?
I did not see anything in the form or instructions that said to do this.  Did I miss something?

**Comment by PavelMakarchuk** [comment]
> In the formula for the `az_itemized_deductions` variable, all (that is, uncapped-by-the-federal-SALT-rules) local property taxes are included AZ itemized deductions:
> 
> https://github.com/PolicyEngine/policyengine-us/blob/d8d5d2da0b7cd6432f87c2d5efe25bdea963b753/policyengine_us/variables/gov/states/az/tax/income/deductions/itemized/az_itemized_deductions.py#L57
> 
> Where exactly is the documentation that says that this is the correct thing to do? I did not see anything in the form or instructions that said to do this. Did I miss something?

I believe you are right, it should be quite the opposite where the state income tax is deducted (after limitations)
![image](https://github.com/PolicyEngine/policyengine-us/assets/110687043/0e610733-740f-4c82-a885-6961a2bc5900)

**Comment by PavelMakarchuk** [comment]
> In the formula for the `az_itemized_deductions` variable, all (that is, uncapped-by-the-federal-SALT-rules) local property taxes are included AZ itemized deductions:
> 
> https://github.com/PolicyEngine/policyengine-us/blob/d8d5d2da0b7cd6432f87c2d5efe25bdea963b753/policyengine_us/variables/gov/states/az/tax/income/deductions/itemized/az_itemized_deductions.py#L57
> 
> Where exactly is the documentation that says that this is the correct thing to do? I did not see anything in the form or instructions that said to do this. Did I miss something?

@martinholmer I believe you are right the [legal code](https://law.justia.com/codes/arizona/2022/title-43/section-43-1042/) seems to state that the total salt deduction amount can be claimed, with a limitations for charitable contributions deducted under the AZ charitable contributions credit. 

Additionally there seems to be an inconsistency in the medical expense calculation. The current code applies the difference between the federal deduction and total expenses but I believe we should deduct the total medical expense amount
![image](https://github.com/PolicyEngine/policyengine-us/assets/110687043/54db17f2-690a-4cd7-8283-0da716ea4e04)
