### ISSUE TITLE
Add federal income tax as a Montana itemized deduction

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3427]
The [2021 Montana income tax instructions](https://mtrevenue.gov/wp-content/uploads/mdocs/form%202%202021%20instructions.pdf#page=32) make it clear that up to $5,000 (or $10,000 for joint filers) of federal income tax liability (that is, the `income_tax` variable) can be a Montana itemized deduction.   The fact that this feature of the Montana income tax is not yet included in Policyengine-US means that there are thousands of differences with TAXSIM35 even in the simple `e21` sample that includes no expenses that are itemizable on a federal return.

**Comment by PavelMakarchuk** [comment]
@Shinuing
