### ISSUE TITLE
Question about South Carolina net capital gains deduction

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3452]
In the 0.578.0 model version, the formula for the `sc_net_capital_gain_deduction` calculates the deduction as 44% of the `net_capital_gain` variable (which **includes** qualified dividends) rather than 44% of the `net_capital_gains` variable (which **excludes** qualified dividends).  The cited reference provides a detailed example, but the example does not include any qualified dividends.   Also, for whatever it is worth, TAXSIM35 interpretes this SC deduction as having nothing to do with qualified dividends.

So, the question is whether there is some specific tax-legislation or form-instruction language that can be pointed to in order to rationalize the use of the `net_capital_gain` variable rather the `net_capital_gains` variable.

**Comment by MaxGhenis** [comment]
Adding @hua7450 who implemented this in #2718

Separately, should we further disambiguate the names of `net_capital_gain` vs `net_capital_gains`? Are these standard names to refer to inclusion of qualified dividends @martinholmer?

**Comment by hua7450** [comment]
It should use the net_capital_gains.py. 
![image](https://github.com/PolicyEngine/policyengine-us/assets/113824411/ea394cbb-e783-4125-8753-319aa7c63d24)

**Comment by martinholmer** [comment]
@MaxGhenis asked:
> Separately, should we further disambiguate the names of `net_capital_gain` vs `net_capital_gains`?  Are these standard names to refer to inclusion of qualified dividends @martinholmer?

I don't know.  Check with @nikhilwoodruff, who I believe created these two variables.

**Comment by martinholmer** [comment]
I'd like to correct my original comment in issue #3452.  I have examined more closely the following example in  the 2021 SC form instructions:

<img width="1438" alt="Screenshot 2023-12-15 at 8 51 29 AM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/5f2a1945-4f92-4b38-8c33-339264a8bdd4">

While my original comment does seem to have moved us to a realization that qualified dividends play no role in calculation of the `sc_net_capital_gain_deduction`, my original comment is suggesting an alternative that seems incorrect.  Let me explain my current thinking and people can correct me if necessary.

This deduction is the product of a rate and a base.  The rate is 44%.   The question now is what is the base.

It seems from the above instructions that the base is essentially positive long-term capital gains except that the base can be reduced (to zero) if the tax-unit has any short-term capital losses.  So, the formula for the base seems like it should be something like this:
```
ltcg = add(tax_unit, period, ["long_term_capital_gains"]
stcg = add(tax_unit, period, ["short_term_capital_gains"]
base = max_(0, ltcg + min_(0, stcg))
```
In any case, the pull request that revises the `sc_net_capital_gain_deduction` formula should include several unit tests that specify different values for qualified dividends, long-tern capital gains, and short-term capital gains.
