### ISSUE TITLE
Fix Alabama itemized deductions

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3493]
In the 0.584.3 version, much of the AL itemized deduction logic make no sense to me.   Here are the sources:

<img width="1094" alt="Screenshot 2023-12-18 at 3 28 11 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/68a3f5e7-d3b7-4ff1-a4aa-1ff50c3e0dc7">

The first two items do make sense: `real_estate_taxes` are fully itemizable under the AL income tax and the `charitable_deduction` variable makes sense.

But after that, I'm puzzled.

For instance, what does the following comment mean?
```
# Redundant with `taxsim_tfica`, but broken out to keep in PolicyEngine variables.
```
What exactly is "broken out" and why?

And what is the `al_mortgage_interest_deduction`?  How exactly does it differ from the `mortgage_interest` variable?   And most importantly, why does the `al_mortgage_interest_deduction` variable have no formula.
And the same questions for the `al_investment_interest_deduction` variable.

It seems as if the Alabama itemized deduction calculation needs a comprehensive review and extensive revisions.

**Comment by MaxGhenis** [comment]
Re `taxsim_tfica`, that's defined as:
https://github.com/PolicyEngine/policyengine-us/blob/546f600d4887010227ecbd80848d4437259a2360/policyengine_us/variables/contrib/taxsim/taxsim_tfica.py#L11

So we could have saved a comma by using `taxsim_tfica`, but opted to avoid taxsim variables.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> So we could have saved a comma by using `taxsim_tfica`, but opted to avoid taxsim variables.

I think that was a wise approach.  But the problem with the pre #3495 code, is that the two PEUS variables (`employee_payroll_tax` and `self_employment_tax`) were not included in the list of itemizable expenses.
