### ISSUE TITLE
Fix New York supplemental tax calculations

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3546]
Using the 0.601.0 version, there are many tax differences in the amounts for the `ny_income_tax_before_credits` variable in comparison with TAXSIM35 even though the two models produce the same NY AGI and same NY taxable income amounts.  

In fact, pull request #3373, which was intended to fix issue #1679, actually **increased** the number of `e21` sample tax differences rather than reducing them.

The problem, as originally pointed out in issue #1679, is that PolicyEngine-US logic does not, in all cases, follow the logic of the simple supplemental income tax worksheets included in the NY income tax instructions.

The way to eliminate these differences is to create a 2021 test for each of the several supplemental tax worksheets (where the output is calculated by hand given AGI and taxable income), and then prepare a pull request that modifies the code so that all those tests pass.

**Comment by Shinuing** [comment]
Hello @martinholmer , some explanations for the #3373 

> The problem, as originally pointed out in issue #1679, is that PolicyEngine-US logic does not, in all cases, follow the logic of the simple supplemental income tax worksheets included in the NY income tax instructions.
> 
Now the ny supplemental income tax follows the [The Laws of New York](https://www.nysenate.gov/legislation/laws/TAX/601) (d-2) for 2021 and (d-3) for 2022. Which the calculation is exactly the same as the [Form IT 201](https://www.tax.ny.gov/pdf/2021/inc/it201i_2021.pdf#page=52) just with different names (recapture base and incremental benefit)

> The way to eliminate these differences is to create a 2021 test for each of the several supplemental tax worksheets (where the output is calculated by hand given AGI and taxable income), and then prepare a pull request that modifies the code so that all those tests pass.
>
The output now is also calculated by hand given AGI and taxable income
I have created unit tests for 2021 JOINT filers. Including 2 in #1679 and 2 corner cases for taxable income < $43,000 and NY AGI > $25,000,000. Please notice that there's no exception calculations in the Form IT 201, only AGI ranges from $107,650 to $25,000,000
For other filing status, I picked a number from the AGI ranges for calculations checking. I can create more.

The thing we can do for now is to create every unit test in each AGI and taxable income ranges for all filing status. Let me know if this is what you want

Calculations in [spreadsheet ](https://docs.google.com/spreadsheets/d/1jS4mFiGweHnK-e4Hdku5S3GD6jZpboCE/edit?usp=sharing&ouid=117507030405629393458&rtpof=true&sd=true)

**Comment by martinholmer** [comment]
In issue #3546, @Shinuing said (among other things):

> Please notice that there's no exception calculations in the Form IT 201, only AGI ranges from $107,650 to $25,000,000.

I have two questions about your statement:

(1) What exactly do you mean by "exception calculations"?

(2) What document are you looking at?   The 2021 Form IT-201 **instructions** include 16 tax computation worksheets with 3 of the 16 covering taxpayers with NY AGI more than $25,000,000.  These 2021 worksheets are at the following URL:
https://www.tax.ny.gov/pdf/2021/inc/it201i_2021.pdf#page=52
though
https://www.tax.ny.gov/pdf/2021/inc/it201i_2021.pdf#page=57

**Comment by Shinuing** [comment]
Hi @martinholmer 
> 
> (1) What exactly do you mean by "exception calculations"?
> 
The [Section 601](https://www.nysenate.gov/legislation/laws/TAX/601) is calculated the supplemental tax in this way

Let's put **JOINT** filing as example:
(1) when AGI is between $107,650 to 25,000,000, Supplemental tax = recapture base + phase-in fraction * incremental benefit
_The same as [Tax computation worksheet 1-5](https://www.tax.ny.gov/pdf/2021/inc/it201i_2021.pdf#page=52)_
(2) Exception 1:  when NY AGI > $25,000,000, Supplemental tax = NY Taxable income * 10.9% -NY main Tax
_Part of the [Tax computation worksheet 1](https://www.tax.ny.gov/pdf/2021/inc/it201i_2021.pdf#page=52)_
(3) Exception 2:  when taxable income < $43,000, Supplemental tax = NY Taxable income * 5.97% - phase-in fraction * NY main Tax 
_The same as [Tax computation worksheet 6](https://www.tax.ny.gov/pdf/2021/inc/it201i_2021.pdf#page=53)_
> (2) What document are you looking at? 

I followed the [The Laws of New York](https://www.nysenate.gov/legislation/laws/TAX/601) (d-2) for 2021 and (d-3) for 2022

As I mentioned, the calculation from the legal law are exactly the same as the form IT 201 just the name
Example:
![image](https://github.com/PolicyEngine/policyengine-us/assets/87620347/07e7ab98-84fa-4511-b975-0b98573afa2b)

Hope that make more sense :) I'll create all unit tests for all situations soon

**Comment by martinholmer** [comment]
@Shinuing said in issue #3546 (among other things):

> (3) Exception 2: when taxable income < $43,000, Supplemental tax = NY Taxable income * 5.97% - phase-in fraction * NY main Tax
The same as [Tax computation worksheet 6](https://www.tax.ny.gov/pdf/2021/inc/it201i_2021.pdf#page=53)

But when I look at the 2021 worksheet 6, I don't see anything about "taxable income < $43,000".   Here is what I see:

<img width="563" alt="Screenshot 2024-01-08 at 1 34 21 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/f5d02de4-be72-4160-bad2-f4338a8e2a42">

I don't understand this "< $43,000 exception" business.   What are you looking at that has you focused on this?

**Comment by Shinuing** [comment]
Hi @martinholmer 

I'm sorry it's in part of [Tax computation worksheet 1](https://www.tax.ny.gov/pdf/2021/inc/it201i_2021.pdf#page=52)
_your taxable income (line 38) is$161,550 or less_

> I don't understand this "< $43,000 exception" business. What are you looking at that has you focused on this?

I'm looking at this because in the [Section 601](https://www.nysenate.gov/legislation/laws/TAX/601), there's a separate paragraph for taxable income <$43,000
![image](https://github.com/PolicyEngine/policyengine-us/assets/87620347/f531a40e-5c60-4f1b-9b20-5d87d08973cc)

Now all tax computation test cases are in #3568

**Comment by martinholmer** [comment]
@Shinuing said in issue #3546 (among other things):

> I'm sorry it's in part of [Tax computation worksheet 1](https://www.tax.ny.gov/pdf/2021/inc/it201i_2021.pdf#page=52)
your taxable income (line 38) is$161,550 or less

When I look at 2021 worksheet 1, I don't see anything about taxable income less than $43,000.   Did I miss something?   Here is the 2021 worksheet 1:

<img width="919" alt="Screenshot 2024-01-08 at 2 11 23 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/0138eb12-83b4-497b-b865-662ff0b61f11">

**Comment by Shinuing** [comment]
Hi @martinholmer 

taxable income < $43,000 belongs to taxable income < $161,550

I think the form merge those two situations
