### ISSUE TITLE
Fix Ohio joint filing credit logic

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3548]
In the 0.601.0 version, the Ohio income tax calculations cause PolicyEngine-US to crash.

The problem seems to be that the `oh_partial_non_refundable_credits` variable is defined by an `adds` statement that points to a non-existent parameter.

It seems as if this sort of potential error should be checked in the unit tests.
Why isn't this being done?

**Comment by MaxGhenis** [comment]
Thanks @martinholmer. I filed #3549 to fix this.

I fully agree we need to catch these, and have filed several issues along these lines, such as https://github.com/PolicyEngine/policyengine-us/issues/2339. We currently request developers to include unit tests only for variables with a `formula` method. Adding a requirement for `adds` and `subtracts` attributes would clutter tests and slow developers with trivial tasks that we should be able to automate instead.

@nikhilwoodruff or @anth-volk could we revisit some of these testing issues to see if we have some low-hanging fruit?

**Comment by nikhilwoodruff** [comment]
Completely agree. Currently we procedurally test that each variable calculates without error for a basic simulation, but I don't think this catches variables that are only defined for a particular state. I think the obvious solution is to create 50 basic situations, one for each state, and test each variable calculates without error for them? Should be pretty straightforward.

**Comment by anth-volk** [comment]
@nikhilwoodruff How high of a priority would you say this is vis-à-vis other ongoing issues? And I would imagine doing this requires roping in @PavelMakarchuk?
