### ISSUE TITLE
Randomness causing small impact of null reforms

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#3579]
For example, [this reform](https://policyengine.org/us/policy?focus=policyOutput.policyBreakdown&reform=44027&region=us&timePeriod=2023&baseline=2) takes effect in 2024 and therefore should have no effect on 2023, yet we're seeing a small budgetary impact. Assume this is due to some household randomness.

<img width="1067" alt="image" src="https://github.com/PolicyEngine/policyengine-us/assets/6076111/c94a0bbc-f9c4-42a7-8d49-c75e06d0049e">

**Comment by nikhilwoodruff** [comment]
This is fixed I think.
