### ISSUE TITLE
Fix Michigan home heating credit

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3585]
In the 0.615.0 version, the MI home heating credit amount is incorrectly calculated in some cases.

For example, an elderly couple with $12,020 income and four dependents gets a credit of over **five million dollars**.  For the same case, TAXSIM35 generates a heating credit of less than one thousand dollars.   

These results indicate that the project's stated goal of using "test-driven development" is not being practiced at an adequate level.  By any sensible definition of test-driven development, the pull request that added the MI heating credit should have been able to detect an error of this magnitude.

**Comment by MaxGhenis** [comment]
@PavelMakarchuk let's add integration tests to programs like these moving forward

**Comment by PavelMakarchuk** [comment]
> @PavelMakarchuk let's add integration tests to programs like these moving forward

Agreed, thank you @martinholmer
