### ISSUE TITLE
Fix Oregon WFHDC credit child care expenses cap & employment eligibility 

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3586]
In the 0.615.0 version, the OR working family household and dependent care credit is incorrectly calculate in some cases.  In 2021 Oregon allowed more care expenses than the federal CDCC as indicated in these instructions:

<img width="1511" alt="Screenshot 2024-01-11 at 3 56 24 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/649fa3e4-6ff5-4af7-9b8c-c4231b04d9ba">

**Comment by PavelMakarchuk** [comment]
[Law](https://oregon.public.law/statutes/ors_315.264)

**Comment by PavelMakarchuk** [comment]
Based on @Shinuing 's research, I believe, as Martin said, the error was caused by the child care expenses being capped to the federal CDCC which is now adjusted to the Oregon cap. We also found that there are some employment eligibility requirements which we have not considered
