### ISSUE TITLE
Fix West Virginia family tax credit

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3603]
In the 0.615.0 version, there are several problems with the representation of the WV family tax credit.

First, the name `wv_low_income_family_tax_credit` is confusing because there is no credit with that name on the WV income tax form or in its instructions.   Plus, the current variable name is verbose: what does "low_income" add?   Most credits are restricted to taxpayers with lower income.  For clarification, I would suggest naming this variable `wv_family_tax_credit`.

Second, the credit formula uses state AGI (rather than federal AGI plus WV additions and tax-exempt interest), which leads to differences between results produced by Policyengine-US and TAXSIM35.

Third, the credit formula ignores the fact that paying the federal AMT makes you ineligible for the WV family tax credit.

**Comment by PavelMakarchuk** [comment]
> In the 0.615.0 version, there are several problems with the representation of the WV family tax credit.
> 
> First, the name `wv_low_income_family_tax_credit` is confusing because there is no credit with that name on the WV income tax form or in its instructions. Plus, the current variable name is verbose: what does "low_income" add? Most credits are restricted to taxpayers with lower income. For clarification, I would suggest naming this variable `wv_family_tax_credit`.
> 
> Second, the credit formula uses state AGI (rather than federal AGI plus WV additions and tax-exempt interest), which leads to differences between results produced by Policyengine-US and TAXSIM35.
> 
> Third, the credit formula ignores the fact that paying the federal AMT makes you ineligible for the WV family tax credit.

Thank you Martin,  believe the [following](https://code.wvlegislature.gov/11-21-22/) legal source mentions the term "low-income family tax credit" which is then only referred to as "credit" in the remaining attached sections of the legal code. 

I will add a reference to the vars and adjust the other two points

![image](https://github.com/PolicyEngine/policyengine-us/assets/110687043/548b5d43-ceae-4bbe-973f-08a75df91f96)
