### ISSUE TITLE
DC Local State Supplement - additional SNAP minimum allotment

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#3610]
Mentioned [here](https://dhs.dc.gov/page/give-snap-raise-heres-what-expect):

>In the District of Columbia, the “Local State Supplement” (LSS) ensures that every SNAP household receives a minimum of $30 per month.

They state a $23 minimum allotment at https://dhs.dc.gov/service/snap-benefits but that seems incorrect and just copied from federal rules

Source: https://code.dccouncil.gov/us/dc/council/code/sections/4-261.04

@benmolin FYI - doesn't look like snapscreener has this (got $23/mo after entering an individual with $1,400/mo earnings)

**Comment by benmolin** [comment]
Thanks for the tag @MaxGhenis. Here's something similar in NJ: https://www.nj.gov/humanservices/njsnap/apply/eligibility/

> New Jersey has a minimum monthly SNAP benefit amount of $95.  If you apply for SNAP and are approved to receive the federal minimum payment or any amount less than $95, New Jersey will add a supplemental payment so that the amount you receive equals $95.
