### ISSUE TITLE
Discrepancy between web app and Python package in baseline poverty rate

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#3634]
The web app currently shows a [8.7% baseline poverty rate](https://policyengine.org/us/policy?focus=policyOutput.povertyImpact&timePeriod=2023&region=us&baseline=2&reform=44780)

<img width="890" alt="image" src="https://github.com/PolicyEngine/policyengine-us/assets/6076111/b48a1b94-2d78-41ed-9db5-7cbcf8ae0f97">

However, pinning the same package version (0.621.0), and applying the `reported_state_income_tax` parameter, the Python package shows a 8.5% baseline poverty rate ([notebook](https://colab.research.google.com/drive/1sF5NnVOG3Qy7pvKsZp8bBzPhC_tRQ9nP?authuser=1#scrollTo=VC_Pie7880SE)).

**Comment by MaxGhenis** [comment]
@nikhilwoodruff fixed this by removing person-level weights from the microdata release so it uses household weights everywhere

**Comment by MaxGhenis** [comment]
This is back, comparing the app and Python package. Here are top-line 2024 numbers, both using 0.683.1:

| CPS version | Population | App | Python |
| - | - | - | - |
| Base | All | [11.4%](https://policyengine.org/us/policy?focus=policyOutput.povertyImpact&reform=3729&region=us&timePeriod=2024&baseline=2) | [11.9%](https://colab.research.google.com/drive/19WpcHglhMOV9Eo52jEGiVf5QYM4QXMNm#scrollTo=Kb_Fr6LKD0-f) |
| Enhanced | All | [13.1%](https://policyengine.org/us/policy?focus=policyOutput.povertyImpact&reform=3729&region=enhanced_us&timePeriod=2024&baseline=2) | [13.1%](https://colab.research.google.com/drive/19WpcHglhMOV9Eo52jEGiVf5QYM4QXMNm#scrollTo=Kb_Fr6LKD0-f) |
| Enhanced | Child | [12.1%](https://policyengine.org/us/policy?focus=policyOutput.povertyImpact&reform=3729&region=enhanced_us&timePeriod=2024&baseline=2) | [12.8%](https://colab.research.google.com/drive/19WpcHglhMOV9Eo52jEGiVf5QYM4QXMNm#scrollTo=Kb_Fr6LKD0-f) |

*Groups selected to highlight discrepancies.*

**Comment by nikhilwoodruff** [comment]
Just to say that locally running the Colab notebooks, I match the app. We should diagnose the Colab issue but I think this indicates that the app is correct.

**Comment by MaxGhenis** [comment]
Did you try in a fresh environment?

**Comment by MaxGhenis** [comment]
@nikhilwoodruff for posterity, could you write how we fixed this?

New results for 2024, version 0.688.1:

CPS version | Population | App | Python
-- | -- | -- | --
Base | All | 11.3% | 11.3%
Enhanced | All | 11.0% | 11.0%
Enhanced | Child | 12.6% | 12.6%
