### ISSUE TITLE
Adjust the California medicaid eligibility to include every immigration status

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-us#3639]
`is_medicaid_eligible` currently includes a formula to exclude undocumented filers which should be removed as it was reverted in 2024.

Also rules before 2024:
[Source](https://www.kff.org/racial-equity-and-health-policy/fact-sheet/key-facts-on-health-coverage-of-immigrants/)
_In January 2020, California extended state-funded Medicaid coverage to [young adults](https://www.dhcs.ca.gov/services/medi-cal/eligibility/Pages/youngadultexp.aspx) ages 19-25 regardless of immigration status, and adults [ages 50 and older](https://www.gov.ca.gov/2021/07/27/governor-newsom-signs-into-law-first-in-the-nation-expansion-of-medi-cal-to-undocumented-californians-age-50-and-over-bold-initiatives-to-advance-more-equitable-and-prevention-focused-health-care/) became eligible on May 1, 2022. The state will further extend coverage to income-eligible adults ages 26 to 49 regardless of immigration status no sooner than January 1, 2024._

**Comment by martinholmer** [comment]
@PavelMakarchuk said in issue #3639:

> `is_medicaid_eligible` currently includes a formula to exclude undocumented filers which should be removed as it was reverted in 2024.

I do not believe this statement is true.  The KFF document you source says this:

<img width="1268" alt="Screenshot 2024-01-17 at 3 39 01 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/ed2579a0-056f-4754-a418-d1cc67cfde05">

And the KFF document explicitly states that this is not true at the federal level.  The few states doing this are bearing the full cost because it is contrary to federal Medicaid law.

**Comment by PavelMakarchuk** [comment]
> @PavelMakarchuk said in issue #3639:
> 
> > `is_medicaid_eligible` currently includes a formula to exclude undocumented filers which should be removed as it was reverted in 2024.
> 
> I do not believe this statement is true. The KFF document you source says this:
> 
> <img alt="Screenshot 2024-01-17 at 3 39 01 PM" width="1268" src="https://private-user-images.githubusercontent.com/12170745/297512308-ed2579a0-056f-4754-a418-d1cc67cfde05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MDgyMDQsIm5iZiI6MTcwNTYwNzkwNCwicGF0aCI6Ii8xMjE3MDc0NS8yOTc1MTIzMDgtZWQyNTc5YTAtMDU2Zi00NzU0LWE0MTgtZDFjYzY3Y2ZkZTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDE5NTgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZDE0MGRkZjM1YzVkMDA4ZWVlZGNlOGFlYWI0YWQ4MDJmMGQxODdkNzdiMGZlMTE3ZWY0ZTQyODMyOGZmNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FFRFUvSg5RsXOlhTM93P1rF7zCWsnE4pJYBkJ43Qojw">
> And the KFF document explicitly states that this is not true at the federal level. The few states doing this are bearing the full cost because it is contrary to federal Medicaid law.

@martinholmer per karin from SBN: California is bearing the full cost, I will find references for this, if it is true

**Comment by martinholmer** [comment]
@PavelMakarchuk,

Yes, I know California had been adding (at their own cost) some immigrants that are not eligible for federal Medicaid matching payments, and that beginning in 2024, CA is covering all immigrants (regardless of their legal status).

But what you're original comment said (it seemed to me) is that all immigrants in the US were going to be covered by Medicaid beginning in 2024.   That is simply not true.

To handle CA and the four other states, you need to create one or more state-level parameters regarding each state's immigrant Medicaid eligibility.   You didn't say that in your original comment, so I feared you were going to impose CA rules nationwide.

**Comment by martinholmer** [comment]
@PavelMakarchuk said in issue #3639:

> the issue title seemed like adjusting all state rules, changed it to limit it to just California rules

It is a very bad idea to limit your scope to just California.   As I said before:

> **To handle CA and the four other states, you need to create one or more state-level parameters regarding each state's immigrant Medicaid eligibility.** 

Look at the medicaid parameter tree to see how state-specific rules are being handled.

**Comment by PavelMakarchuk** [comment]
> @PavelMakarchuk said in issue #3639:
> 
> > the issue title seemed like adjusting all state rules, changed it to limit it to just California rules
> 
> It is a very bad idea to limit your scope to just California. As I said before:
> 
> > **To handle CA and the four other states, you need to create one or more state-level parameters regarding each state's immigrant Medicaid eligibility.**
> 
> Look at the medicaid parameter tree to see how state-specific rules are being handled.

@martinholmer I have created a bool parameter which determines which states allow undocumented immigrants to receive medicaid, but I am debating whether we should be breaking it out by age group and if we can get full documentation on it
