### ISSUE TITLE
Consolidate state level additions variables across all state models 

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-us#3650]
Currently we use the following iterations:

`[state_code]_additions`
`[state_code]_income_additions`
`[state_code]_agi_additions`

we should consolidate all to 
`[state_code]_additions`

**Comment by masterismail** [comment]
Hi @PavelMakarchuk , is there any documentation available for this repo? It would be helpful to understand the codebase for troubleshooting this issue.

**Comment by PavelMakarchuk** [comment]
> Hi @PavelMakarchuk , is there any documentation available for this repo? It would be helpful to understand the codebase for troubleshooting this issue.

@masterismail you take a look at [this](https://docs.google.com/document/d/1BiajMUJZFzG24Ju5lTybCAW8tp59B3E_DNhS8eJkuR0/edit) developer guide.

Additionally, you can join our Slack and message me directly if you have any additional questions:
https://join.slack.com/t/policyengine-group/shared_invite/zt-2g1pwejib-rwcJXDuw4jd18mvk8732Yg
