### ISSUE TITLE
Fix Arkansas `ar_low_income_tax_joint` variable calculation

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3680]
In the 0.631.0 version, the AR tax calculation is not always correct.   For example, a single filer with substantial taxable income has a zero income tax liability, as shown in these trace fragments:

```
 ar_taxable_income_joint<2021, (default)> = [168820.]
 ar_income_tax_before_non_refundable_credits_joint<2021, (default)> = [0.]

 ar_income_tax_before_non_refundable_credits_indiv<2021, (default)> = [0.]
```

**Comment by PavelMakarchuk** [comment]
This was a result of the missing AGI sum in the ar_low_income_tax_joint variable
