### ISSUE TITLE
Make Virginia subtractions tax unit level and adjust the age deduction

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3701]
In the 0.632.0 version, the VA AGI is not always calculated correctly.  This should come as no surprise because there are no tests of the `va_agi` calculation logic.

For example, an elderly couple with two teenage grandchildren as dependents and a federal AGI of $71,030 has a VA AGI of **-24,970** dollars in PEUS.  TAXSIM35 generates 47,030 dollars for the VA AGI.

Current  development practice seems to be based on the belief that variables without formulas (that use just adds or subtracts lists) do not need to be tested.   My experience over the past few weeks is that nearly half of the errors discovered in the TAXSIM35 testing process involve errors in parameter files.   And because there is this mistaken belief that adds/subtracts variables (without an explicit formula) don't need any testing, all the mistakes go uncaught in the development process.  This experience shows to me that test-driven development practices should involve testing all variables with realistic tests.

Adding such tests for the `va_agi` variable is a good place to start practicing improved test-driven development.

**Comment by MaxGhenis** [comment]
To clarify our testing guidelines: we do not include unit tests for variables without a formula. Unit tests for addition and subtraction only would not uncover bugs in parameter files, or bugs in the underlying logic (in this case, we clearly have a bug in some of the specific additions and/or subtracts, not `va_agi`). But we should include integration tests on a program-level basis, as well as the full state tax integration tests you're creating, which would identify the bugs in additions and/or subtractions causing this issue.

We haven't yet formalized expectations around integration tests, given they're inherently a bit fuzzier, but I think we're moving toward more of them and should do more.

**Comment by PavelMakarchuk** [comment]
The virginia subtractions has been added as person level variable which caused certain deductions to be duplicated in the calculation.

Additionally I have removed the va_age_deductions calculation portion which splits the head and spouse amount as it is added afterwards regardless.
