### ISSUE TITLE
Documentation failing

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#3712]
In CI

**Comment by MaxGhenis** [comment]
Due to https://github.com/PolicyEngine/policyengine-core/issues/153

**Comment by MaxGhenis** [comment]
@abhcs fixed https://github.com/PolicyEngine/policyengine-core/issues/153 in https://github.com/PolicyEngine/policyengine-core/pull/162 by updating the `sphinx` pin from `4.5.0` to `5.0.0`. However, `policyengine-us` documentation is still failing despite a similar pin:

https://github.com/PolicyEngine/policyengine-us/blob/e3b8e70d221b54e064a1d671a01af27501469f40/setup.py#L63

@abhcs do you know if we're facing the same issue here? Also did a newer pin not work? (Sphinx is currently on [7.2.6](https://pypi.org/project/Sphinx/)).

**Comment by MaxGhenis** [comment]
Huh, [this CI run](https://github.com/PolicyEngine/policyengine-us/actions/runs/8149157087/job/22273332947?pr=4077#step:8:18) shows we're loading Sphinx 7.2.6

**Comment by abhcs** [comment]
[This log](https://github.com/PolicyEngine/policyengine-us/actions/runs/8146054330/job/22263700579) suggests that the package `furo` is incompatible with the new Sphinx.

**Comment by abhcs** [comment]
`make install` has two parts. The first part installs the packages using the information in `setup.py`. This installs `jupyter-book-0.15.1`. Then, the second part (`pip install --upgrade jupyter-book`) kicks in, and attempts to upgrade `jupyter-book` and its dependencies including `sphinx` to higher versions. This eventually ends in a conflict with `furo`'s version:

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
furo 2022.9.29 requires sphinx<6.0,>=4.0, but you have sphinx 7.2.6 which is incompatible.

Deleting the second line from `make install` should fix these issues, unless the upgrade is there to solve a problem that I am unaware of.

**Comment by MaxGhenis** [comment]
We probably added `pip install --upgrade jupyter-book` to address some episodic issue. If all still works after removing it let's do so.
