### ISSUE TITLE
New Jersey 2023 Individual Income Tax Parameter Updates

### ISSUE THREAD

**Issue by jingyi0808** [PolicyEngine/policyengine-us#3740]
According to the Form New Jersey Resident Return NJ-1040, 2023 Version, there're some parameter updates.

Reference: https://www.nj.gov/treasury/taxation/pdf/current/1040i.pdf

**Comment by yedeer12** [comment]
Changes:

Update New Jersey Earned Income Tax for 2023 (nj_eitc)
Update New Jersey Child Tax Credit for 2023 (nj_ctc)

**Comment by MaxGhenis** [comment]
Can you be more specific?

**Comment by yedeer12** [comment]
> Can you be more specific?
1. Update New Jersey Earned Income Tax amount for 2023 (nj_eitc)
2. Update New Jersey Child Tax Credit amount for 2023 (nj_ctc)
3. Add income limit for Property Tax Credit.
4. Separate CTC variable and eligible.

**Comment by MaxGhenis** [comment]
Please specify the previous and new values for each amended program. This issue will serve as documentation for the PR. Thanks!

**Comment by yedeer12** [comment]
> Please specify the previous and new values for each amended program. This issue will serve as documentation for the PR. Thanks!

Got it!
