### ISSUE TITLE
Don't round income/FPG level in Oregon WFHDC credit

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3755]
When I look at the [OR tax code](https://law.justia.com/codes/oregon/2021/volume-08/chapter-315/section-315-264/), I don't see anything corresponding to this Python code:

https://github.com/PolicyEngine/policyengine-us/blob/bd701543dadc53b67dee9fe744bebbd240961566/policyengine_us/variables/gov/states/or/tax/income/credits/wfhdc/or_wfhdc_income_category.py#L25-L28

Did I miss in the legal code the part about rounding the rate to the nearest three decimal digits?

If I didn't miss the language that says to do that in the legal code, then why not replace the last three lines of Python code with this one line?

```
return np.ceil(capped_fpg_rate * 10)
```
This single line of code seems to correspond more closely to the legal code, again assuming I haven't missed something.

**Comment by PavelMakarchuk** [comment]
@martinholmer I think you are right here, looking back at the legal code I do not see where it would be rounded.

I also removed the `capped_fpg_rate` from the code as this will be automatically checked by the `or_wfhdc_income_eligible` variable
