### ISSUE TITLE
Fix Ohio credit calculations

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3758]
Using the 0.637.4 version, the test case in issue #3750 is still failing.

In issue #3750, @PavelMakarchuk said:
> However, in the [test] case above, I believe the exemptions credit is calculated as expected. The $100 difference seems to results from a different place in the computation tree. Please see passing integration test in https://github.com/PolicyEngine/policyengine-us/pull/3753

When I look at the new integration test added in pull request #3753, I see that the added test is easier than the test included in #3750.   So, while the code can pass the easy test it still fails the harder test in #3750.

I suggest adding the original test from issue #3750.  When the code is fixed, PEUS will pass that harder test as well as the easier test added in PR #3753.

**Comment by PavelMakarchuk** [comment]
> Using the 0.637.4 version, the test case in issue #3750 is still failing.
> 
> In issue #3750, @PavelMakarchuk said:
> 
> > However, in the [test] case above, I believe the exemptions credit is calculated as expected. The $100 difference seems to results from a different place in the computation tree. Please see passing integration test in #3753
> 
> When I look at the new integration test added in pull request #3753, I see that the added test is easier than the test included in #3750. So, while the code can pass the easy test it still fails the harder test in #3750.
> 
> I suggest adding the original test from issue #3750. When the code is fixed, PEUS will pass that harder test as well as the easier test added in PR #3753.

@martinholmer I was confused by the title of the issue as I thought the the exemption credits were the assumed root cause and with them passing the income tax amount might have had to be changed due to a possible inaccuracy in the TaxSim model. 

I will take a look at all the credits and find the root of the $100 difference
