### ISSUE TITLE
Add the exemption amount to the Ohio senior citizen credit income calculation

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3771]
In the 0.638.0 version, the `oh_senior_citizen_credit` formula does not correspond to the cited [form reference](https://tax.ohio.gov/static/forms/ohio_individual/individual/2021/pit-it1040-booklet.pdf#page=20).

**Comment by PavelMakarchuk** [comment]
Should have double checked the rest of the calculation, added the exemption amount to reduce the AGI
