### ISSUE TITLE
Remove `capital_gains_excluded_from_taxable_income` from the rhode island property tax credit income sources

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3775]
I don't understand this list:

https://github.com/PolicyEngine/policyengine-us/blob/babd6ea6efa0553ebc460bc9de48f2a2ebf1b299/policyengine_us/parameters/gov/states/ri/tax/income/credits/property_tax/income_sources.yaml#L1-L13

Specifically, I don't understand why `capital_gains_excluded_from_taxable_income` is included in this list.   That variable is the sum of long-term capital gains and qualified dividends, which are not in the `taxable_income` variable, but they are in the `adjusted_gross_income` variable.  So, it seems as if Policyengine-US is double counting this kind of income when determining eligibility for the RI property tax credit.   Or am I missing something here?

**Comment by PavelMakarchuk** [comment]
> I don't understand this list:
> 
> https://github.com/PolicyEngine/policyengine-us/blob/babd6ea6efa0553ebc460bc9de48f2a2ebf1b299/policyengine_us/parameters/gov/states/ri/tax/income/credits/property_tax/income_sources.yaml#L1-L13
> 
> Specifically, I don't understand why `capital_gains_excluded_from_taxable_income` is included in this list. That variable is the sum of long-term capital gains and qualified dividends, which are not in the `taxable_income` variable, but they are in the `adjusted_gross_income` variable. So, it seems as if Policyengine-US is double counting this kind of income when determining eligibility for the RI property tax credit. Or am I missing something here?

Hello @martinholmer you are right, we are double counting those income sources. I have added an integration test for demonstration
