### ISSUE TITLE
Fix Oregon Federal Tax Liability Subtraction Calculation

### ISSUE THREAD

**Issue by Shinuing** [PolicyEngine/policyengine-us#3797]
Reference:
https://www.oregonlegislature.gov/bills_laws/ors/ors316.html
[2021](https://www.oregon.gov/dor/forms/FormsPubs/form-or-40-inst_101-040-1_2021.pdf#page=13)
[2022](https://www.oregon.gov/dor/forms/FormsPubs/form-or-40-inst_101-040-1_2022.pdf#page=13)

**Comment by MaxGhenis** [comment]
Can you be more specific?

**Comment by Shinuing** [comment]
> Can you be more specific?

We're not fully represent the 2021 and 2022 logic based on the [old structure](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/variables/gov/states/or/tax/income/subtractions/or_federal_tax_liability_subtraction.py). The highlight parts are not included in 2022. 

<img width="316" alt="Annotation 2024-02-07 113457" src="https://github.com/PolicyEngine/policyengine-us/assets/87620347/102d8cdd-bebc-4396-a4b3-b1bcd22a4407">

**Comment by MaxGhenis** [comment]
Is this only an issue for 2022 on then?

**Comment by Shinuing** [comment]
> Is this only an issue for 2022 on then?

Not sure if the old structure fully represents the 2021 logic as well. 
Pavel and I are looking into OR integration test variances and noticed that there may be some issues in `or_federal_tax_liability_subtraction`. We are trying to rewrite the structure and follow the tax form line by line so we can have either logic depends on the year.
