### ISSUE TITLE
Fix missing variable label errors

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3799]
**Configuration:**
```
(policyengine-us) policyengine-us% conda list yeng
# packages in environment at //Users/mrh/anaconda3/envs/policyengine-us:
#
# Name                    Version                   Build  Channel
policyengine-core         2.14.0                   pypi_0    pypi
policyengine-us           0.644.0                  pypi_0    pypi
```

**Result:** massive number of fatal error messages that prevent PEUS from executing.
The last one of the many errors is this:
```
policyengine_core/variables/variable.py", line 192, in __init__
    raise ValueError(
ValueError: Variable "county_fips" has no label
```

**Comment by MaxGhenis** [comment]
We've pinned policyengine-core below 2.14 so if you update you won't encounter the fatal messages

**Comment by martinholmer** [comment]
@MaxGhenis said:
> We've pinned `policyengine-core` below 2.14 so if you update you won't encounter the fatal messages

But you won't get any of the improved error checking in 2.14 either.
Isn't the point of 2.14 to find bugs?

**Comment by MaxGhenis** [comment]
@PavelMakarchuk is working on it in #3794
