### ISSUE TITLE
Arkansas income tax rate parameter discrepancy and low income tax parameter fix

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-us#3825]

**Comment by MaxGhenis** [comment]
Can you give more detail?

**Comment by PavelMakarchuk** [comment]
Need some to go through all the references:

A couple of adjustments, firstly:
The low income tax tables had 0 instead of .inf as a parameter value which was leading to 0 income tax for high income tax units

Secondly:
There is a difference between the way we have modeled the tax rates and the representation in the tax forms / tax tables:
We have adjusted the calcualtion of the tax rates to follow the[ tax bracket](https://www.dfa.arkansas.gov/images/uploads/incomeTaxOffice/TaxBrackets_2021.pdf) form which aligns the values with the tax tables:
![image](https://github.com/PolicyEngine/policyengine-us/assets/110687043/9477e5c7-d91a-43fc-8f4e-5ce547e64667)
This included creating a single amount reduction parameter to the rates. 
There are multiple legal code sources which point to separate calculations in different years 
[Source 1](https://codes.findlaw.com/ar/title-26-taxation/ar-code-sect-26-51-201/)
[Source 2](https://casetext.com/statute/arkansas-code-of-1987/title-26-taxation/subtitle-5-state-taxes/chapter-51-income-taxes/subchapter-2-imposition-of-tax/section-26-51-201-individuals-trusts-and-estates)

This seems to be the most accurate representation of the tax rate and mirrors the approach of TAXSIM
