### ISSUE TITLE
Distribute ASEC retirement contributions across types

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#3842]
See [2021 DOL data](https://www.dol.gov/sites/dolgov/files/ebsa/researchers/statistics/retirement-bulletins/private-pension-plan-bulletins-abstract-2021.xlsx) ([website](https://www.dol.gov/agencies/ebsa/researchers/statistics/retirement-bulletins/private-pension-plan)):

| Type of Plan          | Number of Plans | Total Participants (thousands) | Active Participants (thousands) | Total Assets (millions)  | Total Contributions (millions) | Total Benefits (millions)  |
|------------------------|-----------------|--------------------------------|------------------------------------|--------------------------|----------------------------------|-----------------------------|
| Total                  | 765,124         | 146,166                        | 99,544                             | $13,169,507              | $732,907                         | $1,055,371                  |
| Defined Benefit        | 46,388          | 31,235                         | 11,642                             | $3,670,366               | $76,032                          | $278,493                    |
| Cash Balance           | 24,624          | 9,561                          | 3,605                              | $1,326,323               | $19,040                          | $101,863                    |
| Other Defined Benefit  | 21,763          | 21,673                         | 8,037                              | $2,344,043               | $56,991                          | $176,630                    |
| Defined Contribution   | 718,736         | 114,931                        | 87,901                             | $9,499,141               | $656,875                         | $776,879                    |
| 401(k)-Type            | 644,671         | 96,255                         | 74,905                             | $8,020,485               | $582,681                         | $680,261                    |
| 403(b)                 | 20,270          | 9,901                          | 6,790                              | $779,135                 | $45,100                          | $49,527                     |
| Other Defined Contribution | 53,795      | 8,775                          | 6,207                              | $699,521                 | $29,094                          | $47,091                     |

We can split IRA contributions into 40% traditional, 60% Roth based on 2020 data from [ICI](https://www.ici.org/statistical-report/ret_23_q3) ([spreadsheet](https://www.ici.org/statistical-report/ret_23_q3_data.xls)): Table 11 shows $22.1 billion in traditional IRA contributions, and Table 12 shows $33.0 billion in Roth IRA contributions.

**Comment by PavelMakarchuk** [comment]
For the IRA contributions we take the $22.1 billion of traditional and $33 billion of Roth IRA contributions and increase it by the 4.7% inflation rate
