### ISSUE TITLE
Exclude negatives from bottom decile

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#3855]
Let's follow [TPC's approach](https://www.taxpolicycenter.org/sites/default/files/alfresco/publication-pdfs/412871-Measuring-Income-for-Distributional-Analysis.PDF):

>The income percentile classes used in this table are based on the income distribution for the entire population and contain an equal number of people not tax units. Tax units with negative adjusted gross income are excluded from their respective income class but are included in the totals.

That is, after our current decile assignment, add another step to reassign negatives to another decile, say -1.

**Comment by anth-volk** [comment]
Does this not skew their outputs away from impacts upon the very poor?

**Comment by MaxGhenis** [comment]
People with negative income are generally not what we think of as very poor. I can't find studies immediately but they often have high wealth and consumption, and only have negative income due to circumstances like business losses. That combined with the sign-flipping affecting https://github.com/PolicyEngine/policyengine-app/issues/1338 justify other analysts conventionally excluding them from distributional analyses.
