### ISSUE TITLE
Pension income should be included in MS AGI

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3949]
Pull request #3947, which "fixed" issue #3946, which itself has no description, removed taxable pension income from MS AGI.   Given the 2021 form, and the lack of any rationale for doing this, I'd say this is a bug.   Certainly, the testing results against TAXSIM35 have suffered a regression.

What was the rationale for doing this?

Here is the 2021 form which includes this type of income on line 45:

<img width="1263" alt="Screenshot 2024-02-19 at 3 44 04 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/e57bdc0f-7cda-4497-bc52-d7ae0d5229cc">

**Comment by PavelMakarchuk** [comment]
The question is mentioned in #3924 where the [instructions](https://www.dor.ms.gov/sites/default/files/Forms/Individual/80100211_0.pdf#page=11) and the [law](https://law.justia.com/codes/mississippi/2020/title-27/chapter-7/article-1/section-27-7-15/) seem to exclude certain pension income types.
![image](https://github.com/PolicyEngine/policyengine-us/assets/110687043/6ca88cd7-88ed-4e9a-9ebe-8c8ea6472026)

**Comment by martinholmer** [comment]
Where in that text do you read something that leads you to think that private federally-taxable pension income should not be included in MS AGI?

**Comment by PavelMakarchuk** [comment]
> Where in that text do you read something that leads you to think that private federally-taxable pension income should not be included in MS AGI?

The last sentence ".... retirement income from federal, state, and private retirement systems are exempt in total."

**Comment by martinholmer** [comment]
So, why do you think the rules (that you're quoting) for **NON-RESIDENT RETURNS** would apply to filling out the form (that I showed) for **RESIDENT RETURNS**?

**Comment by PavelMakarchuk** [comment]
> So, why do you think the rules (that you're quoting) for **NON-RESIDENT RETURNS** would apply to filling out the form (that I showed) for **RESIDENT RETURNS**?

That does explain this, will fix now! Thank you for explaining
