### ISSUE TITLE
Fix NY Income Tax formula 

### ISSUE THREAD

**Issue by hua7450** [PolicyEngine/policyengine-us#3981]
![image](https://github.com/PolicyEngine/policyengine-us/assets/113824411/6b587bf2-cb8c-4c53-85a2-36ccbc5b9494)
Fix the NY income tax according to the tax form, and see if it can pass the integration test.

**Comment by MaxGhenis** [comment]
What's incorrect with the calculation?

**Comment by hua7450** [comment]
Based on the tax form, it requires ny_taxable_income to calculate the income tax, but our current formula only uses refundable credits and nonrefundable credits.
