### ISSUE TITLE
2023 South Carolina Income Tax Rules

### ISSUE THREAD

**Issue by pxu12** [PolicyEngine/policyengine-us#3997]
Reference: [2023 Tax Form](https://dor.sc.gov/forms-site/Forms/IITPacket_2023.pdf)
[2023 Tax Form Instructions](https://dor.sc.gov/forms-site/Forms/SC1040inst_2023.pdf)

**Comment by MaxGhenis** [comment]
Could you please list the changes

**Comment by pxu12** [comment]
Hi Max @MaxGhenis , the changes are as follows:

1. Change in income tax rate brackets – For 2023, the top marginal Individual Income Tax rate changed to 6.4%, the thresholds changed to 3,330 and 16,680;
2. Increase in SC Dependent Exemption amount – The SC dependent exemption amount for 2023 is changed to $4,610;
3. Increase in Earned Income Tax Credit rate – For 2023, the EITC rate increases to 125% of the federal Earned Income Tax Credit allowed to the taxpayer；
4. Increase in Two Wage Earner Credit maximum amount – For 2023, the earned income threshold changed to $50,000.

**Comment by MaxGhenis** [comment]
Thanks that's helpful for reviewing #4004, except I don't see a dependent exemption either in the current code or PR

**Comment by pxu12** [comment]
Hi Max, I think it's called the young child deduction in the current code.
