### ISSUE TITLE
Alimony income is too high in the Enhanced CPS

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-us#4022]
Around $80bn compared to $20bn actual.

**Comment by MaxGhenis** [comment]
We're not targeting this right? What's the $20bn source?

**Comment by MaxGhenis** [comment]
Looks pretty good
<img width="1841" alt="image" src="https://github.com/PolicyEngine/policyengine-us/assets/6076111/08335c57-c107-4143-9498-cf24ee5297a4">
