### ISSUE TITLE
2023 Wisconsin  Second Tax Bracket Expansion

### ISSUE THREAD

**Issue by RileyAK** [PolicyEngine/policyengine-us#4026]
Expand the second-lowest tax bracket from $19,000 to $150,000.
[ Source](https://www.wispolitics.com/2024/senate-sends-2-1b-gop-tax-package-to-evers/)

Bill text: https://pluralpolicy.com/app/legislative-tracking/bill/details/state-wi-2023-ab1020/2321417

Additional Info: https://docs.google.com/document/d/1y-Hq4CYhmtDs0MRWHE2TzCy6DuWWbsSRX6rWqg7CEPs/edit?usp=sharing

**Comment by PavelMakarchuk** [comment]
We can model this in the WebApp
