### ISSUE TITLE
2023 Wisconsin Retirees' Income Exemption

### ISSUE THREAD

**Issue by RileyAK** [PolicyEngine/policyengine-us#4027]
Exempt up to $75,000 of retirees' income for single filers and $150,000 for married joint filers.

Media Source: (https://apnews.com/article/wisconsin-republicans-tax-cut-surplus-veto-2d84e8c72657a4b1aa79b20e8d50e4a9)
Bill text: https://pluralpolicy.com/app/legislative-tracking/bill/details/state-wi-2023-ab1021/2321764
Additional Info: https://docs.google.com/document/d/1y-Hq4CYhmtDs0MRWHE2TzCy6DuWWbsSRX6rWqg7CEPs/edit?usp=sharing

**Comment by MaxGhenis** [comment]
Was this enacted? If not please add the `reform` label.

**Comment by PavelMakarchuk** [comment]
Dont need a reform as we can modify all parameters accordingly in the app
