### ISSUE TITLE
Remove CPS_2023

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#4032]
#4030 will remove EnhancedCPS_2023 in favor of EnhancedCPS_2022. Let's do the same for CPS_2023, reflecting a dataset's survey year as its name.

**Comment by MaxGhenis** [comment]
Here: 

https://github.com/PolicyEngine/policyengine-us/blob/cc1b4b134f51429a2ebde45574437677c43579ba/policyengine_us/data/datasets/cps/cps.py#L561

@nikhilwoodruff did you keep this in #4030 for backwards compatibility?

**Comment by nikhilwoodruff** [comment]
Yes
