### ISSUE TITLE
Fix Minnesota Working Family Credit eligibility formula

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#4036]
In April 2023, the Minnesota state income tax was added by the merge of pull request #2066, which was authored by @martinholmer.  At that time, the Python code passed 900,000 TAXSIM35-based integration tests.

However, in a recent email, Daniel Feenberg, the author of TAXSIM35, has kindly provided some corrections to TAXSIM35 that he has discovered over the past year in his own testing against commercial tax-preparation software.

It turns out that both the Minnesota Policyengine-US code and the year-ago version of TAXSIM35 had made the same mistake: omitting the property income eligibility rules for the Working Family Credit, which are the same as for the federal EITC.

<img width="818" alt="Screenshot 2024-02-29 at 10 24 08 AM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/930afae2-fe54-4cfe-a3bc-1af5d64c398e">

**Comment by MaxGhenis** [comment]
For posterity, the legal code also cites the federal law for matters including the investment income limit.

>To receive a credit, a taxpayer must be eligible for a credit under section 32 of the Internal Revenue Code...

https://www.revisor.mn.gov/statutes/cite/290.0671
