### ISSUE TITLE
SNAP uprating bug

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#4121]
After successfully using the 0.688.1 version since March 2nd, I upgraded on March 9th to the 0.695.1 version, but found it unusable.   I get the following fatal error message as Policyengine crashes:

```
File "policyengine_core/parameters/operations/uprate_parameters.py", line 89:
   raise ValueError(
ValueError: Failed to uprate using gov.usda.snap.uprating at
2000-01-01 for
gov.usda.snap.income.deductions.excess_medical_expense.standard.AP at
2020-10-01 because the uprating parameter is not defined at
2000-01-01.
```

**Comment by martinholmer** [comment]
@MaxGhenis said:
> Could you try updating policyengine-core?

If that is the issue, why doesn't Policyengine-US **require** the newer version of Policyengine-Core?

**Comment by MaxGhenis** [comment]
Yep I'll change the issue to bump it if that fixes for you
