### ISSUE TITLE
CPS 2022 child poverty rate is too low

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-us#4146]
[Notebook 1](https://gist.github.com/nikhilwoodruff/c86bceb1b9b84eab107675e4852d8a41)

[Notebook 2](https://gist.github.com/nikhilwoodruff/8c9ca57455af3ce872d0195d5c3f8803)

Unclear why the child poverty rate is 4.7% in 2022. The values between 2022 and 23 are not substantially different, the targets are mostly similar (no deviations of more than 15%), but the share of weight from PUF records is ~10% in 23 and 24 but ~30% in 22.

**Comment by MaxGhenis** [comment]
I moved this to https://github.com/PolicyEngine/policyengine-us/discussions/3637 - let's continue the conversation there
