### ISSUE TITLE
Add 2023 Indiana Tax Rules

### ISSUE THREAD

**Issue by XZ-mabel** [PolicyEngine/policyengine-us#4175]
2023 Income Tax Form Instructions: https://www.in.gov/dor/tax-forms/2023-individual-income-tax-forms/
(All tax parameters haven't been updated except for Indiana tax rate for 2023)

**Comment by MaxGhenis** [comment]
Thanks - could you please label these issues with the year and state?

**Comment by XZ-mabel** [comment]
I can't add labels to issues. 
<img width="349" alt="github_screenshot" src="https://github.com/PolicyEngine/policyengine-us/assets/131919825/aa368525-e021-41ee-a73b-8d1aaa18fb83">

**Comment by MaxGhenis** [comment]
Could you try again after accepting the triage access invite I just sent you?

**Comment by XZ-mabel** [comment]
I can add labels now
