### ISSUE TITLE
Add 2023 Minnesota Tax Rules

### ISSUE THREAD

**Issue by XZ-mabel** [PolicyEngine/policyengine-us#4184]
2023 Income Tax Form Instructions: https://www.revenue.state.mn.us/sites/default/files/2024-02/m1-inst-23.pdf

**Comment by shuyu7zhan** [comment]
Summary: 2023 MN tax rules updates
1. AMT - fractional excess income threshold
2. Credit - marriage - max amount
3. Credit - marriage - min taxable income
4. Credit - WFC - phase in - max earnings for phasein rate
5. Credit - WFC - phase out - threshold - joint filers/other filers
6. Deductions - agi threshold
7. Deductions - standard - base/extra
8. Exemptions - agi threshold
9. Rates - head/joint/separate/single/widow
10. Subtractions - social security - subtraction income amount

**Comment by shuyu7zhan** [comment]
Tax code issue
credits - not found
deductions/exemptions - value difference in code/form
subtractions - elder/disab - net agi fraction
