### ISSUE TITLE
Add 2023 Ohio Tax Rules

### ISSUE THREAD

**Issue by XZ-mabel** [PolicyEngine/policyengine-us#4194]
2023 Income Tax Form Instructions: https://dam.assets.ohio.gov/image/upload/tax.ohio.gov/forms/ohio_individual/individual/2023/it1040-sd100-instructionbooklet.pdf

**Comment by hua7450** [comment]
Changes: 
2022, 2023 and 2024 Ohio income tax bracket ([legal code](https://codes.ohio.gov/ohio-revised-code/section-5747.02))
