### ISSUE TITLE
Add 2023 Utah Tax Rules

### ISSUE THREAD

**Issue by XZ-mabel** [PolicyEngine/policyengine-us#4198]
2023 Income Tax Form Instructions: https://tax.utah.gov/forms/current/tc-40inst.pdf

**Comment by PavelMakarchuk** [comment]
- Added the references of 2023 Tax Form
- Updated the 2023 values of ss_benifits phase-out threshold
- Updated the 2023 values of taxpayer credit personal exemption
- Updated the 2023 values of taxpayer credit phase-out threshold
