### ISSUE TITLE
Add 2023 Vermont Tax Rules

### ISSUE THREAD

**Issue by XZ-mabel** [PolicyEngine/policyengine-us#4200]
2023 Income Tax Form Instructions: https://tax.vermont.gov/sites/tax/files/documents/Income-Booklet-2023.pdf

**Comment by Kiki-67** [comment]
2023 updates:
1. Additional standard deduction: 1,015 -> 1,150
2. standard deductions base: JOINT ->  14_050, HEAD_OF_HOUSEHOLD -> 10_550, SURVIVING_SPOUSE -> 14_050, SINGLE -> 7_000, SEPARATE -> 7_000
3. personal exemption amount -> 4500 -> 4850
4. tax income bracket for all filling status
