### ISSUE TITLE
Colorado SNAP updates 

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-us#4246]
Later this year, the SNAP utility calculations are changing in a way that will increase a HH's utility allowance and thereby decrease countable income. Consistent with federal regulations, if a state agency elects to use a standard utility allowance, that allowance must be made available to HHs that received a payment under LEAP or an other similar energy assistance program.
Starting October 1, CDHS will issue EBT credits to HHs ($20 to help cover utilities + $1 for ATM costs) that didn't get LEAP in the prior 12 months. All eligible SNAP households will get this amount regardless of income, expenses, or HH size. The result is that all Colorado HHs will get the HCUA. The goal is to give HHs the highest possible utility deduction.
The rules will go into effect by August 1 with implementation October 1 (coinciding with when SNAP updates its income / benefits amounts). Details are in this [deck](https://docs.google.com/presentation/d/1LjJz-Ycx1-acefOcEJNtMxVRGfYMLEQgbRxGtEeyYgI/edit#slide=id.g2ab7e3e92af_0_134).

**Comment by CalebPena** [comment]
@PavelMakarchuk I am going to work on this ticket, but I have a couple of questions.

Is the HCUA the same as the SUA?
Do you want to implement this by updating the `snap_utility_allowance_type` variable?
