### ISSUE TITLE
Ohio Joint Filing Credit calculation error

### ISSUE THREAD

**Issue by ksteffenson** [PolicyEngine/policyengine-us#4348]
I completed my Ohio State Individual Tax form at https://myportal.tax.ohio.gov/.  When it was completed, the tax due was reduced by $200. The summary revealed that even though I had selected "No" in response to "Do you have any nonrefundable credits", the software had added in the Joint Filing Credit.  The issue is that the instructions and the law clearly state that the $500 qualifying income for my spouse can't include interest, and that is her only source of income.  Therefore the web page is incorrectly determining the qualification for the Joint Filing Credit.  Perhaps this issue is related to Fix Ohio joint filing credit calculation (https://github.com/PolicyEngine/policyengine-us/pull/3685)?

**Comment by MaxGhenis** [comment]
Hi @ksteffenson - could you share how you're accessing PolicyEngine? We don't ask the question "Do you have any nonrefundable credits"

**Comment by ksteffenson** [comment]
Google search brought me to the issue (https://github.com/PolicyEngine/policyengine-us/pull/3685) - so it appeared that PolicyEngine was running on the Ohio Tax Portal ( https://myportal.tax.ohio.gov/) in some way.  The help line hasn't been very responsive, so I thought I'd try your git for answers/solutions.

**Comment by MaxGhenis** [comment]
Thanks for clarifying - PolicyEngine does not currently run on the Ohio Tax Portal. Best of luck finding a solution!
