### ISSUE TITLE
Question about allocating Delaware itemized deductions

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#4363]
The code in the 0.727.1 version is as follows:

https://github.com/PolicyEngine/policyengine-us/blob/db2a86c58739e44fd58d086bfe480085ab53df55/policyengine_us/variables/gov/states/de/tax/income/deductions/itemized/de_itemized_deductions_indv.py#L4-L26

Where exactly in the legislative language or form instructions does it say to allocate itemized deductions between married-filing-separately spouses in proportion to DE AGI?

**Comment by PavelMakarchuk** [comment]
We read it in the [instructions](https://revenuefiles.delaware.gov/2021/PIT-RES_TY21_2021-01_Instructions.pdf#page=7) here:

![image](https://github.com/PolicyEngine/policyengine-us/assets/110687043/c8dac024-b23f-4a3b-87e9-6c1f3efd4f12)

[RSA](https://revenuefiles.delaware.gov/2021/TY21_PIT-RSA_2021-01_PaperInteractive.pdf) 
![image](https://github.com/PolicyEngine/policyengine-us/assets/110687043/ac4fa81b-4f6c-45da-9256-973303f6408f)

Let me know if you think that we misinterpret this language

**Comment by MaxGhenis** [comment]
Should we allocate by DE AGI or gross income?

**Comment by martinholmer** [comment]
@PavelMakarchuk,  Thanks for the citation in issue #4363; I missed that form language.

@MaxGhenis asked:
> Should we allocate by DE AGI or gross income?

Good question.  The form language is not very clear, but it does suggest that DE AGI is not appropriate (because of the large pension exclusion).

How about using the `de_pre_exclusions_agi` variable to allocate itemized deductions among married couples filing separately?   The whole DE income tabulation process starts with federal AGI, so it seems unlikely that the phrase "household income" means gross income as defined in PEUS..

**Comment by martinholmer** [comment]
@MaxGhenis, Now I see that `de_pre_exclusions_agi` is misnamed because it includes the pension subtractions.   So, I think the best approach is to allocate DE itemized deductions using **federal AGI**, which is where DE begins its income calculations.

**Comment by PavelMakarchuk** [comment]
> @MaxGhenis, Now I see that `de_pre_exclusions_agi` is misnamed because it includes the pension subtractions. So, I think the best approach is to allocate DE itemized deductions using **federal AGI**, which is where DE begins its income calculations.

I agree, will make the adjustment, thank you!

**Comment by MaxGhenis** [comment]
For completeness, it doesn't look like the legal code defines this: https://delcode.delaware.gov/title30/c011/sc02/index.html
