### ISSUE TITLE
Estate tax

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#4415]
As a benchmark of how to model it, @kpomerleau said he assigns it to the top 1% in proportion to household income

See also https://www.jec.senate.gov/public/_cache/files/bc9424c1-8897-4dbd-b14c-a17c9c5380a3/costs-and-consequences-of-the-federal-estate-tax-july-25-2012.pdf

**Comment by PavelMakarchuk** [comment]
[Legal code](https://www.law.cornell.edu/uscode/text/26/subtitle-B/chapter-11/subchapter-A)
