### ISSUE TITLE
SNAP BBCE Asset Limit Removed in MI

### ISSUE THREAD

**Issue by benmolin** [PolicyEngine/policyengine-us#4459]
# File to Update

https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/parameters/gov/hhs/tanf/non_cash/asset_limit.yaml

# MI

MI: .inf

https://www.michigan.gov/mdhhs/assistance-programs/food/eligibility

"Effective March 1, 2024, most Food Assistance Program (FAP) groups do not have an asset limit."

**Comment by PavelMakarchuk** [comment]
Thank you @benmolin for filing!
