### ISSUE TITLE
Refactor Louisiana exempt income formula

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#4462]
The formula for the `la_agi_exempt_income` variable is too long and has dubious variable names, making it difficult to tell whether or not the logic in the formula is correct or not.   The formula needs to be broken up making several of the formula's local variables into global variables.

An example of the confusion is this local variable:

https://github.com/PolicyEngine/policyengine-us/blob/cf9237a7c8e14674ebd2e38e50f2afeff24362c0/policyengine_us/variables/gov/states/la/tax/income/exempt_income/la_agi_exempt_income.py#L30-L33

.

I don't understand how `AGI-itemized_deduction-income_tax_before_credits` can be an income tax variable.   Perhaps it is, but the logic is not transparent.

**Comment by PavelMakarchuk** [comment]
@martinholmer thank you for pointing it out. I got confused with Louisiana commonly using "federal income tax" to describe their federal income tax **deduction** - fixed
