### ISSUE TITLE
New Minnesota 2023 working family credit logic

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-us#4520]
The program was adjusted in [2023](https://www.revisor.mn.gov/statutes/2023/cite/290.0671) and needs structural logic changes

[2023 tax form](https://www.revenue.state.mn.us/sites/default/files/2024-01/m1cwfc-23_1.pdf)

[2021 form](https://www.revisor.mn.gov/statutes/2021/cite/290.0671)

[Legal code](https://www.revisor.mn.gov/statutes/cite/290.0675#stat.290.0675.3)

**Comment by shuyu7zhan** [comment]
@PavelMakarchuk  plz check the WFC "tree", let me know if all good and I can work on the variable

Calculation Summary:
WFC = min (earned income, upper limit) * 4% + QOC credit - (earned income - phase out threshold) * 9%

Parameters:
1. upper limit ($8750)
2. WFC rate (4%)
3. Qualified Older Children (QOC) age: 18 to 23
4. QOC credit: $915/2100/2500 for 1/2/more children
5. phase out threshold: $35000 for joint filing and $29500 for others
6. phase out rate (9%)

**Comment by PavelMakarchuk** [comment]
> @PavelMakarchuk plz check the WFC "tree", let me know if all good and I can work on the variable
> 
> Calculation Summary: WFC = min (earned income, upper limit) * 4% + QOC credit - (earned income - phase out threshold) * 9%
> 
> Parameters:
> 
> 1. upper limit ($8750)
> 2. WFC rate (4%)
> 3. Qualified Older Children (QOC) age: 18 to 23
> 4. QOC credit: $915/2100/2500 for 1/2/more children
> 5. phase out threshold: $35000 for joint filing and $29500 for others
> 6. phase out rate (9%)

Looks good to me, what do we already have and what do we need to add?

**Comment by shuyu7zhan** [comment]
> > @PavelMakarchuk plz check the WFC "tree", let me know if all good and I can work on the variable
> > Calculation Summary: WFC = min (earned income, upper limit) * 4% + QOC credit - (earned income - phase out threshold) * 9%
> > Parameters:
> > 
> > 1. upper limit ($8750)
> > 2. WFC rate (4%)
> > 3. Qualified Older Children (QOC) age: 18 to 23
> > 4. QOC credit: $915/2100/2500 for 1/2/more children
> > 5. phase out threshold: $35000 for joint filing and $29500 for others
> > 6. phase out rate (9%)
> 
> Looks good to me, what do we already have and what do we need to add?

every parameter I list above, and rewrite mn_wfc.py

**Comment by PavelMakarchuk** [comment]
> > > @PavelMakarchuk plz check the WFC "tree", let me know if all good and I can work on the variable
> > > Calculation Summary: WFC = min (earned income, upper limit) * 4% + QOC credit - (earned income - phase out threshold) * 9%
> > > Parameters:
> > > 
> > > 1. upper limit ($8750)
> > > 2. WFC rate (4%)
> > > 3. Qualified Older Children (QOC) age: 18 to 23
> > > 4. QOC credit: $915/2100/2500 for 1/2/more children
> > > 5. phase out threshold: $35000 for joint filing and $29500 for others
> > > 6. phase out rate (9%)
> > 
> > 
> > Looks good to me, what do we already have and what do we need to add?
> 
> need to add every parameter I list above, and rewrite mn_wfc.py

LGTM then, we can get started
