### ISSUE TITLE
Add CBO lower and higher elasticity options

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#4568]
Currently we only let users pre-populate central elasticities from [CBO (2012)](https://www.cbo.gov/sites/default/files/112th-congress-2011-2012/reports/43674-laborsupplyfiscalpolicy.pdf#page=4):

<img width="686" alt="image" src="https://github.com/PolicyEngine/policyengine-us/assets/6076111/d0077919-0658-40d2-8b93-b854cdf3bd91">

Though https://github.com/PolicyEngine/policyengine-app/issues/1755 may supersede this, since we could stack them as reforms.

**Comment by PavelMakarchuk** [comment]
@SirMalamute

**Comment by MaxGhenis** [comment]
No longer a code issue, we just need to create reforms for them
