### ISSUE TITLE
Remove unneeded personal_interest_expense variable

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#4590]
The `personal_interest_expense` variable is not used in any tax or benefit or other calculations, and is, therefore, unnecessary.

**Comment by MaxGhenis** [comment]
`personal_interest_expense` is used in `non_mortgage_interest` which eventually feeds into `interest_deduction`

**Comment by martinholmer** [comment]
@MaxGhenis said:
 > `personal_interest_expense` is used in `non_mortgage_interest` which eventually feeds into `interest_deduction`.   @PavelMakarchuk added it in https://github.com/PolicyEngine/policyengine-us/pull/3507.

But why was it added in the first place?   As far as I can see, there is no reason to add it.
`personal_interest_expense` is not a deductible expense.

If we include the extraneous `personal_interest_expense` variable, which is not used **directly** in any tax or benefit calculations, why don't we go ahead and add variables like `waygu_beef_expenses`?

**Comment by martinholmer** [comment]
The inclusion of `personal_interest_expense` in the 'interest_expense` variable seems to be causing confusion.   Person interest expense (such as credit card interest) is not deductible under federal or state income tax laws, as far as I know.  So, use `interest_expense` to specify deductible interest is incorrect.

Both `mortgage_interest` and `investment_interest_expense` are definitely deductible.

**Comment by martinholmer** [comment]
IRS help topic 505, [Interest expense](https://www.irs.gov/taxtopics/tc505#:~:text=Types%20of%20interest%20not%20deductible,interest%20incurred%20for%20personal%20expenses) includes the following text:

> Types of interest not deductible include **personal interest**, such as:
>
> * Interest paid on a loan to purchase a car for personal use.
> * Credit card and installment interest incurred for personal expenses.
> * Points (if you're a seller), service charges, credit investigation fees, and interest relating to tax-exempt income, such as interest to purchase or carry tax-exempt securities.

So, @PavelMakarchuk, why did you add the `personal_interest_expense` variable in #3507?
