### ISSUE TITLE
Bug affecting all pull requests

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#4592]
All recent PRs are failing with this error (that is unrelated to the substance of the PR):

<img width="1262" alt="Screenshot 2024-06-02 at 2 38 57 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/76750d2d-7ccd-44c7-b083-970066da3192">

**Comment by MaxGhenis** [comment]
Duplicate of #4582
