### ISSUE TITLE
Illinois 2024 Child Tax Credit

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-us#4596]
[Reference](https://www.niskanencenter.org/proposed-illinois-child-tax-credit-is-a-step-in-the-right-direction/)

**Comment by MaxGhenis** [comment]
Gov Pritzker expected to sign into law https://wgntv.com/news/illinois/illinois-house-passes-53b-state-budget-sent-to-gov-pritzker/
