### ISSUE TITLE
Refactor the `social_security_excess` in the `refundable_ctc` calculation

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-us#4612]
The [following code](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/variables/gov/irs/credits/ctc/refundable/refundable_ctc.py#L50-L64) is duplicated multiple times
We currently use the computation in the [Colorado refundable CTC](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/variables/gov/states/co/tax/income/credits/ctc/federal_ctc/co_refundable_ctc.py#L43-L59) as well as adding it in the New York additional CTC computation in #4451

**Comment by MaxGhenis** [comment]
let's also make those constants parameters
