### ISSUE TITLE
Move start date for Colorado Family Affordability Credit parameters to 2024

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#4630]
Currently starts in 2020 but it started in 2024

https://policyengine.org/us/policy?focus=gov.states.co.tax.income.credits.family_affordability.amount&reform=57479&region=us&timePeriod=2024&baseline=2

**Comment by PavelMakarchuk** [comment]
This seems to be an app issue, the [parameter](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/parameters/gov/states/co/tax/income/credits/family_affordability/amount.yaml) is encoded for 2024

![image](https://github.com/PolicyEngine/policyengine-us/assets/110687043/294a7bd1-e526-4149-a799-35f5e2bcc9d2)

**Comment by MaxGhenis** [comment]
Thanks @PavelMakarchuk - filed https://github.com/PolicyEngine/policyengine-app/issues/1867
