### ISSUE TITLE
NY Geothermal Energy System Credit

### ISSUE THREAD

**Issue by fuyukitn** [PolicyEngine/policyengine-us#4643]
https://www.tax.ny.gov/pit/credits/geothermal-energy-system-credit.htm
https://www.tax.ny.gov/forms/current-forms/it/it267i.htm

# Eligibility
You are entitled to claim this credit if:
- you purchased geothermal energy system equipment, **or**
- entered into a written agreement for the lease of geothermal energy system equipment,             

**and**

- the New York residential property where the system was installed was your residence at the time the system was placed in service, **and**
- the property was not rented at any time during the taxable year in which the credit is claimed.

**Note**: The geothermal energy system **must** use solar thermal energy stored in the ground or bodies of water to produce heat for residential use, commonly known as a ground source heat pump. 

# Benefits
- The credit is equal to 25% of your qualified geothermal energy system equipment expenditures and is limited to $5,000.
- The geothermal energy system credit is not refundable. However, any credit amount in excess of the tax due can be carried over for up to five years.

**Note**: You may **only** claim the geothermal energy system credit for one system in a tax year.

# Variable to add: name

# Variable to amend: name

# Parameter to add: name

# Parameter to amend: name

**Comment by jpvelez** [comment]
Leases for geothermal, and geothermal installed at condos, have specialized logic. Do we want to implement that, @MaxGhenis?
