### ISSUE TITLE
state snap minimum benefits

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-us#4713]
[MD:](https://mgaleg.maryland.gov/2024RS/fnotes/bil_0006/hb0666.pdf) Any member over 62 in the household: minimum benefit brought up to $40.
[NM](https://casetext.com/regulation/new-mexico-administrative-code/title-8-social-services/chapter-139-food-stamp-program/part-502-state-food-stamp-supplement/section-81395028-state-snap-supplement-benefits): All members over 60 or with a disability without earned income: minimum benefit amount brought up to a number established by the HSD secretary ([$32](https://www.nmlegis.gov/Entity/LFC/Documents/Session_Publications/Post_Session_Fiscal_Reviews/2024%20Post%20Session%20web.pdf#page=27))

Not sure if NM is for HH size of 1 and 2 only. Also not sure if above the minimum would be brought to $32 (ie $23-> $32 but does $26 go to $32? I read it as no)

https://casetext.com/regulation/new-mexico-administrative-code/title-8-social-services/chapter-139-food-stamp-program/part-502-state-food-stamp-supplement/section-81395028-state-snap-supplement-benefits

[HI $250 proposal](https://www.billtrack50.com/billdetail/1538639) -- not sure what it would have looked like for over 200% FPL: 

-

MD and NM are being updated in October.

**Comment by hua7450** [comment]
> [NM](https://casetext.com/regulation/new-mexico-administrative-code/title-8-social-services/chapter-139-food-stamp-program/part-502-state-food-stamp-supplement/section-81395028-state-snap-supplement-benefits): All members over 60 or with a disability without earned income: minimum benefit amount brought up to a number established by the HSD secretary ([$32](https://www.nmlegis.gov/Entity/LFC/Documents/Session_Publications/Post_Session_Fiscal_Reviews/2024%20Post%20Session%20web.pdf#page=27))

I find a [file](https://www.nmlegis.gov/handouts/ALFC%20121223%20Item%209%20-%20FINAL%20LFC%20HCA%20FY25%20Budget%20Request23_12.pdf#page=64) that is related to this source, which implies that the minimum allotment for seniors with disabilities is $32, but I could not find legal code that support it. Besides, the [chart](https://www.hca.nm.gov/wp-content/uploads/FPG-Cards-FY-2024-10.01.23-to-09.30.2024-English-1.pdf) we found from the HCA website states the minimum allotment is $23, which is the same as the federal's. This aligns the [legal code](https://casetext.com/regulation/new-mexico-administrative-code/title-8-social-services/chapter-139-food-stamp-program/part-502-state-food-stamp-supplement/section-81395028-state-snap-supplement-benefits):
![image](https://github.com/user-attachments/assets/cf4bcb40-1e4d-4dbd-8a66-7472050d7e14)
