### ISSUE TITLE
VITA eligibility

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#4720]
https://www.irs.gov/individuals/free-tax-return-preparation-for-qualifying-taxpayers

> VITA sites offer free tax help to people who need assistance in preparing their own tax returns, including:
> 
> People who generally make $64,000 or less
> Persons with disabilities; and
> Limited English-speaking taxpayers
> In addition to VITA, the TCE program offers free tax help, particularly for those who are 60 years of age and older, specializing in questions about pensions and retirement-related issues unique to seniors.

I don't think there's explicit legal/regulatory backing for these. SingleStop models it.

**Comment by PavelMakarchuk** [comment]
Would we include this in the computation tree in any form? E.g. should this be displayed in the web app when household information is entered?

**Comment by MaxGhenis** [comment]
Let's start with eligibility disconnected from the net income tree. Filed #4721 for the value.
