### ISSUE TITLE
Fix erroneous federal AMT calculation

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#4775]
The following simple 2022 test case illustrates a major flaw in the federal AMT calculations that can cause PolicyEngine-US to generate federal income tax amounts that are many thousands of dollars larger than the correct amounts.  This flaw causes errors as far back at 2018 (see #4769).

The characterization of this situation as a bug seems sensible because online [TAXSIM-35](https://taxsim.nber.org/taxsim35) and [Tax-Calculator 4.2.0](https://github.com/PSLmodels/Tax-Calculator) and 2022 [Turbo Tax](https://turbotax.intuit.com) are all in agreement that this test case has a zero AMT.   PolicyEngine-US 1.28.0, however, generates a federal AMT amount equal to $7,538.50.

That this bug exists is not particularly surprising because the developers of the `alternative_minimum_tax` formula did not specify any unit tests for it.   (At least, I can't find any tests when doing a recursive grep operation over the source code tree.).  Also, the 2022 federal income testing done in issue #1773 never considered test cases with more than $10K in qualified dividends or more than $10K in long-term capital gains.

First, I show the YAML file containing the test case.  Then I show several screenshots from Turbo Tax processing a make-believe person like the test case.

**The YAML test case:**
```
- name: Single Texan with no children, $150K wages, $50K QDIV, $50K LTCG
  absolute_error_margin: 0.01
  period: 2022
  input:
    people:
      person1:
        age: 50
        employment_income: 150_000
        qualified_dividend_income: 50_000
        long_term_capital_gains: 50_000
    spm_units:
      spm_unit:
        members: [person1]
    tax_units:
      tax_unit:
        members: [person1]
    households:
      household:
        members: [person1]
        state_code: TX
  output:
    # expected output from online TAXSIM-35
    # which is at: https://taxsim.nber.org/taxsim35/
    #
    adjusted_gross_income: 250_000
    taxable_income: 237_050
    net_investment_income_tax: 1_900
    income_tax: 43_627.50

##############################################################################
# ABOVE TEST IS IN A FILE NAMED case22.yaml
# TEST ENVIRONMENT:
#   % pip list | grep policyengine
#   policyengine-core             2.21.8
#   policyengine-us               1.28.0
# RESULTS FROM RUNNING THIS TEST ARE AS FOLLOWS:
#
#=============================== FAILURES ===================================
#_____________________________ test session _________________________________
#/Users/mrh/work/.../case22.yaml:
#  Test 'Single Texan with no children, $150K wages, $50K QDIV, $50K LTCG':
#    income_tax@2022: [51166.] differs from 43627.5
#                     with an absolute margin [7538.5] > 0.01
#======================= short test summary info ============================
#FAILED case22.yaml::
#========================== 1 failed in 3.19s ===============================
#Trace output is in file: case22.trace
#% grep alternative_minimum_tax case22.trace
#         alternative_minimum_tax<2022, (default)> = [7538.5]
# So, the income tax difference is caused solely by the AMT difference.
```

**2022 Turbo Tax screenshots:**

<img width="495" alt="Screenshot 2024-07-23 at 11 38 10 AM" src="https://github.com/user-attachments/assets/32ad9bce-f1d1-4419-b6d4-dbb32bfb2ccd">

.

<img width="606" alt="Screenshot 2024-07-23 at 11 46 40 AM" src="https://github.com/user-attachments/assets/7e9b8112-54b0-4211-9289-b939e63d5c92">

.

And finally, federal Form 6251:

<img width="613" alt="Screenshot 2024-07-23 at 11 52 24 AM" src="https://github.com/user-attachments/assets/fca7af74-199c-474e-8ab2-dcd32994ca6b">

<img width="606" alt="Screenshot 2024-07-23 at 11 52 45 AM" src="https://github.com/user-attachments/assets/ffc61099-7fba-4fdd-afb8-9edc4482853c">

<img width="607" alt="Screenshot 2024-07-23 at 11 53 23 AM" src="https://github.com/user-attachments/assets/ba603d28-cfb3-4f13-96c3-1d9645ded1d6">

<img width="607" alt="Screenshot 2024-07-23 at 11 54 18 AM" src="https://github.com/user-attachments/assets/feb2fad5-8be0-42fb-962e-b807ded93509">

**Comment by MaxGhenis** [comment]
Does this relate to https://github.com/PSLmodels/Tax-Calculator/pull/2785?

**Comment by martinholmer** [comment]
@MaxGhenis asked in PR #4775:
> Does this relate to https://github.com/PSLmodels/Tax-Calculator/pull/2785?

No.

**Comment by PavelMakarchuk** [comment]
Thank you @martinholmer for filing -

The issue here is that we do not consider capital gains taxes when computing the final AMT amount in Part II Line 10 - will fix now

**Comment by martinholmer** [comment]
@PavelMakarchuk said in issue #4775:
> The issue here is that we do not consider capital gains taxes when computing the final AMT amount in Part II Line 10 - will fix now.

Good that you've identified the problem in the code.

**Comment by MaxGhenis** [comment]
This reform simulates repealing AMT by raising the exemption to $1T: https://policyengine.org/us/policy?focus=policyOutput.policyBreakdown&reform=62899&region=enhanced_us&timePeriod=2024&baseline=2

Before merging #4815, this produced a $153 billion cost in 2024; now it's $0.8 billion.

Do we now need to adjust other parameters to simulate AMT repeal? We could also try neutralizing from a notebook.

Other reforms still work correctly, e.g. [TRAFWA](https://policyengine.org/us/policy?focus=policyOutput.policyBreakdown&reform=54413&region=enhanced_us&timePeriod=2024&baseline=2).

**Comment by PavelMakarchuk** [comment]
I wonder if the previous effect was correct - the easiest way it to set the rate to 0 (both brackets). This would produce an [impact](https://policyengine.org/us/policy?reform=63010&focus=policyOutput.policyBreakdown&region=us&timePeriod=2024&baseline=2) of $1.4 billion - which is what we get if we repeal the AMT as a [structural reform](https://github.com/PolicyEngine/analysis-notebooks/blob/main/us/irs/income/amt/repeal_amt.ipynb)

**Comment by MaxGhenis** [comment]
[TPC projects that AMT raises $6.3 billion in 2023](https://www.taxpolicycenter.org/briefing-book/how-much-revenue-does-amt-raise)

I would expect our projection to be lower as we haven't fully incorporated important deductions like the property tax component of SALT and charitable deductions. So $1.4 billion seems OK.

Do you know why an infinite exemption differs from zeroing out the rates though?

**Comment by PavelMakarchuk** [comment]
> [TPC projects that AMT raises $6.3 billion in 2023](https://www.taxpolicycenter.org/briefing-book/how-much-revenue-does-amt-raise)
> 
> I would expect our projection to be lower as we haven't fully incorporated important deductions like the property tax component of SALT and charitable deductions. So $1.4 billion seems OK.
> 
> Do you know why an infinite exemption differs from zeroing out the rates though?

There is a cap on the exemption amounts for filers who are below 18
