### ISSUE TITLE
Denver Property Tax Relief

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#4782]
https://github.com/Gary-Community-Ventures/benefits-api/pull/461

**Comment by hua7450** [comment]
[Program rule](https://denvergov.org/files/content/public/v/37/government/agencies-departments-offices/agencies-departments-offices-directory/denver-human-services/be-supported/additional-assistance/property-tax-relief/denver-property-tax-relief-program-year-2021-rules.pdf)
[Program instruction](https://denvergov.org/files/assets/public/v/2/denver-human-services/documents/property-tax-relief/dptr-instructions-2023.pdf)
