### ISSUE TITLE
Indiana additional exemption amount for adopted children

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-us#4789]
[Law](https://law.justia.com/codes/indiana/title-6/article-3/chapter-1/section-6-3-1-3-5/)
"D) Three thousand dollars ($3,000) for each exemption allowed under Section 151(c) of the Internal Revenue Code (as effective January 1, 2017) for an individual who is:

(i) an adopted child of the taxpayer; and

(ii) less than nineteen (19) years of age or is a full-time student who is less than twenty-four (24) years of age.

"

**Comment by PavelMakarchuk** [comment]
Also includes an additional definition in the 2023 [Booklet](https://forms.in.gov/Download.aspx?id=15792) which should be looked into:
![image](https://github.com/user-attachments/assets/5ffa15bb-ab26-420e-a922-3d92318513a5)

**Comment by vrathi101** [comment]
for the adoption exemption, the base amount in the legal code is 3000 so this tax form additional definition wouldn't really apply right, it would only make sense if the base amount was 1500? which may be the case for other IN exemptions

**Comment by PavelMakarchuk** [comment]
> for the adoption exemption, the base amount in the legal code is 3000 so this tax form additional definition wouldn't really apply right, it would only make sense if the base amount was 1500? which may be the case for other IN exemptions

I am reading this as the exemption is 3,000 for the year of adoption and after that the child receives the regular 1,500 exemption amount as each child
