### ISSUE TITLE
California Lifeline

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#4806]
Bumps discount from federal $9.25 to $19

 https://www.cpuc.ca.gov/consumer-support/financial-assistance-savings-and-discounts/lifeline/california-lifeline-eligibility

https://leginfo.legislature.ca.gov/faces/codes_displayText.xhtml?lawCode=PUC&division=1.&title=&part=1.&chapter=4.&article=8.

Let's also check the eligibility

**Comment by PavelMakarchuk** [comment]
@Mshuning similar approach as in the `snap_min_allotment.py` e.g. PR #4734 
We would need a bool parameter for in_effect and an amount parameter specific for CA 

Similar in #4809
