### ISSUE TITLE
California Revised State Median Income (SMI) Ceilings  

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-us#4808]
[Reference](https://cdss.ca.gov/Portals/9/Additional-Resources/Letters-and-Notices/CCBs/2024/CCB_24-12.pdf?ver=2024-07-02-114041-930)

**Comment by vrathi101** [comment]
@PavelMakarchuk are these the official 2024 values for all states? https://www.acf.hhs.gov/sites/default/files/documents/ocs/COMM_LIHWAP_Att1SMITable_FY2023.pdf
if so should I file a new issue to update all SMI ceilings
