### ISSUE TITLE
TCE eligibility

### ISSUE THREAD

**Issue by shuyu7zhan** [PolicyEngine/policyengine-us#4823]
https://www.irs.gov/individuals/free-tax-return-preparation-for-qualifying-taxpayers

In addition to VITA, the TCE program offers free tax help, particularly for those who are 60 years of age and older, specializing in questions about pensions and retirement-related issues unique to seniors.

**Comment by vrathi101** [comment]
https://github.com/PolicyEngine/policyengine-us/pull/4770

**Comment by vrathi101** [comment]
Resolved via Issue #4751
