### ISSUE TITLE
Refactor the `household_benefits` and `household_state_benefits` variable to include a list parameter

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-us#4863]
This will allow us to set start dates for program, currently we do not account for program start dates

**Comment by vrathi101** [comment]
@PavelMakarchuk do we want to do the same for `household_benefits` variable as well

**Comment by PavelMakarchuk** [comment]
> @PavelMakarchuk do we want to do the same refactoring for `household_benefits` variable as well

yes pleas
