### ISSUE TITLE
Delaware Pension Exclusion Under 60 Starting in 2022

### ISSUE THREAD

**Issue by DTrim99** [PolicyEngine/policyengine-us#4931]
Increased military pension exclusion from $2,000 to $12,500 for retirees under 60 (matches current exclusion for retirees over 60). 

[Reference](https://legis.delaware.gov/BillDetail/79131)

**Comment by DTrim99** [comment]
amount.yaml needs update

First amount beginning on 2023-01-01 goes to 12_500

**Comment by PavelMakarchuk** [comment]
This is currently reflected in the [`de_pension_exclusion.py`](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/variables/gov/states/de/tax/income/subtractions/pension_exclusion/de_pension_exclusion.py#L53)

This is also tested in [this](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/tests/policy/baseline/gov/states/de/tax/income/subtractions/pension_exclusion/de_pension_exclusion.yaml#L59) file
