### ISSUE TITLE
Indiana homestead property tax deduction increase

### ISSUE THREAD

**Issue by DTrim99** [PolicyEngine/policyengine-us#4933]
The property tax homestead deduction is increased by $3,000 in 2023. This allows taxpayers to deduct the lesser of 60 percent of the property's assessed value or $48,000 (up from $45,000) in 2022.

[Reference](https://taxfoundation.org/research/all/state/2023-state-tax-changes/)

**Comment by PavelMakarchuk** [comment]
@DTrim99 we need to double check the implementation here, as this is what I see in the 2023 Indiana [instructions](https://forms.in.gov/Download.aspx?id=15792):
![image](https://github.com/user-attachments/assets/7c4112ec-9f2c-4d03-bf9c-e15f5be7b6db)

**Comment by PavelMakarchuk** [comment]
[Schedule 2 (2023):](https://forms.in.gov/Download.aspx?id=13427)

![image](https://github.com/user-attachments/assets/4f9bfc5b-52f4-4909-9ed8-38ffa41a4e9f)

**Comment by PavelMakarchuk** [comment]
Seeing this in the[ legal code](https://iga.in.gov/laws/2024/ic/titles/6)
![image](https://github.com/user-attachments/assets/d436f5c4-e65f-495f-8427-1ee91b2e8863)

This seems to relate just to property taxes and not the income tax code

**Comment by PavelMakarchuk** [comment]
Closing the issue for now as this seems to relate to property taxes

**Comment by MaxGhenis** [comment]
Is it based on income?
