### ISSUE TITLE
Mississippi Income Tax Rates 2023 to 2026

### ISSUE THREAD

**Issue by DTrim99** [PolicyEngine/policyengine-us#4940]
In 2023, Mississippi has a 0% tax bracket from $0 to $10,000. Any income over $10,000 is taxed at 5%. The top rate decreases to 4.7% in 2024, 4.4% in 2025 and 4% in 2026 and beyond. PE attempts to account for this, but it needs to be fixed or at least simplified. 

[Reference](https://www.dor.ms.gov/individual/tax-rates)

**Comment by PavelMakarchuk** [comment]
@DTrim99 This is reflected in the rates parameter in MS, however due to the changing bracket structure, I can see how it can be misinterpreted in the WebApp - will close the issue and move to a more broad discussion
