### ISSUE TITLE
District of Columbia Standard Deduction and Additional Standard Deduction

### ISSUE THREAD

**Issue by DTrim99** [PolicyEngine/policyengine-us#4961]
D.C. has a standard deduction in line with the federal standard for 2022 and 2023. It also has an additional deduction for elderly and blind residents. $1,750 for single or HOH, $1,400 for other households in 2022. $1,850 for single or HOH, $1,500 for other households in 2023.

[2022](https://otr.cfo.dc.gov/sites/default/files/dc/sites/otr/publication/attachments/2022_D-40_Booklet_Final_blk_01_23_23_Ordc.pdf)

[2023](https://otr.cfo.dc.gov/sites/default/files/dc/sites/otr/publication/attachments/2023_D40_Book_Final_041124.pdf)

**Comment by MaxGhenis** [comment]
We do this today: https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/variables/gov/states/dc/tax/income/deductions/dc_standard_deduction.py

In general we will not create separate parameters for state policies that point to federal parameters; instead, we apply the law and only create parameters once per statutory appearance.
