### ISSUE TITLE
Exclude students from the SNAP unit if they are students.

### ISSUE THREAD

**Issue by CalebPena** [PolicyEngine/policyengine-us#4962]
Per SNAP Screener

> Students attending an institution of higher education half-time or more are only eligible for SNAP if they meet an exemption. These exemptions include meeting any of the following:
Being under age 18 or being 50 or older
Working at least 20 hours a week in paid employment
Participating in a state or federally financed work study program
Having a physical or mental disability
To see a full list of exemptions for students, [click here](https://www.fns.usda.gov/snap/students). Some less common exemptions may vary by state. If a student does not meet any of the student exemptions, they are likely not eligible for SNAP benefits.
If your household includes a student that does not meet the student eligibility requirements and therefore is ineligible for SNAP, restart this calculator without including the student as part of your household size and without counting any income or assets of the student.

**Comment by MaxGhenis** [comment]
Statutory reference: https://www.law.cornell.edu/uscode/text/7/2015
