### ISSUE TITLE
Pin policyengine-core to >=3.6.0

### ISSUE THREAD

**Issue by CalebPena** [PolicyEngine/policyengine-us#4963]
The latest version of [policyengine-core](https://github.com/PolicyEngine/policyengine-core) is not installed automatically. i.e. If you already have policyengine-core installed locally, and you run `make install`, the version will not be updated.

A similar situation is handled in the API by using the exact version number. [Example](https://github.com/PolicyEngine/policyengine-api/blob/b465e09b91433287d07261a23a54cfc987973b98/setup.py#L23-L28)

**Comment by MaxGhenis** [comment]
Updated based on new -core updates being necessary for avoiding bugs in -us: https://github.com/PolicyEngine/policyengine-core/blob/master/CHANGELOG.md
