### ISSUE TITLE
Refactor ut_income_tax formula 

### ISSUE THREAD

**Issue by hua7450** [PolicyEngine/policyengine-us#4982]
The current formula for ut_income_tax has some missing calculations. 
Tax form: https://tax.utah.gov/forms/current/tc-40.pdf # line 22 & 32

**Comment by MaxGhenis** [comment]
Are we missing logic? #993 shows not deviations against TAXSIM for Utah, but `missing calculations` suggests problems beyond refactoring.

**Comment by hua7450** [comment]
> Are we missing logic? #993 shows not deviations against TAXSIM for Utah, but `missing calculations` suggests problems beyond refactoring.

We have `ut_income_tax_exempt` as a boolean where taxpayers can be exempted from paying tax, but this variable has not been used in any formula.  I added it to the `ut_income_tax_before_non_refundable_credits`. In the [tax form](https://tax.utah.gov/forms/current/tc-40.pdf), the `ut_income_tax_before_non_refundable_credits` is called Utach income tax (line 22). I changed the name so the variable names are more consistent with other states'.
