### ISSUE TITLE
New York Additional Empire State Child Credit Payments (Only Tax Year 2021)

### ISSUE THREAD

**Issue by DTrim99** [PolicyEngine/policyengine-us#5014]
The additional Empire State child credit payments were only for tax year 2021. PE has it continuing in perpetuity. 

[Reference](https://www.tax.ny.gov/pit/child-earned-payments.htm)

**Comment by hua7450** [comment]
The additional Empire State child credit payments ([ny_additional_ctc](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/parameters/gov/states/ny/tax/income/credits/refundable.yaml)) were for 2021 and 2023, as it is in PE right now.

**Comment by MaxGhenis** [comment]
This isn't obvious in the web app since we remove them from a list parameter in other years rather than zero out the value, but it is WAI
