### ISSUE TITLE
Oklahoma Military Retirement Benefit Exclusion 2022

### ISSUE THREAD

**Issue by DTrim99** [PolicyEngine/policyengine-us#5017]
![OK military retirement benefits](https://github.com/user-attachments/assets/5fbb6a56-1516-4375-bc5b-9757ca5cabd6)

[Reference](https://taxsim.nber.org/historical_state_tax_forms/OK/2022/511-Pkt.pdf)

**Comment by hua7450** [comment]
![image](https://github.com/user-attachments/assets/abc430b6-5da9-4a7b-a15f-71b825dc8506)
![image](https://github.com/user-attachments/assets/dbe317c6-b12c-40e3-8f67-ea4643dc156a)
Both active and retirement pay are 100% exempted start in 2022.
