### ISSUE TITLE
Limit Colorado deductions for filers with income above $300,000 starting in 2023

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#5020]
https://www.chalkbeat.org/colorado/2022/11/8/23448263/proposition-ff-colorado-school-lunch-midterm-elections-2022-election-results/

**Comment by PavelMakarchuk** [comment]
We already account for this in the [Colorado state add back](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/variables/gov/states/co/tax/income/additions/co_state_addback.py) - I am fairly sure this is what the article refers to

**Comment by MaxGhenis** [comment]
Where's the $300,000?

**Comment by PavelMakarchuk** [comment]
[agi_threshold.yaml](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/parameters/gov/states/co/tax/income/additions/federal_deductions/agi_threshold.yaml)
