### ISSUE TITLE
South Carolina Top Tax Rate Reduction 2023

### ISSUE THREAD

**Issue by DTrim99** [PolicyEngine/policyengine-us#5027]
Lower top tax rate from 6.5% to 6.4%.

[Reference](https://dor.sc.gov/forms-site/Forms/SC1040TT_2023.pdf)

**Comment by hua7450** [comment]
The current South Carolina's top tax rate in 2023 is 6.4% in PE.  
![image](https://github.com/user-attachments/assets/b021d2c3-4a26-4587-b9d5-581cbb6e49ac)

**Comment by PavelMakarchuk** [comment]
> The current South Carolina's top tax rate in 2023 is 6.4%. ![image](https://private-user-images.githubusercontent.com/113824411/364822178-b021d2c3-4a26-4587-b9d5-581cbb6e49ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NDgxNDksIm5iZiI6MTcyNTU0Nzg0OSwicGF0aCI6Ii8xMTM4MjQ0MTEvMzY0ODIyMTc4LWIwMjFkMmMzLTRhMjYtNDU4Ny1iOWQ1LTU4MWNiYjZlNDlhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxNDUwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGI1MmY3YjQwYTBiZDE1MTEwYWJlNzVlOGEyNzY0N2M0OGE3ZmI3ZGIzMTk1ZmE5YTdiYTBjZDAwY2ZlY2IxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cCt-SpAyumjeLy6IQiWHBYrSkyq6bG-bEYrLcWRRuBs)

I see, this is due to the changed brackets - the [rate](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/parameters/gov/states/sc/tax/income/rates.yaml) is 6.4% but there are other higher brakcets which do not effect 2023 - closing the issue but we should really think about formatting adjustmets
