### ISSUE TITLE
Calculation issue in various state-level taxes

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-us#5083]
While doing some testing on the Policy2Code back-end changes, I find that even when calculating outputs for a family from Alabama, I receive a value for both of these variables that does not equal the default value defined in the metadata. There may be some sort of calculation issue here, perhaps not checking to ensure the household lives in Illinois (unless Illinois collects universally, which I wouldn't put past them).

**Comment by MaxGhenis** [comment]
Indeed, missing `defined_for`: https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/variables/gov/states/il/tax/income/credits/il_eitc.py

**Comment by anth-volk** [comment]
This is also true for `mt_eitc`, as well as potentially some other Illinois taxes and credits.

**Comment by PavelMakarchuk** [comment]
There should be a couple of state level variables - need to check and add a defined for

**Comment by PavelMakarchuk** [comment]
@srilareddy can you take a look
