### ISSUE TITLE
Rhode Island EITC Match Increase 2024 (15% -> 16%)

### ISSUE THREAD

**Issue by DTrim99** [PolicyEngine/policyengine-us#5130]
[Reference](https://tax.ri.gov/sites/g/files/xkgbur541/files/2023-09/ADV%202023-13.pdf)

**Comment by MaxGhenis** [comment]
Can you find a statutory reference?

**Comment by DTrim99** [comment]
![RI EITC 16%](https://github.com/user-attachments/assets/f2c2e427-116b-4f28-95f0-7abae5136020)

[Updated reference](https://webserver.rilegislature.gov/billtext23/housetext23/h5200aaa.htm)

**Comment by DTrim99** [comment]
https://github.com/PolicyEngine/policyengine-us/blob/7ba8021d14658eacb36912c7b4213ffcc6343a15/policyengine_us/parameters/gov/states/ri/tax/income/credits/eitc/match.yaml#L1-L4
