### ISSUE TITLE
North Carolina Future Income Tax Rate Cuts

### ISSUE THREAD

**Issue by DTrim99** [PolicyEngine/policyengine-us#5131]
![NC income tax ](https://github.com/user-attachments/assets/c31845a1-b30a-444a-9e0e-2d78b0508f7b)

[Reference](https://www.ncleg.gov/Sessions/2023/Bills/House/PDF/H259v7.pdf)

**Comment by DTrim99** [comment]
https://github.com/PolicyEngine/policyengine-us/blob/7ba8021d14658eacb36912c7b4213ffcc6343a15/policyengine_us/parameters/gov/states/nc/tax/income/rate.yaml#L1-L23

**Comment by PavelMakarchuk** [comment]
@YichunRen can you take a look?
