### ISSUE TITLE
Kentucky Standard Deduction 2024 ($3,160)

### ISSUE THREAD

**Issue by DTrim99** [PolicyEngine/policyengine-us#5134]
Increased with Inflation ($180 greater than 2023)

[Reference](https://apps.legislature.ky.gov/law/statutes/statute.aspx?id=29067)

**Comment by MaxGhenis** [comment]
https://github.com/PolicyEngine/policyengine-us/blob/7ba8021d14658eacb36912c7b4213ffcc6343a15/policyengine_us/parameters/gov/states/ky/tax/income/deductions/standard.yaml#L1-L6

**Comment by MaxGhenis** [comment]
Where's $3,150? We already apply inflation adjustments.

https://policyengine.org/us/policy?focus=gov.states.ky.tax.income.deductions.standard

<img width="773" alt="image" src="https://github.com/user-attachments/assets/b69f96a2-783f-42c5-b3d4-13273409ff0b">
