### ISSUE TITLE
SNAP Standard Medical Deduction Offset 

### ISSUE THREAD

**Issue by vrathi101** [PolicyEngine/policyengine-us#5139]
https://www.fns.usda.gov/snap/eligibility/deduction/standard-utility-allowances

**Comment by vrathi101** [comment]
Sorry maybe I missed something, do we model the offset amount, it's the last column in the Excel sheet

**Comment by MaxGhenis** [comment]
How does it work? [ChatGPT wasn't very clear](https://chatgpt.com/share/66f75a0f-9e84-8001-bbc0-88d5fb38680a) and it's not in snapscreener.com as far as I could tell.

**Comment by vrathi101** [comment]
Yeah I'm not sure either, I was trying to find resources to explain it but there doesn't seem to be any, Perplexity didn't explain well either

**Comment by MaxGhenis** [comment]
@benmolin do you know how the SMD offset works?

**Comment by benmolin** [comment]
> Another area of concern for some states is that they must show that the waiver will not increase
> federal costs. FNS has worked with states to calculate the required savings to ensure cost neutrality.
> Most states offset the waiver’s cost by reducing their standard utility allowance63 (SUA) or forgoing a
> small cost-of-living increase in the SUA. This is an important policy decision, as it means cutting
> benefits to some SNAP recipients (individuals with out-of-pocket utility costs) to benefit others
> (individuals with medical expenses).

From https://www.cbpp.org/sites/default/files/atoms/files/8-20-14fa.pdf#page=29

The offset amount wouldn't be part of the equation when calculating a household's SNAP benefit.

Also see https://pubmed.ncbi.nlm.nih.gov/37549333/

**Comment by MaxGhenis** [comment]
Thank you @benmolin!
