### ISSUE TITLE
District Child Tax Credit

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#5183]
The DC Council passed this as part of the budget earlier this year, and while the Mayor didn't sign it, someone told me it has become law through a congressional mechanism.

**Comment by hua7450** [comment]
Bill status: https://legiscan.com/DC/bill/B25-0190/2023
Bill text: https://legiscan.com/DC/text/B25-0190/id/2729286/Washington_D_C_-2023-B25-0190-Introduced.pdf

**Comment by MaxGhenis** [comment]
Yes but it is law, despite the bill status. Please check the legal code, and potentially other sources.
