### ISSUE TITLE
Set Additional Medicare Tax and NIIT Thresholds to $400,000 for 2025. 

### ISSUE THREAD

**Issue by DTrim99** [PolicyEngine/policyengine-us#5230]
Analysis of the Harris piece should begin in 2025 with the thresholds at their base rates before beginning to uprate in 2026 and beyond.

Additional Medicare Tax:

https://github.com/PolicyEngine/policyengine-us/blob/17630f01127590407bc7f7a67d8c04e8d407e34e/policyengine_us/parameters/gov/contrib/biden/budget_2025/medicare/threshold.yaml#L1-L12

NIIT:

https://github.com/PolicyEngine/policyengine-us/blob/17630f01127590407bc7f7a67d8c04e8d407e34e/policyengine_us/parameters/gov/contrib/biden/budget_2025/net_investment_income/threshold.yaml#L1-L12

**Comment by MaxGhenis** [comment]
Based on what? The [Treasury document](https://home.treasury.gov/system/files/131/General-Explanations-FY2025.pdf#page=85) looks like it indexes starting in 2024:

>The proposal would increase the additional Medicare tax rate by 1.2 percentage points for taxpayers with more than $400,000 of earnings. When combined with current-law tax rates, this would bring the marginal Medicare tax rate up to 5 percent for earnings above the threshold. The threshold would be indexed for inflation.

>The proposal would also increase the NIIT rate by 1.2 percentage points for taxpayers with more than $400,000 of income, similarly bringing the marginal NIIT rate to 5 percent for investment income above the threshold. Specifically, for taxpayers with positive net investment income, the NIIT would increase by 1.2 percentage points on the lesser of (a) net investment income or (b) the excess, if any, of modified adjusted gross income over $400,000. The threshold would be
indexed for inflation.

>Under the proposal, the revenue from the NIIT (that raised under current law and that which would be raised under any proposed expansion) would be directed to the HITF in the same manner as the revenue from the current 3.8 percent tax on earnings and the proposed additional 1.2 percent tax on earnings.

>The proposal would be effective for taxable years beginning after December 31, 2023

**Comment by DTrim99** [comment]
My assumption was because the proposal would not be passed in 2024 that all provisions should begin in 2025, including the thresholds. Looking at the text I think either way is reasonable, whichever you think is best I'm good with.
