### ISSUE TITLE
Pregnant person counts as 2 for purposes of Medicaid

### ISSUE THREAD

**Issue by CalebPena** [PolicyEngine/policyengine-us#5248]
CO regs: https://www.sos.state.co.us/CCR/GenerateRulePdf.do?ruleVersionId=11618&fileName=10%20CCR%202505-10%208.100

**Comment by MaxGhenis** [comment]
From page 58 of that document:
>When a household includes a pregnant woman, regardless of the Medical Assistance category, the pregnant woman is counted as herself plus the number of children she is expected to deliver.

[This CMS document](https://www.cms.gov/marketplace/technical-assistance-resources/special-populations-pregnant-women.pdf) provides more guidance:
>For Medicaid eligibility, if a pregnant woman is seeking an eligibility determination for herself, she is counted as one person plus the number of children expected to deliver. However, if a pregnant woman is in the household of someone who is seeking a Medicaid eligibility determination, states can opt to count her as one person, two people, or one person plus the number of children expected.

I'll merge #5249 as it gets us closer to the right logic, especially in Colorado. I also filed #5250 and #5251 to improve the logic.
