### ISSUE TITLE
Don't uprate SNAP standard medical deduction and SNAP standard utility allowance

### ISSUE THREAD

**Issue by CalebPena** [PolicyEngine/policyengine-us#5284]
@MaxGhenis What do you think about removing the uprating on the following (there may be others as well, but these are the ones that I found are incorrect for 2025 in CO) because they don't appear to be updated each year:

- [SNAP standard medical deduction](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/parameters/gov/usda/snap/income/deductions/excess_medical_expense/standard.yaml)
- [SNAP standard utility allowance](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/parameters/gov/usda/snap/income/deductions/utility/standard/main.yaml)

**Comment by MaxGhenis** [comment]
This makes sense to me. They rise more often than they fall, but we should limit uprating to cases where the state specified it as such in its laws/regs.
