### ISSUE TITLE
New Jersey 2023 Exemption discrepancy

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-us#5292]
In TaxAct a single New Jersey elderly 2023 taxpayer with 100,000 in pwages and no dependents or deductions  has 4116 in liability, while the emulator reports 3925. See:

   http://taxsim.nber.org/out2psl/test10

for the TaxAct return etc. The difference appears to be in Taxable Income, perhaps TaxAct is missing 3000 in exemptions?

**Comment by PavelMakarchuk** [comment]
Moving the issue to the Emulator
