### ISSUE TITLE
California 2023 Joint return one dep 81k wage

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-us#5293]
At

http://taxsim.nber.org/out2psl/test11

I have put a TaxAct filled out form for joint return with 81000 in wage income by the primary taxpayer and a single 4 year old dependent. Taxable income is 70274 in TaxAct, and  75637 in the emulator. The difference in the standard deduction explains that difference, but that is not sufficient to explain the difference in tax.  There is also a difference in credits.

**Comment by PavelMakarchuk** [comment]
@feenberg I spoke with Al and he has confirmed that we currently don't account for dependents in the emulator - we will file an issue in the emulator repository and once that is closed we can test for situations which include dependents
