### ISSUE TITLE
Vermont 2023 81k wage joint 1dep

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-us#5294]
At 

http://taxsim.nber.org/out2psl/test12

I have posted a TaxAct prepared 2023 joint return for Vermont with 81K wages and 1 dep. The standard deduction differs from the emulator - 14050 v 7000, but that does not fully explain the difference in taxable income (52400 v 69150) or tax(755 v  3088) although part of that may be the child tax credit.

**Comment by PavelMakarchuk** [comment]
I would like to close this issue and re-run once the standard deduction questions in [#75](https://github.com/PolicyEngine/policyengine-taxsim/issues/75) are resolved
