### ISSUE TITLE
Maine 81kwages joint one dep

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-us#5295]
.At

http://taxsim.nber.org/out2psl/test13

I have posted a TaxAct return for Maine, joint 81k wages, one dep. TaxAct shows a standard deduction of  27700 while the emulator shows zero, leading to a large descrepancy in tax.

**Comment by PavelMakarchuk** [comment]
This should also be further investigate after [#75](https://github.com/PolicyEngine/policyengine-taxsim/issues/75) in the emulator app is resolved the the standard deduction amount is displayed
