### ISSUE TITLE
Idaho 81K wages joint, one dep

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-us#5296]
At

http://taxsim.nber.org/out2psl/test14

I have posted a TaxAct form for Idaho, joint 81K wages,one dep 2023 year. It shows a Taxable Income of 53300 while the emulator reports 67150. The emulator doesn't report a non-zero standard deduction or the Grocery Credit (line 43 of Form 40).

**Comment by PavelMakarchuk** [comment]
@feenberg the rules engine returns a value for this case, I moved this issue to [#67](https://github.com/PolicyEngine/policyengine-taxsim/issues/67) in the emulator repository
