### ISSUE TITLE
Utah 81k wage joint one dep

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-us#5299]
Utah 81k wage joint one dep

http://taxsim.nber.org/out2psl/test17

Looks like the emulator is missing  Line 20 - Taxpayer Tax Credit of 1160.

**Comment by PavelMakarchuk** [comment]
Local tests show the correct taxpayer credit amount I have field issue [#79](https://github.com/PolicyEngine/policyengine-taxsim/issues/79) in the emulator repository
