### ISSUE TITLE
New York 81K wage joint one dep 2023

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-us#5300]
New York 81K wage joint one dep 2023

http://taxsim.nber.org/out2psl/test19

Note that the tax before penalty doesn't appear on the form  IT-201.  It is Line 62 less line 76 (3186-330=2856). That is what should match to the emulator siitax value.

The standard deduction in the emulator is 8000, but 16000 in TaxAct. Also, I think the dependent exemption (1000) is missing.

**Comment by PavelMakarchuk** [comment]
Local tests show the correct standard deduction as well as dependent exemption amounts 

I have filed issue [#78](https://github.com/PolicyEngine/policyengine-taxsim/issues/78) in the emulator repository
