### ISSUE TITLE
Rhode Island 2023  81k wage joint one dep

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-us#5303]
Rhode Island 2023 81k wage joint one dep

http://taxsim.nber.org/out2psl/test22

TaxAct has standard deduction of 20050, emulator shows 10000.

**Comment by PavelMakarchuk** [comment]
This is an issue with the emulator, local tests return #20,050 for the RI standard deduction have filed issue [#77](https://github.com/PolicyEngine/policyengine-taxsim/issues/77) in the emulator repository
