### ISSUE TITLE
Oklahoma 2023 81k wage joint one dep

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-us#5304]
Oklahoma 2023 81k wage joint one dep

http://taxsim.nber.org/out2psl/test23

Standard deduction is larger in emulator than in TaxAct.

**Comment by PavelMakarchuk** [comment]
There seems to be a more general issue with the output of the standard deduction in most of the states I would like to close issue [#75](https://github.com/PolicyEngine/policyengine-taxsim/issues/75) in the emulator and then re-run individual states to see if we get new differences and open new issues with the correct outputs
