### ISSUE TITLE
Missouri 2023 Joint 81k wage one dep

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-us#5305]
Missouri 2023 Joint 81k wage one dep

http://taxsim.nber.org/out2psl/test24

Perhaps a problem with the standard deduction in the emulator - which displays as zero, but taxable income suggests it is probably using 13850, while TA uses 27700.

**Comment by PavelMakarchuk** [comment]
@feenberg there are a couple of states with this issue as Missouri uses the federal standard deduction as opposed to a separate state calculation - the emulator currently returns 0 for those cases - for this case I filed issue [#75](https://github.com/PolicyEngine/policyengine-taxsim/issues/75) in the emulator repository - will like to resolve this before doing further investigations with more accurate outputs
