### ISSUE TITLE
North Dakota 2023 joint 81k wages one dep

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-us#5306]
North Dakota 2023 joint 81k wages one dep

http://taxsim.nber.org/out2psl/test30

Hard to guess what is wrong when there are no intermediate values.

**Comment by PavelMakarchuk** [comment]
It seems like taxsim returns a value for this household but if I am reading the taxcode correctly, then this household should have a total of $53,300 (81,000 - 27,700 (standard deduction) ) in federal taxable income which should result in a 0% state income tax rate

![image](https://github.com/user-attachments/assets/88af8d7a-8460-492d-bb08-6ed6c7c772e8)
![image](https://github.com/user-attachments/assets/53c2a45c-a3ba-4a39-b5ce-e5f7d1646c06)

**Comment by PavelMakarchuk** [comment]
After speaking with Al, we need to wait until dependents are included in the emulator inputs and then we can re-run all tests which include dependents in the households
