### ISSUE TITLE
Make childcare expenses per-child

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-us#836]

**Comment by MaxGhenis** [comment]
Related: I just tried abolishing CDCC in PolicyEngine and it had no effect on a family with $6,000 childcare expenses. Seems wrong? https://policyengine.org/us/household?abolish_cdcc=1

**Comment by martinholmer** [comment]
@nikhilwoodruff,  I'm an OpenFisca novice, so I don't understand exactly what "make childcare expenses per-child" means.  But like @MaxGhenis, I'm seeing problems with the current CDCC formula as I describe in issue #837.

**Comment by MaxGhenis** [comment]
This is coming up in NYC as well, where they limit their CDCC to expenses for children under age 4. @leogoldman
